/**
 * 祝福の定義表（データのみ）。ロジックは system/boons.ts（抽選・選択・既存のフック）と
 * system/boonRules.ts（拡張で足したルール）。docs/ideas/boons-expansion.md
 */

export const BOON_KEYS = [
  "finisherOnly",
  "dashGun",
  "reflect",
  "justSlash",
  "lockdown",
  "glassJust",
  "comboWave",
  "heartBurn",
  "eliteVault",
  "secondWind",
  "giantSlayer",
  "dashBlast",
  "justWipe",
  "clearShield",
  "clearHeal",
  "finisherWave",
  "rearGuard",
  "standingSniper",
  "triggerHappy",
  "dashGuard",
  "comboKeeper",
  "comboClock",
  "overcharge",
  "burstRefund",
  "burnSpread",
  "chillShatter",
  "dashShock",
  "critChain",
  "bloodFeast",
  "eliteMagnet",
  "frostLock",
  "lopsided",
  "swapHands",
  "spiritBlade",
  "plague",
  "bloodMist",
  "crumble",
  "frostPierce",
  "springWell",
  "bloodMana",
  "reaperCup",
  "keenBreath",
  "circulation",
  "hollowVessel",
  // ---- 系譜: 灰燼（燃焼） ----
  "emberSeed",
  "wildfire",
  "ashBed",
  "scorchedEarth",
  // ---- 系譜: 霜枷（冷気・凍結） ----
  "frostBreath",
  "frostFeet",
  "shatterBell",
  "eternalWinter",
  // ---- 系譜: 雷鳴（感電・麻痺） ----
  "staticDash",
  "chargedBlade",
  "thunderMark",
  "thunderDrum",
  // ---- 系譜: 月蝕（マナ・スキル・沈黙） ----
  "moonRead",
  "highTide",
  "newMoon",
  "eclipse",
  // ---- 単体（docs/ideas/boons-expansion.md 1 章） ----
  "bulletSteal",
  "silenceShot",
  "glare",
  "intimidate",
  "reaperPlay",
  "wakeupHunt",
  "elementTrail",
  "recall",
  "huntBleed",
  "frostRead",
  "venomBreak",
  "insight",
  "twinWheels",
  "iceRelay",
  "trialSeeker",
  "oneWing",
  "justReturn",
  "passCut",
  "ricochet",
  "warhead",
  "weakSpot",
  "embers",
  "nerveCut",
  "bloodReturn",
  "laceration",
  "frayWiden",
  "backstab",
  "quietHall",
  "keenEye",
  "collapseChain",
  "regroupHunt",
  "edgeStrike",
  "cashOut",
  "takeBack",
  "woundMemory",
  "reaperShadow",
  "stallTime",
  "deathRush",
  "burden",
  "karmaFire",
  "heavenEarth",
  "afterglow",
  "ambushReturn",
  "appraise",
  "usurp",
  "tightrope",
  "swallowFlight",
  "chantReturn",
  "fullMoonShot",
  "carryOver",
  "fireWalk",
  // ---- 結び（2 つの祝福を持つと出る） ----
  "swallowReturn",
  "plagueBlood",
  "thunderBlast",
  "totalCollapse",
  "feastCup",
  "criticalMass",
  "hollowBlade",
  "winterNest",
  "clearMirror",
  "stillDash",
  "waveReturn",
] as const;

export type BoonKey = (typeof BOON_KEYS)[number];
export type BoonRarity = "common" | "rare" | "epic";
export type BoonTag =
  | "melee"
  | "ranged"
  | "dash"
  | "just"
  | "combo"
  | "energy"
  | "burn"
  | "chill"
  | "shock"
  | "explode"
  | "crit"
  | "hp"
  | "room"
  | "loot"
  | "boss"
  | "attr"
  | "poison"
  | "bleed"
  | "stagger"
  | "mana"
  | "freeze"
  | "paralyze"
  | "vulnerable"
  | "weaken"
  | "fear"
  | "silence"
  | "guarded"
  | "counter"
  | "skill"
  | "placed"
  | "reaper";

/** 系譜（同じ主から出る 4 段の祝福）。前段を持っていると次段が抽選に出る */
export type LineageKey = "ash" | "frost" | "thunder" | "moon";

/** 系譜の表示名（カードと HUD の注記） */
export const LINEAGE_LABEL: Readonly<Record<LineageKey, string>> = {
  ash: "灰燼",
  frost: "霜枷",
  thunder: "雷鳴",
  moon: "月蝕",
};

export interface BoonDef {
  key: BoonKey;
  name: string;
  desc: string;
  /** HUD のアイコン文字（1 文字） */
  icon: string;
  rarity: BoonRarity;
  tags: readonly BoonTag[];
  /** その祝福が作り出すもの（燃焼・脆弱など）。持っていると、それを食う祝福の重みが上がる */
  gives?: readonly BoonTag[];
  /** 呪い付き（強い効果 + 代償）。3 択のうち 1 枠に確率で混ざる */
  cursed: boolean;
  /** このタグを装備（またはスキル石）が持っていないと出ない（burn の無い装備に燃焼祝福を出さない） */
  requires?: BoonTag;
  /** 系譜。同じ系譜は 1 回の 3 択に 1 枚まで */
  lineage?: LineageKey;
  /** 系譜の前段。これを持っていないと出ない */
  after?: BoonKey;
  /** 結び: この 2 つを両方持っていないと出ない */
  duo?: readonly [BoonKey, BoonKey];
}

export const BOONS: Readonly<Record<BoonKey, BoonDef>> = {
  finisherOnly: {
    key: "finisherOnly",
    name: "終撃のみ",
    desc: "近接は常に3段目のみ。1・2段目は出ない。",
    icon: "3",
    rarity: "rare",
    tags: ["melee"],
    cursed: false,
  },
  dashGun: {
    key: "dashGun",
    name: "疾走射撃",
    desc: "ダッシュ中でも射撃できる。",
    icon: "»",
    rarity: "common",
    tags: ["ranged", "dash"],
    cursed: false,
  },
  reflect: {
    key: "reflect",
    name: "弾返し",
    desc: "近接攻撃で敵弾を撃ち返す。撃ち返すと必殺ゲージが3倍増える。",
    icon: "P",
    rarity: "common",
    tags: ["melee", "energy"],
    cursed: false,
  },
  justSlash: {
    key: "justSlash",
    name: "見切り斬り",
    desc: "ジャスト回避の直後に攻撃すると、回避した敵の目の前へ瞬間移動して斬る。",
    icon: "/",
    rarity: "rare",
    tags: ["just", "melee"],
    gives: ["counter"],
    cursed: false,
  },
  lockdown: {
    key: "lockdown",
    name: "封鎖疾走",
    desc: "封鎖中は移動速度+30%になる代わりに、それ以外では-10%になる。",
    icon: "L",
    rarity: "common",
    tags: ["room", "dash"],
    cursed: true,
  },
  glassJust: {
    key: "glassJust",
    name: "硝子の見切り",
    desc: "最大HPが1になる代わりに、ジャスト回避の受付時間が2倍になる。",
    icon: "G",
    rarity: "epic",
    tags: ["just", "dash"],
    cursed: true,
  },
  comboWave: {
    key: "comboWave",
    name: "連撃波",
    desc: "コンボ20以上で、斬るたびに貫通する衝撃波が出る。",
    icon: "W",
    rarity: "rare",
    tags: ["melee", "combo"],
    cursed: false,
  },
  heartBurn: {
    key: "heartBurn",
    name: "業火の心",
    desc: "ハートを拾うと10秒間、燃焼効果が2倍になる。",
    icon: "H",
    rarity: "common",
    tags: ["burn", "hp"],
    cursed: false,
    requires: "burn",
  },
  eliteVault: {
    key: "eliteVault",
    name: "宝物の鍵",
    desc: "エリートを倒すと、次の階に宝物庫が確定で出現する。",
    icon: "K",
    rarity: "rare",
    tags: ["loot"],
    cursed: false,
  },
  secondWind: {
    key: "secondWind",
    name: "再起",
    desc: "ラン中1回だけ、力尽きる代わりにHP30%で復活する。",
    icon: "R",
    rarity: "epic",
    tags: ["hp"],
    cursed: false,
  },
  giantSlayer: {
    key: "giantSlayer",
    name: "巨人殺し",
    desc: "ボスのHPが-25%になる代わりに、通常の敵のHPが+25%になる。",
    icon: "B",
    rarity: "common",
    tags: ["boss"],
    cursed: true,
  },
  dashBlast: {
    key: "dashBlast",
    name: "爆走",
    desc: "ダッシュの終わりに爆発が起こる。",
    icon: "X",
    rarity: "rare",
    tags: ["dash", "explode"],
    gives: ["explode"],
    cursed: false,
  },
  justWipe: {
    key: "justWipe",
    name: "回避一掃",
    desc: "ジャスト回避で敵弾を全て消し去る。",
    icon: "J",
    rarity: "rare",
    tags: ["just"],
    cursed: false,
  },
  clearShield: {
    key: "clearShield",
    name: "勝利の帳",
    desc: "部屋を制圧すると5秒間無敵になる。",
    icon: "V",
    rarity: "common",
    tags: ["room"],
    cursed: false,
  },
  clearHeal: {
    key: "clearHeal",
    name: "血の代償",
    desc: "部屋を制圧するとHPが全回復する代わりに、最大HPが-30%になる。",
    icon: "T",
    rarity: "rare",
    tags: ["room", "hp"],
    cursed: true,
  },
  finisherWave: {
    key: "finisherWave",
    name: "断裂波",
    desc: "3段目の斬撃で貫通する衝撃波が出る。",
    icon: "~",
    rarity: "common",
    tags: ["melee"],
    cursed: false,
  },
  rearGuard: {
    key: "rearGuard",
    name: "背面射撃",
    desc: "射撃するたびに後方へも弾を1発撃つ。",
    icon: "<",
    rarity: "common",
    tags: ["ranged"],
    cursed: false,
  },
  standingSniper: {
    key: "standingSniper",
    name: "静止狙撃",
    desc: "静止して撃った弾は貫通+3、速度+50%になる。",
    icon: "S",
    rarity: "common",
    tags: ["ranged"],
    cursed: false,
  },
  triggerHappy: {
    key: "triggerHappy",
    name: "連射狂い",
    desc: "連射速度が2倍になる代わりに、近接攻撃ができなくなる。",
    icon: "!",
    rarity: "rare",
    tags: ["ranged"],
    cursed: true,
  },
  dashGuard: {
    key: "dashGuard",
    name: "鉄壁の構え",
    desc: "ダッシュがその場の防御になり、防御中の被弾はJUST扱いになる。",
    icon: "I",
    rarity: "rare",
    tags: ["just", "dash"],
    cursed: true,
  },
  comboKeeper: {
    key: "comboKeeper",
    name: "堅実な手",
    desc: "被弾してもコンボが0にならず半分残る。",
    icon: "C",
    rarity: "common",
    tags: ["combo"],
    cursed: false,
  },
  comboClock: {
    key: "comboClock",
    name: "刻限コンボ",
    desc: "コンボ受付時間が半分になる代わりに、10コンボごとに必殺ゲージが満タンになる。",
    icon: "@",
    rarity: "rare",
    tags: ["combo", "energy"],
    gives: ["energy"],
    cursed: true,
  },
  overcharge: {
    key: "overcharge",
    name: "過充填",
    desc: "必殺ゲージが満タンの間、斬撃が爆発する。",
    icon: "O",
    rarity: "rare",
    tags: ["energy", "melee", "explode"],
    gives: ["explode"],
    cursed: false,
  },
  burstRefund: {
    key: "burstRefund",
    name: "残響爆発",
    desc: "バーストでの撃破ごとにゲージが25%還元される。",
    icon: "E",
    rarity: "common",
    tags: ["energy"],
    cursed: false,
  },
  burnSpread: {
    key: "burnSpread",
    name: "野火",
    desc: "燃えている敵は死亡時に周囲へ燃焼を広げる。",
    icon: "F",
    rarity: "common",
    tags: ["burn"],
    gives: ["burn"],
    cursed: false,
    requires: "burn",
  },
  chillShatter: {
    key: "chillShatter",
    name: "氷砕",
    desc: "凍えた敵は死亡時に氷の破片となって弾け飛ぶ。",
    icon: "*",
    rarity: "common",
    tags: ["chill"],
    gives: ["chill"],
    cursed: false,
    requires: "chill",
  },
  dashShock: {
    key: "dashShock",
    name: "帯電疾走",
    desc: "ダッシュ開始時に連鎖する雷を放つ。",
    icon: "Z",
    rarity: "rare",
    tags: ["dash", "shock"],
    gives: ["shock"],
    cursed: false,
  },
  critChain: {
    key: "critChain",
    name: "会心雷撃",
    desc: "クリティカルヒットで連鎖する雷を放つ。",
    icon: "A",
    rarity: "rare",
    tags: ["crit", "shock"],
    gives: ["shock"],
    cursed: false,
  },
  bloodFeast: {
    key: "bloodFeast",
    name: "血の饗宴",
    desc: "ハートが出なくなる代わりに、撃破するたびHP3回復する。",
    icon: "+",
    rarity: "rare",
    tags: ["hp"],
    cursed: true,
  },
  eliteMagnet: {
    key: "eliteMagnet",
    name: "エリート誘引",
    desc: "エリートの出現率が大きく上がる代わりに、エリートは必ずアイテムを落とす。",
    icon: "M",
    rarity: "rare",
    tags: ["loot"],
    cursed: true,
  },
  frostLock: {
    key: "frostLock",
    name: "氷結封鎖",
    desc: "部屋をロックすると、中の敵全員を3秒間凍えさせる。",
    icon: "#",
    rarity: "common",
    tags: ["chill", "room"],
    gives: ["chill"],
    cursed: false,
  },
  lopsided: {
    key: "lopsided",
    name: "偏重",
    desc: "最も高いステータスの伸びが1.25倍になる代わりに、最も低いステータスは0として扱う。",
    icon: "^",
    rarity: "rare",
    tags: ["attr"],
    cursed: true,
    requires: "attr",
  },
  swapHands: {
    key: "swapHands",
    name: "持ち替え",
    desc: "筋力と技巧を入れ替えて扱う。近接が技巧で、射撃が筋力で伸びる。",
    icon: "%",
    rarity: "common",
    tags: ["attr", "melee", "ranged"],
    cursed: false,
  },
  spiritBlade: {
    key: "spiritBlade",
    name: "霊刃",
    desc: "通常攻撃が霊力でも伸びる代わりに、通常攻撃で戻るマナが半分になる。",
    icon: "&",
    rarity: "rare",
    tags: ["attr", "melee", "ranged"],
    cursed: true,
  },
  plague: {
    key: "plague",
    name: "疫病",
    desc: "毒の敵が死ぬと、周囲の敵に毒を引き継ぐ。",
    icon: "Q",
    rarity: "common",
    tags: ["poison"],
    gives: ["poison"],
    cursed: false,
    requires: "poison",
  },
  bloodMist: {
    key: "bloodMist",
    name: "血煙",
    desc: "出血の敵を倒すと、自分の出血が消えてHP3回復する。",
    icon: "D",
    rarity: "common",
    tags: ["bleed", "hp"],
    cursed: false,
    requires: "bleed",
  },
  crumble: {
    key: "crumble",
    name: "崩し",
    desc: "怯ませた敵を脆弱にする。",
    icon: "Y",
    rarity: "common",
    tags: ["stagger", "melee"],
    gives: ["vulnerable"],
    cursed: false,
  },
  frostPierce: {
    key: "frostPierce",
    name: "凍て刺し",
    desc: "砕きで周囲の敵に冷気を2つ重ねる。",
    icon: "N",
    rarity: "rare",
    tags: ["chill"],
    gives: ["chill"],
    cursed: false,
    requires: "chill",
  },
  springWell: {
    key: "springWell",
    name: "湧水",
    desc: "部屋を制圧するとマナが満タンになる。",
    icon: "U",
    rarity: "rare",
    tags: ["mana", "room"],
    gives: ["mana"],
    cursed: false,
  },
  bloodMana: {
    key: "bloodMana",
    name: "血の対価",
    desc: "HPが50%以下の間、スキルのマナコストが-40%になる。",
    icon: "$",
    rarity: "common",
    tags: ["mana", "hp"],
    cursed: false,
  },
  reaperCup: {
    key: "reaperCup",
    name: "屠りの盃",
    desc: "撃破するたびマナが10回復する代わりに、マナの自然回復が半分になる。",
    icon: "=",
    rarity: "common",
    tags: ["mana"],
    cursed: false,
  },
  keenBreath: {
    key: "keenBreath",
    name: "見切りの息",
    desc: "ジャスト回避でマナが25回復する。",
    icon: "'",
    rarity: "common",
    tags: ["mana", "just"],
    gives: ["mana"],
    cursed: false,
  },
  circulation: {
    key: "circulation",
    name: "循環",
    desc: "スキルが命中するたびマナが2回復する。1回の発動で8まで。",
    icon: "o",
    rarity: "rare",
    tags: ["mana"],
    cursed: false,
  },
  hollowVessel: {
    key: "hollowVessel",
    name: "虚ろの器",
    desc: "スキルのマナコストが-35%になる代わりに、最大マナが-40%、通常攻撃で戻るマナが半分になる。",
    icon: "0",
    rarity: "rare",
    tags: ["mana"],
    cursed: true,
  },
  // ---------------------------------------------------------------------------
  // 系譜: 灰燼（燃焼）
  // ---------------------------------------------------------------------------
  emberSeed: {
    key: "emberSeed",
    name: "火種",
    desc: "近接の3段目は必ず燃焼を付ける。",
    icon: "火",
    rarity: "common",
    tags: ["burn", "melee"],
    gives: ["burn"],
    cursed: false,
    lineage: "ash",
  },
  wildfire: {
    key: "wildfire",
    name: "延焼",
    desc: "燃焼中の敵に攻撃を当てると、周囲の敵にも燃焼が移る。",
    icon: "延",
    rarity: "rare",
    tags: ["burn"],
    gives: ["burn"],
    cursed: false,
    lineage: "ash",
    after: "emberSeed",
  },
  ashBed: {
    key: "ashBed",
    name: "灰積もり",
    desc: "燃焼中の敵を倒すと灰が残る。灰を踏むと、次の近接1回が2倍の燃焼を付ける。",
    icon: "灰",
    rarity: "rare",
    tags: ["burn", "melee"],
    gives: ["burn"],
    cursed: false,
    lineage: "ash",
    after: "wildfire",
  },
  scorchedEarth: {
    key: "scorchedEarth",
    name: "焦土",
    desc: "バーストが周囲の燃焼を起爆し、残りの燃焼ダメージの1.5倍を即座に与える。",
    icon: "焦",
    rarity: "epic",
    tags: ["burn", "energy"],
    cursed: false,
    requires: "burn",
    lineage: "ash",
    after: "ashBed",
  },
  // ---------------------------------------------------------------------------
  // 系譜: 霜枷（冷気・凍結）
  // ---------------------------------------------------------------------------
  frostBreath: {
    key: "frostBreath",
    name: "霜息",
    desc: "射撃の命中で冷気を付ける。",
    icon: "霜",
    rarity: "common",
    tags: ["chill", "ranged"],
    gives: ["chill"],
    cursed: false,
    lineage: "frost",
  },
  frostFeet: {
    key: "frostFeet",
    name: "凍て足",
    desc: "冷気3以上の敵は予備動作が40%長くなる。",
    icon: "凍",
    rarity: "rare",
    tags: ["chill", "counter"],
    gives: ["counter"],
    cursed: false,
    lineage: "frost",
    after: "frostBreath",
  },
  shatterBell: {
    key: "shatterBell",
    name: "砕氷の鐘",
    desc: "砕きが起きると、近くの凍結中の敵も連鎖して砕ける。",
    icon: "鐘",
    rarity: "rare",
    tags: ["chill", "freeze"],
    cursed: false,
    lineage: "frost",
    after: "frostFeet",
  },
  eternalWinter: {
    key: "eternalWinter",
    name: "永冬",
    desc: "ジャスト回避で周囲の敵を凍結させる（ボスを除く）。",
    icon: "冬",
    rarity: "epic",
    tags: ["chill", "freeze", "just"],
    gives: ["freeze"],
    cursed: false,
    requires: "chill",
    lineage: "frost",
    after: "shatterBell",
  },
  // ---------------------------------------------------------------------------
  // 系譜: 雷鳴（感電・麻痺）
  // ---------------------------------------------------------------------------
  staticDash: {
    key: "staticDash",
    name: "静電気",
    desc: "ダッシュですり抜けた敵に感電を付ける。",
    icon: "静",
    rarity: "common",
    tags: ["shock", "dash"],
    gives: ["shock"],
    cursed: false,
    lineage: "thunder",
  },
  chargedBlade: {
    key: "chargedBlade",
    name: "帯電の刃",
    desc: "感電中の敵を近接で殴ると、その敵から連鎖する雷が走る。",
    icon: "刃",
    rarity: "rare",
    tags: ["shock", "melee"],
    gives: ["shock"],
    cursed: false,
    lineage: "thunder",
    after: "staticDash",
  },
  thunderMark: {
    key: "thunderMark",
    name: "落雷予告",
    desc: "麻痺した敵の足元に予告の円が出て、1秒後に雷が落ちる。",
    icon: "落",
    rarity: "rare",
    tags: ["shock", "paralyze"],
    cursed: false,
    lineage: "thunder",
    after: "chargedBlade",
  },
  thunderDrum: {
    key: "thunderDrum",
    name: "雷神の鼓",
    desc: "コンボ10ごとに、周囲の感電中の敵すべてから雷が連鎖する。",
    icon: "鼓",
    rarity: "epic",
    tags: ["shock", "combo"],
    cursed: false,
    requires: "shock",
    lineage: "thunder",
    after: "thunderMark",
  },
  // ---------------------------------------------------------------------------
  // 系譜: 月蝕（マナ・スキル・沈黙）
  // ---------------------------------------------------------------------------
  moonRead: {
    key: "moonRead",
    name: "月読",
    desc: "マナを使うスキルが命中した敵を短く沈黙させる。",
    icon: "月",
    rarity: "common",
    tags: ["mana", "skill", "silence"],
    gives: ["silence"],
    cursed: false,
    lineage: "moon",
  },
  highTide: {
    key: "highTide",
    name: "満ち潮",
    desc: "マナが満タンの間、通常攻撃の命中で必殺ゲージが余分に溜まる。",
    icon: "潮",
    rarity: "rare",
    tags: ["mana", "energy"],
    gives: ["energy"],
    cursed: false,
    lineage: "moon",
    after: "moonRead",
  },
  newMoon: {
    key: "newMoon",
    name: "新月",
    desc: "マナが0になってから2秒以内に撃ったスキル1回は、払ったマナが戻る。",
    icon: "朔",
    rarity: "rare",
    tags: ["mana", "skill"],
    cursed: false,
    lineage: "moon",
    after: "highTide",
  },
  eclipse: {
    key: "eclipse",
    name: "月蝕",
    desc: "装着中のスキルを重複なく続けて全て撃つと、2秒間スキルで払ったマナが戻る。",
    icon: "蝕",
    rarity: "epic",
    tags: ["mana", "skill"],
    cursed: false,
    requires: "mana",
    lineage: "moon",
    after: "newMoon",
  },
  // ---------------------------------------------------------------------------
  // 単体
  // ---------------------------------------------------------------------------
  bulletSteal: {
    key: "bulletSteal",
    name: "奪弾",
    desc: "ジャスト回避の瞬間、周囲の敵弾を自分の弾に変えて照準の方向へ撃ち出す。",
    icon: "奪",
    rarity: "rare",
    tags: ["ranged", "just"],
    cursed: false,
  },
  silenceShot: {
    key: "silenceShot",
    name: "口封じ",
    desc: "射撃・レーザー・爆弾の敵の予備動作中に弾を当てると沈黙させ、攻撃を取り消す。",
    icon: "封",
    rarity: "rare",
    tags: ["silence", "ranged", "counter"],
    gives: ["silence"],
    cursed: false,
  },
  glare: {
    key: "glare",
    name: "睨み",
    desc: "ジャスト回避した攻撃の主を4秒間弱体にする。",
    icon: "睨",
    rarity: "common",
    tags: ["weaken", "just"],
    gives: ["weaken"],
    cursed: false,
  },
  intimidate: {
    key: "intimidate",
    name: "威圧",
    desc: "近接の3段目で敵を倒すと、周囲の敵を恐怖させる。",
    icon: "威",
    rarity: "common",
    tags: ["fear", "melee"],
    gives: ["fear"],
    cursed: false,
  },
  reaperPlay: {
    key: "reaperPlay",
    name: "死神遊び",
    desc: "死神の攻撃にもジャスト回避が成立し、成立するたび死神が3秒止まる。",
    icon: "遊",
    rarity: "epic",
    tags: ["reaper", "just"],
    cursed: false,
  },
  wakeupHunt: {
    key: "wakeupHunt",
    name: "起き上がり狙い",
    desc: "敵の怯みが解けた直後0.4秒、その敵への近接はカウンターになる。",
    icon: "起",
    rarity: "rare",
    tags: ["stagger", "counter"],
    gives: ["counter"],
    cursed: false,
  },
  elementTrail: {
    key: "elementTrail",
    name: "属性の轍",
    desc: "ダッシュの軌跡に帯が残る。帯は装備で最も強い元素（燃焼・冷気・感電）を付ける。",
    icon: "轍",
    rarity: "rare",
    tags: ["dash", "burn", "chill", "shock"],
    cursed: false,
  },
  recall: {
    key: "recall",
    name: "呼び戻し",
    desc: "射撃ボタンを離すと、飛んでいる自分の弾が手元へ戻る。戻り道でも当たる。",
    icon: "戻",
    rarity: "rare",
    tags: ["ranged"],
    cursed: false,
  },
  huntBleed: {
    key: "huntBleed",
    name: "狩り立て",
    desc: "出血中の敵に近接を当てると短く恐怖させる。逃げるほど出血が進む。",
    icon: "狩",
    rarity: "common",
    tags: ["bleed", "fear", "melee"],
    gives: ["fear"],
    cursed: false,
  },
  frostRead: {
    key: "frostRead",
    name: "霜読み",
    desc: "冷気の敵の予備動作中に当てた弾もカウンターになる。",
    icon: "読",
    rarity: "rare",
    tags: ["chill", "counter", "ranged"],
    cursed: false,
  },
  venomBreak: {
    key: "venomBreak",
    name: "毒崩し",
    desc: "毒の敵には、怯みが解けた後の堅守が付かない。",
    icon: "腐",
    rarity: "common",
    tags: ["poison", "stagger", "guarded"],
    cursed: false,
  },
  insight: {
    key: "insight",
    name: "看破",
    desc: "カウンターを当てた敵を脆弱にする。",
    icon: "看",
    rarity: "common",
    tags: ["vulnerable", "counter"],
    gives: ["vulnerable"],
    cursed: false,
  },
  twinWheels: {
    key: "twinWheels",
    name: "両輪",
    desc: "マナのスキルが当たると他のスキルのクールダウンが1秒縮み、クールダウンのスキルが当たると次のマナのスキルのコストが半分になる。",
    icon: "輪",
    rarity: "rare",
    tags: ["mana", "skill"],
    cursed: false,
  },
  iceRelay: {
    key: "iceRelay",
    name: "氷伝い",
    desc: "連鎖する雷が冷気の敵に届くと、そこから連鎖がさらに2回延びる。",
    icon: "伝",
    rarity: "rare",
    tags: ["shock", "chill"],
    cursed: false,
  },
  trialSeeker: {
    key: "trialSeeker",
    name: "試練の徒",
    desc: "試練の部屋を制圧すると、祝福の3択がもう1回出る。",
    icon: "試",
    rarity: "rare",
    tags: ["room"],
    cursed: false,
  },
  oneWing: {
    key: "oneWing",
    name: "片翼",
    desc: "射撃できなくなる代わりに、近接の3段目で射撃の弾が扇状に出る。",
    icon: "翼",
    rarity: "rare",
    tags: ["melee", "ranged"],
    cursed: true,
  },
  justReturn: {
    key: "justReturn",
    name: "見切り返し",
    desc: "ジャスト回避でダッシュの回数が1戻る。",
    icon: "還",
    rarity: "common",
    tags: ["dash", "just"],
    cursed: false,
  },
  passCut: {
    key: "passCut",
    name: "抜き胴",
    desc: "ダッシュですり抜けた敵すべてを斬る。",
    icon: "胴",
    rarity: "rare",
    tags: ["dash", "melee"],
    cursed: false,
  },
  ricochet: {
    key: "ricochet",
    name: "跳ね弾",
    desc: "自分の弾が壁で1回跳ね返る。跳ねた弾は威力+30%。",
    icon: "跳",
    rarity: "common",
    tags: ["ranged"],
    cursed: false,
  },
  warhead: {
    key: "warhead",
    name: "炸裂弾頭",
    desc: "自分の弾が壁に当たると小さく爆発する。",
    icon: "炸",
    rarity: "common",
    tags: ["ranged", "explode"],
    gives: ["explode"],
    cursed: false,
  },
  weakSpot: {
    key: "weakSpot",
    name: "狙い目",
    desc: "脆弱の敵に当たった弾は貫通+2。",
    icon: "狙",
    rarity: "common",
    tags: ["vulnerable", "ranged"],
    cursed: false,
  },
  embers: {
    key: "embers",
    name: "燠火",
    desc: "燃焼中の敵を近接で殴ると、燃焼の残り時間が1秒延びる（元の持続まで）。",
    icon: "燠",
    rarity: "common",
    tags: ["burn", "melee"],
    cursed: false,
  },
  nerveCut: {
    key: "nerveCut",
    name: "神経断ち",
    desc: "麻痺が解けた敵を3秒間弱体にする。",
    icon: "断",
    rarity: "common",
    tags: ["paralyze", "weaken"],
    gives: ["weaken"],
    cursed: false,
  },
  bloodReturn: {
    key: "bloodReturn",
    name: "返り血",
    desc: "出血中の敵を倒すと、ダッシュの回数が全て戻る。",
    icon: "血",
    rarity: "common",
    tags: ["bleed", "dash"],
    cursed: false,
  },
  laceration: {
    key: "laceration",
    name: "血裂き",
    desc: "出血3の敵への会心は出血を全て消費し、その分を即座にダメージにする。",
    icon: "裂",
    rarity: "rare",
    tags: ["bleed", "crit"],
    cursed: false,
  },
  frayWiden: {
    key: "frayWiden",
    name: "綻び広げ",
    desc: "脆弱の敵が死ぬと、脆弱が最も近い敵へ残り時間ごと移る。",
    icon: "綻",
    rarity: "common",
    tags: ["vulnerable"],
    gives: ["vulnerable"],
    cursed: false,
  },
  backstab: {
    key: "backstab",
    name: "背討ち",
    desc: "恐怖で逃げる敵への攻撃は必ず会心になる。",
    icon: "背",
    rarity: "rare",
    tags: ["fear", "crit"],
    gives: ["crit"],
    cursed: false,
  },
  quietHall: {
    key: "quietHall",
    name: "静寂の間",
    desc: "沈黙中の敵が近くにいる間、スキルのマナコストが-30%になる。",
    icon: "寂",
    rarity: "common",
    tags: ["silence", "mana"],
    cursed: false,
  },
  keenEye: {
    key: "keenEye",
    name: "見逃さぬ",
    desc: "敵を怯ませるたびマナが8回復する。",
    icon: "逃",
    rarity: "common",
    tags: ["stagger", "mana"],
    gives: ["mana"],
    cursed: false,
  },
  collapseChain: {
    key: "collapseChain",
    name: "崩し連鎖",
    desc: "敵を怯ませると、同じ部屋で怯み値が溜まっている敵全員にさらに怯み値が溜まる。",
    icon: "鎖",
    rarity: "rare",
    tags: ["stagger"],
    gives: ["stagger"],
    cursed: false,
  },
  regroupHunt: {
    key: "regroupHunt",
    name: "立て直し狩り",
    desc: "堅守中の敵を倒すと必殺ゲージが30%溜まる。",
    icon: "堅",
    rarity: "common",
    tags: ["guarded", "energy"],
    gives: ["energy"],
    cursed: false,
  },
  edgeStrike: {
    key: "edgeStrike",
    name: "際打ち",
    desc: "コンボが切れる直前（残り0.3秒）に当てた攻撃は怯み値が2倍になる。",
    icon: "際",
    rarity: "rare",
    tags: ["combo", "stagger"],
    cursed: false,
  },
  cashOut: {
    key: "cashOut",
    name: "換金",
    desc: "バーストを撃つとコンボを0にして、コンボ数の2倍のマナを得る。",
    icon: "換",
    rarity: "common",
    tags: ["combo", "mana", "energy"],
    gives: ["mana"],
    cursed: false,
  },
  takeBack: {
    key: "takeBack",
    name: "取り返し",
    desc: "リゲイン中に敵を倒すと、取り戻せる分を全て回復する。",
    icon: "取",
    rarity: "common",
    tags: ["hp"],
    cursed: false,
  },
  woundMemory: {
    key: "woundMemory",
    name: "傷の記憶",
    desc: "被弾すると、その攻撃の主を4秒間脆弱にする。",
    icon: "傷",
    rarity: "common",
    tags: ["hp", "vulnerable"],
    gives: ["vulnerable"],
    cursed: false,
  },
  reaperShadow: {
    key: "reaperShadow",
    name: "死神の影",
    desc: "死神の警告中と出現中は、撃破するたびマナ+10・必殺ゲージ+10。",
    icon: "影",
    rarity: "common",
    tags: ["reaper", "mana", "energy"],
    cursed: false,
  },
  stallTime: {
    key: "stallTime",
    name: "時間稼ぎ",
    desc: "部屋を制圧するたび、死神の出現が10秒遅れる。",
    icon: "稼",
    rarity: "common",
    tags: ["reaper", "room"],
    cursed: false,
  },
  deathRush: {
    key: "deathRush",
    name: "死に急ぎ",
    desc: "最大HPが-50%になる代わりに、撃破するたび0.5秒無敵になる。",
    icon: "急",
    rarity: "rare",
    tags: ["hp"],
    cursed: true,
  },
  burden: {
    key: "burden",
    name: "重荷",
    desc: "移動速度が-25%になる代わりに、近接の怯み値が2倍になる。",
    icon: "重",
    rarity: "rare",
    tags: ["stagger", "melee"],
    cursed: true,
  },
  karmaFire: {
    key: "karmaFire",
    name: "業の火",
    desc: "燃焼の効果が2倍になる代わりに、近くに燃える敵がいると自分も燃える。",
    icon: "業",
    rarity: "rare",
    tags: ["burn"],
    cursed: true,
  },
  heavenEarth: {
    key: "heavenEarth",
    name: "乾坤",
    desc: "マナの自然回復と通常攻撃のマナ回収が0になる代わりに、ジャスト回避と撃破でマナが満タンになる。",
    icon: "乾",
    rarity: "rare",
    tags: ["mana", "just"],
    cursed: true,
  },
  afterglow: {
    key: "afterglow",
    name: "余韻",
    desc: "スキル発動後0.6秒、通常攻撃の命中で戻るマナが2倍になる。",
    icon: "韻",
    rarity: "common",
    tags: ["mana", "skill"],
    cursed: false,
  },
  ambushReturn: {
    key: "ambushReturn",
    name: "伏兵返し",
    desc: "伏兵の部屋を制圧すると刻印符が確定で落ちる。",
    icon: "伏",
    rarity: "common",
    tags: ["room", "loot"],
    cursed: false,
  },
  appraise: {
    key: "appraise",
    name: "見定め",
    desc: "近接の1・2段目を同じ敵に当てると、その敵への3段目は必ず会心になる。",
    icon: "定",
    rarity: "rare",
    tags: ["melee", "crit"],
    gives: ["crit"],
    cursed: false,
  },
  usurp: {
    key: "usurp",
    name: "力の簒奪",
    desc: "弱体の敵を倒すと、次の近接1回の怯み値が2倍になる。",
    icon: "簒",
    rarity: "common",
    tags: ["weaken", "stagger"],
    cursed: false,
  },
  tightrope: {
    key: "tightrope",
    name: "綱渡り",
    desc: "コンボが時間切れで途切れなくなる代わりに、被弾するとコンボ数の1/5の追加ダメージを受ける。",
    icon: "綱",
    rarity: "rare",
    tags: ["combo"],
    cursed: true,
  },
  swallowFlight: {
    key: "swallowFlight",
    name: "飛燕",
    desc: "誰にも当たらなかった斬撃は、短い斬撃波になって飛ぶ。",
    icon: "飛",
    rarity: "common",
    tags: ["melee", "ranged"],
    cursed: false,
  },
  chantReturn: {
    key: "chantReturn",
    name: "詠唱返し",
    desc: "自分が沈黙している間、通常攻撃で戻るマナが3倍になる。",
    icon: "詠",
    rarity: "common",
    tags: ["silence", "mana"],
    cursed: false,
  },
  fullMoonShot: {
    key: "fullMoonShot",
    name: "満月撃ち",
    desc: "マナが満タンで撃ったスキルは、命中した敵を脆弱にする。",
    icon: "満",
    rarity: "common",
    tags: ["mana", "skill", "vulnerable"],
    gives: ["vulnerable"],
    cursed: false,
  },
  carryOver: {
    key: "carryOver",
    name: "持ち越し",
    desc: "部屋を制圧した時のコンボを、次の封鎖まで時間切れなしで保つ。",
    icon: "越",
    rarity: "common",
    tags: ["combo", "room"],
    gives: ["combo"],
    cursed: false,
  },
  fireWalk: {
    key: "fireWalk",
    name: "火渡り",
    desc: "燃焼中の敵を通った弾は貫通+1され、次に当たる敵へ燃焼を移す。",
    icon: "渡",
    rarity: "rare",
    tags: ["burn", "ranged"],
    gives: ["burn"],
    cursed: false,
  },
  // ---------------------------------------------------------------------------
  // 結び（duo の 2 つを両方持っていると抽選に出る）
  // ---------------------------------------------------------------------------
  swallowReturn: {
    key: "swallowReturn",
    name: "燕渡り",
    desc: "ジャスト回避で消した敵弾の数だけ、近い敵を最大5体まで斬り渡る。",
    icon: "燕",
    rarity: "epic",
    tags: ["just", "melee"],
    cursed: false,
    duo: ["justSlash", "justWipe"],
  },
  plagueBlood: {
    key: "plagueBlood",
    name: "疫血",
    desc: "毒と出血が両方付いた敵が死ぬと、周囲の敵に毒と出血を両方引き継ぐ。",
    icon: "疫",
    rarity: "epic",
    tags: ["poison", "bleed"],
    gives: ["poison", "bleed"],
    cursed: false,
    duo: ["plague", "bloodMist"],
  },
  thunderBlast: {
    key: "thunderBlast",
    name: "雷爆走",
    desc: "ダッシュの終わりの爆発が、巻き込んだ敵に感電を2つ重ねる。",
    icon: "轟",
    rarity: "epic",
    tags: ["dash", "explode", "shock"],
    gives: ["shock"],
    cursed: false,
    duo: ["dashBlast", "dashShock"],
  },
  totalCollapse: {
    key: "totalCollapse",
    name: "総崩れ",
    desc: "崩しで脆弱になった敵の周囲の敵にも脆弱が伝わる。",
    icon: "総",
    rarity: "epic",
    tags: ["stagger", "vulnerable"],
    gives: ["vulnerable"],
    cursed: false,
    duo: ["crumble", "collapseChain"],
  },
  feastCup: {
    key: "feastCup",
    name: "饗宴の盃",
    desc: "撃破時、HPが満タンなら戻るマナが増え、マナが満タンなら回復が増える。",
    icon: "盃",
    rarity: "epic",
    tags: ["hp", "mana"],
    cursed: false,
    duo: ["bloodFeast", "reaperCup"],
  },
  criticalMass: {
    key: "criticalMass",
    name: "臨界",
    desc: "バーストの後3秒間は、必殺ゲージが空でも斬撃が爆発する。",
    icon: "臨",
    rarity: "epic",
    tags: ["energy", "explode"],
    cursed: false,
    duo: ["overcharge", "burstRefund"],
  },
  hollowBlade: {
    key: "hollowBlade",
    name: "虚刃",
    desc: "マナが0の間、通常攻撃に乗る霊力が2倍になる。",
    icon: "虚",
    rarity: "epic",
    tags: ["mana", "attr"],
    cursed: false,
    duo: ["spiritBlade", "hollowVessel"],
  },
  winterNest: {
    key: "winterNest",
    name: "冬籠り",
    desc: "封鎖中の部屋の敵は予備動作が20%長くなる。",
    icon: "籠",
    rarity: "epic",
    tags: ["chill", "room"],
    gives: ["counter"],
    cursed: false,
    duo: ["frostLock", "clearShield"],
  },
  clearMirror: {
    key: "clearMirror",
    name: "明鏡",
    desc: "ジャスト回避から1.5秒以内に撃ったスキル1回は、払ったマナが戻る。",
    icon: "鏡",
    rarity: "epic",
    tags: ["just", "mana"],
    cursed: false,
    duo: ["keenBreath", "justReturn"],
  },
  stillDash: {
    key: "stillDash",
    name: "瞬停",
    desc: "ダッシュの終わり際に撃った弾も静止狙撃の扱いになる。",
    icon: "停",
    rarity: "epic",
    tags: ["ranged", "dash"],
    cursed: false,
    duo: ["standingSniper", "dashGun"],
  },
  waveReturn: {
    key: "waveReturn",
    name: "波返し",
    desc: "衝撃波が壁で1回跳ね返る。",
    icon: "波",
    rarity: "epic",
    tags: ["melee", "combo"],
    cursed: false,
    duo: ["comboWave", "finisherWave"],
  },
};
