import { baseDef } from "./bases";
import type { Slot } from "./types";

/**
 * 名のある遺物（旧 unique）。性質は固定（値は小さく揺らぐ）、誓約も固定。
 * docs/LOOT_DESIGN.md「名のある遺物」
 */

export interface UniqueAffixSpec {
  key: string;
}

export interface UniqueDef {
  key: string;
  name: string;
  baseKey: string;
  minLevel: number;
  affixes: readonly UniqueAffixSpec[];
  /** 固定の誓約（KEYSTONES の key） */
  keystone?: string;
  /** フレーバー 1 行 */
  flavor?: string;
}

export const UNIQUES: readonly UniqueDef[] = [
  {
    key: "widowmaker",
    name: "喪服の剣",
    baseKey: "greatsword",
    minLevel: 14,
    keystone: "ks_berserker",
    flavor: "生命が減るほど、その一振りは大きくなる。",
    affixes: [
      { key: "meleeDamagePct" },
      { key: "critMultiplier" },
      { key: "lifeOnKill" },
      { key: "knockback" },
    ],
  },
  {
    key: "hailstormEngine",
    name: "雹嵐機関",
    baseKey: "smg",
    minLevel: 10,
    keystone: "ks_overclock",
    flavor: "引き金を引くたび、己の一部が飛び散る。",
    affixes: [
      { key: "projectiles" },
      { key: "fireRate" },
      { key: "chill" },
      { key: "pierce" },
      { key: "cv_splitToPierce" },
    ],
  },
  {
    key: "heartOfTheMountain",
    name: "山の心臓",
    baseKey: "plate",
    minLevel: 18,
    keystone: "ks_juggernaut",
    flavor: "これほど鈍重なものが、これほど重い一撃を放つはずがない。",
    affixes: [
      { key: "maxLife" },
      { key: "maxLifePct" },
      { key: "thorns" },
      { key: "damageTaken" },
      { key: "cv_lifeToArmor" },
    ],
  },
  {
    key: "stormstriders",
    name: "嵐脚",
    baseKey: "greaves",
    minLevel: 14,
    keystone: "ks_blink",
    flavor: "雷鳴より先に、お前はそこに立っている。",
    affixes: [
      { key: "moveSpeed" },
      { key: "dashCharge" },
      { key: "shock" },
      { key: "dashCooldown" },
    ],
  },
  {
    key: "eyeOfTheTempest",
    name: "颶風の瞳",
    baseKey: "lapisAmulet",
    minLevel: 12,
    keystone: "ks_gambler",
    flavor: "全ての必殺は賭け。部屋はその賭けに耐えられない。",
    affixes: [
      { key: "burstDamage" },
      { key: "burstRadius" },
      { key: "energyGain" },
      { key: "comboWindow" },
      { key: "explodeOnKill" },
    ],
  },

  // ---- 追加 10 種: 各スロット 2 つ以上、出始め ilvl は 4〜20 でばらす ----
  {
    key: "cinderfang",
    name: "燠牙",
    baseKey: "dagger",
    minLevel: 4,
    keystone: "ks_glassCannon",
    flavor: "二閃、そして炎が仕事を終わらせる。",
    affixes: [
      { key: "attackSpeed" },
      { key: "burn" },
      { key: "cv_meleeToBurn" },
    ],
  },
  {
    key: "bloodletterKiss",
    name: "瀉血の口づけ",
    baseKey: "shortsword",
    minLevel: 8,
    keystone: "ks_vampire",
    flavor: "お前を独りで失血死させはしない。",
    affixes: [
      { key: "lifeOnHit" },
      { key: "attackSpeed" },
      { key: "critMultiplier" },
    ],
  },
  {
    key: "whisperOfTheVoid",
    name: "虚無の囁き",
    baseKey: "rifle",
    minLevel: 9,
    keystone: "ks_pacifist",
    flavor: "それは一度だけ、遥か遠くから語る。",
    affixes: [
      { key: "rangedDamagePct" },
      { key: "pierce" },
      { key: "critChance" },
    ],
  },
  {
    key: "lastRites",
    name: "終油の秘跡",
    baseKey: "shotgun",
    minLevel: 15,
    keystone: "ks_overclock",
    flavor: "弾は一発ごとに、至近距離で施される。",
    affixes: [
      { key: "projectiles" },
      { key: "explodeOnKill" },
      { key: "fireRate" },
    ],
  },
  {
    key: "aegisOfTheUnbroken",
    name: "不屈のイージス",
    baseKey: "plate",
    minLevel: 20,
    keystone: "ks_juggernaut",
    flavor: "一度たりとも退くことを考えたことがない。",
    affixes: [
      { key: "armorFlat" },
      { key: "maxLifePct" },
      { key: "damageTaken" },
    ],
  },
  {
    key: "wardensSilence",
    name: "看守の沈黙",
    baseKey: "chain",
    minLevel: 11,
    keystone: "ks_bladeOath",
    flavor: "どんな問いにも、刃の腹で答える。",
    affixes: [
      { key: "maxLife" },
      { key: "meleeDamageFlat" },
      { key: "thorns" },
    ],
  },
  {
    key: "tempestLoader",
    name: "疾風の装填",
    baseKey: "greaves",
    minLevel: 13,
    keystone: "ks_windWalker",
    flavor: "地面が追いつく前に、全てのチャージを使い切れ。",
    affixes: [
      { key: "dashDistance" },
      { key: "moveSpeed" },
      { key: "cv_speedToAttack" },
    ],
  },
  {
    key: "berserkersSignet",
    name: "狂戦士の印章",
    baseKey: "bloodRing",
    minLevel: 10,
    keystone: "ks_berserker",
    flavor: "お前の代わりに、傷の数を数えてくれる。",
    affixes: [
      { key: "lifeOnKill" },
      { key: "critMultiplier" },
      { key: "maxLife" },
    ],
  },
  {
    key: "fortunesGambit",
    name: "運命の賭け",
    baseKey: "goldRing",
    minLevel: 7,
    keystone: "ks_gambler",
    flavor: "胴元は、いつか必ず負ける。",
    affixes: [
      { key: "critChance" },
      { key: "burstDamage" },
      { key: "energyGain" },
    ],
  },
  {
    key: "phaseAnchor",
    name: "位相の錨",
    baseKey: "onyxAmulet",
    minLevel: 14,
    keystone: "ks_blink",
    flavor: "お前がいるはずだった場所を、それは覚えている。",
    affixes: [
      { key: "burstRadius" },
      { key: "dashCooldown" },
      { key: "moveSpeed" },
    ],
  },
  {
    // 器は小さいが、倒すたびに汲み上げる。マナ経済（docs/COMBAT_DESIGN.md B 節）の尖った解
    key: "driedWell",
    name: "涸れ井戸の指輪",
    baseKey: "sapphireRing",
    minLevel: 10,
    flavor: "底は乾いている。満たすのは、いつも他人の最期だ。",
    affixes: [
      { key: "manaDrought" },
      { key: "manaCostPct" },
    ],
  },
  // ---- 2026-09 追加（docs/ideas/loot-expansion.md 4 章）。新しい性質・誓約を固定セットで見せる ----
  {
    key: "guardStripper",
    name: "堅守剥がし",
    baseKey: "revolver",
    minLevel: 9,
    flavor: "盾の裏を撃つ弾もある。",
    affixes: [{ key: "guardPiercer" }, { key: "manaOnStagger" }, { key: "rangedDamagePct" }],
  },
  {
    key: "silentScripture",
    name: "沈黙の聖句",
    baseKey: "smg",
    minLevel: 8,
    flavor: "黙らせた数だけ、祈りは届く。",
    affixes: [{ key: "procSilence" }, { key: "silencedKillMana" }, { key: "vortexCore" }],
  },
  {
    key: "paradoxRing",
    name: "矛盾の指輪",
    baseKey: "goldRing",
    minLevel: 8,
    flavor: "育てるか、育てぬか。どちらでも応える。",
    affixes: [{ key: "sapling" }, { key: "inscribedWeight" }],
  },
  {
    key: "bottomless",
    name: "底なし",
    baseKey: "jadeAmulet",
    minLevel: 7,
    flavor: "空と満ちの間に、底はない。",
    affixes: [{ key: "lowTide" }, { key: "manaOverflow" }],
  },
  {
    key: "manyHuedBrush",
    name: "多彩の筆",
    baseKey: "staff",
    minLevel: 10,
    flavor: "一色では、絵にならない。",
    affixes: [{ key: "kaleidoscope" }, { key: "procWeaken" }, { key: "procPoison" }],
  },
  {
    key: "wedgeDriver",
    name: "楔打ち",
    baseKey: "warpick",
    minLevel: 15,
    keystone: "ks_wedgeOath",
    flavor: "割れ目があれば、そこが入口だ。",
    affixes: [{ key: "wedge" }, { key: "staggerQuake" }, { key: "damageVsStaggered" }],
  },
  {
    key: "firstStrikeBlade",
    name: "先の先",
    baseKey: "shortsword",
    minLevel: 9,
    keystone: "ks_readOath",
    flavor: "構えた瞬間に、もう終わっている。",
    affixes: [{ key: "readAhead" }, { key: "counterMana" }, { key: "windupCrack" }],
  },
  {
    key: "lightningRod",
    name: "避雷針",
    baseKey: "railgun",
    minLevel: 17,
    flavor: "雷は、通り道を覚えている。",
    affixes: [{ key: "brimShock" }, { key: "shock" }, { key: "chainedBarrage" }],
  },
  {
    key: "scarredHide",
    name: "古傷の胴",
    baseKey: "leather",
    minLevel: 6,
    flavor: "傷の数だけ、厚くなる。",
    affixes: [{ key: "oldScars" }, { key: "hybridDefense" }, { key: "staggerLeech" }],
  },
  {
    key: "proxyRobe",
    name: "身代わり衣",
    baseKey: "robe",
    minLevel: 8,
    flavor: "払えるうちは、痛くない。",
    affixes: [{ key: "manaShield" }, { key: "maxManaFlat" }, { key: "manaRegenFlat" }],
  },
  {
    key: "sickbedCurtain",
    name: "病床の帳",
    baseKey: "chain",
    minLevel: 11,
    keystone: "ks_blight",
    flavor: "熱のあるうちが、一番強い。",
    affixes: [{ key: "fever" }, { key: "procPoison" }],
  },
  {
    key: "whiteCloth",
    name: "白布",
    baseKey: "cloth",
    minLevel: 6,
    keystone: "ks_pure",
    flavor: "何も染みず、何も染めない。",
    affixes: [{ key: "hpRegen" }, { key: "maxLife" }, { key: "statusWard" }],
  },
  {
    key: "backwaterPlate",
    name: "背水の甲",
    baseKey: "plate",
    minLevel: 16,
    keystone: "ks_backwater",
    flavor: "退路は、扉と一緒に閉じた。",
    affixes: [{ key: "lockdownFury" }, { key: "damageTaken" }, { key: "armorFlat" }],
  },
  {
    key: "painlessChain",
    name: "無痛の鎖",
    baseKey: "scale",
    minLevel: 12,
    flavor: "痛みを売って、力を買った。",
    affixes: [{ key: "painToMana" }, { key: "hurtWeaken" }, { key: "maxLife" }],
  },
  {
    key: "wayfarerSandals",
    name: "旅の垢",
    baseKey: "sandals",
    minLevel: 5,
    keystone: "ks_discipline",
    flavor: "歩いた道の分だけ、軽くなる。",
    affixes: [{ key: "wayfarer" }, { key: "moveSpeed" }],
  },
  {
    key: "idatenTabi",
    name: "韋駄天の足袋",
    baseKey: "tabi",
    minLevel: 9,
    flavor: "止まる理由を、一つずつ捨てた。",
    affixes: [{ key: "dashVolley" }, { key: "moveSpeed" }, { key: "dashCooldown" }],
  },
  {
    key: "keenSandals",
    name: "見切りの草履",
    baseKey: "sandals",
    minLevel: 10,
    flavor: "見た数だけ、遅く見える。",
    affixes: [{ key: "keenMemory" }, { key: "justDodgeDamage" }, { key: "justBreath" }],
  },
  {
    key: "reaperBoots",
    name: "死神の靴",
    baseKey: "wingedBoots",
    minLevel: 16,
    keystone: "ks_reaperOath",
    flavor: "あれは、足音を真似ている。",
    affixes: [{ key: "reaperShadow" }, { key: "moveSpeed" }],
  },
  {
    key: "reverseRing",
    name: "裏返しの輪",
    baseKey: "voidBand",
    minLevel: 14,
    flavor: "裏も表も、同じ重さ。",
    affixes: [{ key: "invertedFeast" }, { key: "foreignEcho" }],
  },
  {
    key: "monochromeNecklace",
    name: "一色の首飾り",
    baseKey: "lapisAmulet",
    minLevel: 12,
    keystone: "ks_monochrome",
    flavor: "一つの色で、部屋を塗れ。",
    affixes: [{ key: "burstRadius" }, { key: "burstDamage" }],
  },
  {
    key: "facingMirrors",
    name: "合わせ鏡",
    baseKey: "onyxAmulet",
    minLevel: 11,
    keystone: "ks_mirror",
    flavor: "映ったほうが、本物かもしれない。",
    affixes: [{ key: "bridge" }, { key: "critMultiplier" }],
  },
  {
    key: "kingslayerCollar",
    name: "王殺しの首輪",
    baseKey: "duskAmulet",
    minLevel: 13,
    flavor: "冠の数だけ、鎖が重い。",
    affixes: [{ key: "kingslayerMark" }, { key: "downHunter" }],
  },
  {
    key: "nightOwl",
    name: "夜更かしの眼",
    baseKey: "rifle",
    minLevel: 10,
    flavor: "灯りを消せば、よく見える。",
    affixes: [{ key: "nightEyes" }, { key: "critChance" }, { key: "pierce" }],
  },
  {
    key: "lastBell",
    name: "殲滅の鐘",
    baseKey: "greatsword",
    minLevel: 12,
    flavor: "最後の一打が、次の最初の一打になる。",
    affixes: [{ key: "lastKillMana" }, { key: "lockdownFury" }, { key: "meleeDamagePct" }],
  },
  {
    key: "colorlessBell",
    name: "無色の鈴",
    baseKey: "bell",
    minLevel: 9,
    keystone: "ks_colorless",
    flavor: "鳴らない鈴は、全ての音を持っている。",
    affixes: [{ key: "virulent" }, { key: "critChance" }],
  },
  {
    key: "contagionFang",
    name: "病みの牙",
    baseKey: "fangNecklace",
    minLevel: 10,
    keystone: "ks_contagion",
    flavor: "死者の病は、生者が継ぐ。",
    affixes: [{ key: "plagueSeed" }, { key: "procBleed" }, { key: "kaleidoscope" }],
  },
  {
    key: "chantRosary",
    name: "詠唱の数珠",
    baseKey: "rosary",
    minLevel: 8,
    keystone: "ks_chant",
    flavor: "空になるまで、祈れ。",
    affixes: [{ key: "arcaneFocus" }, { key: "manaGainPct" }, { key: "fullTide" }],
  },
  {
    key: "unshakenScale",
    name: "揺るがぬ鱗",
    baseKey: "scale",
    minLevel: 14,
    keystone: "ks_unshaken",
    flavor: "倒れないものは、倒さない。",
    affixes: [{ key: "heavyHand" }, { key: "armorFlat" }],
  },
  {
    key: "chokeTwins",
    name: "締め上げの双剣",
    baseKey: "twinblades",
    minLevel: 12,
    keystone: "ks_chokehold",
    flavor: "息を継ぐ隙は、与えない。",
    affixes: [{ key: "guardedBane" }, { key: "fearPoise" }, { key: "attackSpeed" }],
  },
  {
    key: "oblivionRags",
    name: "忘却の襤褸",
    baseKey: "rags",
    minLevel: 7,
    keystone: "ks_oblivion",
    flavor: "何も覚えていない。だから、まだ何にでもなれる。",
    affixes: [{ key: "sapling" }, { key: "maxLife" }],
  },
  {
    key: "brokenCadence",
    name: "途切れの音",
    baseKey: "longsword",
    minLevel: 8,
    flavor: "途切れたときに、初めて音がする。",
    affixes: [{ key: "echoSlash" }, { key: "comboDamage" }],
  },
  {
    key: "keepsakeRing",
    name: "形見分け",
    baseKey: "rubyRing",
    minLevel: 9,
    flavor: "死者の病は、生者が継ぐ。",
    affixes: [{ key: "inheritance" }, { key: "kaleidoscope" }],
  },
  {
    key: "returningSwallow",
    name: "帰り燕",
    baseKey: "pistol",
    minLevel: 7,
    flavor: "行って、刺さって、帰ってくる。",
    affixes: [{ key: "stake" }, { key: "rangedDamageFlat" }],
  },
  {
    key: "leftBehind",
    name: "置き土産の輪",
    baseKey: "ironRing",
    minLevel: 8,
    flavor: "去った後に、罠だけが喋る。",
    affixes: [{ key: "placedInfuse" }, { key: "placedAnchor" }, { key: "bloodSignature" }],
  },
  // ---- 2026-09 第 2 弾: 属性・武器種・射撃の型・ジョブ・地形ごとに 1〜2 個 ----
  // 属性
  {
    key: "emberHeart",
    name: "熾火の心臓",
    baseKey: "handCannon",
    minLevel: 13,
    keystone: "ks_emberOath",
    flavor: "燃え残りは、次の火種になる。",
    affixes: [{ key: "emberTrail" }, { key: "igniter" }, { key: "cv_burnToFire" }],
  },
  {
    key: "glacierStep",
    name: "氷河の足",
    baseKey: "snowBoots",
    minLevel: 9,
    keystone: "ks_slickOath",
    flavor: "滑る者だけが、氷の上で踊れる。",
    affixes: [{ key: "frostTrail" }, { key: "slickFooting" }, { key: "res_ice" }],
  },
  {
    key: "thunderLash",
    name: "雷導の鞭",
    baseKey: "chainWhip",
    minLevel: 10,
    flavor: "水を打て。雷は後から来る。",
    affixes: [{ key: "conductor" }, { key: "cv_shockToLightning" }, { key: "shock" }],
  },
  {
    key: "bogMother",
    name: "沼母の珠",
    baseKey: "seekerOrb",
    minLevel: 8,
    flavor: "逃げても、沼は追ってくる。",
    affixes: [{ key: "homingVenom" }, { key: "cv_infusePoison" }, { key: "terrainHunter" }],
  },
  {
    key: "duskSickle",
    name: "宵の小鎌",
    baseKey: "sickle",
    minLevel: 7,
    flavor: "告げられた者は、もう刈られている。",
    affixes: [{ key: "doomToll" }, { key: "corrodeClaw" }, { key: "lifeOnKill" }],
  },
  {
    key: "dawnCrystal",
    name: "暁の水晶杖",
    baseKey: "crystalWand",
    minLevel: 11,
    keystone: "ks_weakOath",
    flavor: "光は、弱いところから差し込む。",
    affixes: [{ key: "cv_critToLight" }, { key: "weakRead" }, { key: "prismEdge" }],
  },
  {
    key: "oneHueBand",
    name: "一色の輪",
    baseKey: "goldRing",
    minLevel: 10,
    keystone: "ks_oneElement",
    flavor: "一つの色に染まれば、どんな壁も透ける。",
    affixes: [{ key: "resistBreaker" }, { key: "conductor" }],
  },
  {
    key: "plainVeil",
    name: "無地の帳",
    baseKey: "robe",
    minLevel: 9,
    keystone: "ks_nullOath",
    flavor: "色を捨てれば、色に傷つかない。",
    affixes: [{ key: "elementalWard" }, { key: "wardingFlat" }, { key: "cv_resistToWarding" }],
  },
  {
    key: "backlashCharm",
    name: "逆撫での首飾り",
    baseKey: "onyxAmulet",
    minLevel: 8,
    flavor: "嫌がるところを、何度でも撫でる。",
    affixes: [{ key: "backlash" }, { key: "elementalBreak" }],
  },
  // 武器種
  {
    key: "moonCleaver",
    name: "月断ち",
    baseKey: "zanbato",
    minLevel: 12,
    keystone: "ks_chargeOath",
    flavor: "満ちるまで待て。欠けた刃は届かない。",
    affixes: [{ key: "chargeCore" }, { key: "chargeQuake" }],
  },
  {
    key: "mastersKatana",
    name: "師範の打刀",
    baseKey: "katana",
    minLevel: 9,
    keystone: "ks_ironOath",
    flavor: "型は、師より長く生きる。",
    affixes: [{ key: "schoolForm" }, { key: "branchArt" }],
  },
  {
    key: "strayFists",
    name: "野良の鉄拳",
    baseKey: "cestus",
    minLevel: 8,
    flavor: "誰にも習わなかった。だから誰にも読まれない。",
    affixes: [{ key: "selfTaught" }, { key: "wanderer" }, { key: "attackSpeed" }],
  },
  {
    key: "matedFangs",
    name: "番いの短刀",
    baseKey: "twinDaggers",
    minLevel: 6,
    flavor: "片方が噛めば、もう片方が離さない。",
    affixes: [{ key: "switchHitter" }, { key: "switchBreath" }, { key: "critChance" }],
  },
  {
    key: "gateHalberd",
    name: "城門の矛槍",
    baseKey: "halberd",
    minLevel: 11,
    keystone: "ks_stanceOath",
    flavor: "門は、開くより閉じる方が強い。",
    affixes: [{ key: "siegeGuard" }, { key: "guardedBane" }],
  },
  {
    key: "abbotsStaff",
    name: "住職の錫杖",
    baseKey: "shakujo",
    minLevel: 9,
    flavor: "鳴らすたびに、場が静まる。",
    affixes: [{ key: "siegeSpark" }, { key: "schoolHarvest" }, { key: "maxManaFlat" }],
  },
  {
    key: "rustbreaker",
    name: "錆割りの双剣",
    baseKey: "twinblades",
    minLevel: 10,
    flavor: "錆びた鎧ほど、よく割れる。",
    affixes: [{ key: "brokenHunter" }, { key: "corrodeClaw" }],
  },
  // 射撃の型
  {
    key: "thunderTrumpet",
    name: "雷鳴の喇叭銃",
    baseKey: "blunderbuss",
    minLevel: 8,
    flavor: "耳元で鳴らせば、誰でも退く。",
    affixes: [{ key: "spreadCore" }, { key: "spreadShove" }],
  },
  {
    key: "brandingKnives",
    name: "烙印の投げ短剣",
    baseKey: "throwingKnives",
    minLevel: 6,
    flavor: "一本目は印。二本目が本命。",
    affixes: [{ key: "rapidBrand" }, { key: "brandDetonator" }],
  },
  {
    key: "demonCaltrops",
    name: "鬼の撒き菱",
    baseKey: "caltrops",
    minLevel: 9,
    flavor: "足元を見ない者から、倒れていく。",
    affixes: [{ key: "terrainBurst" }, { key: "terrainHunter" }],
  },
  {
    key: "circlingMoon",
    name: "巡り月",
    baseKey: "chakram",
    minLevel: 9,
    flavor: "回るものは、必ず帰ってくる。",
    affixes: [{ key: "switchBreath" }, { key: "pierce" }, { key: "projectileSpeed" }],
  },
  // 地形・ジョブ・交戦
  {
    key: "earthMino",
    name: "土の蓑",
    baseKey: "mino",
    minLevel: 6,
    keystone: "ks_earthOath",
    flavor: "泥に座れば、泥が傷を塞ぐ。",
    affixes: [{ key: "groundMend" }, { key: "mireGuard" }],
  },
  {
    key: "rootedGeta",
    name: "根張りの下駄",
    baseKey: "ironGeta",
    minLevel: 8,
    flavor: "動かぬ足は、地の声を聞く。",
    affixes: [{ key: "groundRooted" }, { key: "mireGuard" }],
  },
  {
    key: "driftersCharm",
    name: "流れ者の護符",
    baseKey: "jadeAmulet",
    minLevel: 5,
    flavor: "名も型も持たない。持たないから、どこへでも行ける。",
    affixes: [{ key: "wanderer" }, { key: "siegeSpark" }],
  },
  {
    key: "lampOil",
    name: "灯油の首飾り",
    baseKey: "amberAmulet",
    minLevel: 7,
    flavor: "油を撒いたのは、誰だったか。",
    affixes: [{ key: "igniter" }, { key: "emberTrail" }],
  },
];

/** slot に対応し depth で解禁済みの名のある遺物 */
export function uniquesFor(slot: Slot, depth: number): UniqueDef[] {
  return UNIQUES.filter((u) => u.minLevel <= depth && baseDef(u.baseKey)?.slot === slot);
}

export function uniqueDef(key: string): UniqueDef | undefined {
  return UNIQUES.find((u) => u.key === key);
}
