import { kw } from "../core/keywords";
import { STATUS } from "../data/tuning";
import type { StatusApply } from "../core/status";
import { EXTRA_SKILL_TUNING as T } from "./tuning";
import type { ExtraSkillKey, SkillDef } from "./types";
import { cooldownSkill, manaSkill } from "./resource";

/**
 * 大拡張のスキル石の定義（docs/ideas/skills-expansion.md 1 章）。data.ts の SKILL_DEFS に展開する。
 * 発動処理は skills/actions.ts（近接・範囲・移動）/ shots.ts（射撃弾）/ summons.ts（設置物・連動体）。
 * 新しい状態異常・地形を前提にするもの（泥沼・落石・雷針など）は別レーンの担当なので入れていない。
 */

/** 命中した敵に付ける状態異常 */
const APPLIES = {
  fullMoon: [{ kind: "vulnerable", stacks: 1, duration: T.fullMoon.vulnerableTime, potency: 0 }],
  powderKeg: [{ kind: "burn", stacks: 1, duration: T.powderKeg.burnTime, potency: T.powderKeg.burnPotency }],
  iceBreaker: [{ kind: "chill", stacks: T.iceBreaker.chillStacks, duration: STATUS.chill.duration, potency: 0 }],
  verdict: [{ kind: "silence", stacks: 1, duration: T.verdict.silenceTime, potency: 0 }],
  threadReel: [{ kind: "weaken", stacks: 1, duration: T.threadReel.weakenTime, potency: 0 }],
} as const satisfies Partial<Record<ExtraSkillKey, readonly StatusApply[]>>;

export const EXTRA_SKILL_DEFS: Record<ExtraSkillKey, SkillDef> = {
  contagion: {
    key: "contagion",
    name: "伝染",
    icon: "伝",
    verb: "カーソル近くの敵の状態異常を、周りの敵へ持続半分で写す（元の敵からは消えない）",
    tags: ["area"],
    keywords: kw(["area", "reaction"], ["burn", "poison", "bleed"]),
    damageKind: "none",
    axes: ["areaVsDamage", "durationVsPotency"],
    ...manaSkill(T.contagion),
  },
  unravel: {
    key: "unravel",
    name: "綻び",
    icon: "綻",
    verb: "命中した敵の状態異常をすべて消し、種類が多いほど強く打つ",
    tags: ["projectile"],
    keywords: kw(["ranged"], ["burn", "chill", "shock", "poison", "bleed"]),
    damageKind: "ranged",
    axes: ["cooldownVsDamage", "speedVsDamage"],
    ...manaSkill(T.unravel),
    combos: ["contagionUnravel"],
  },
  kindle: {
    key: "kindle",
    name: "燃え種爆ぜ",
    icon: "爆",
    verb: "カーソル周りの燃焼をすべて爆発に変える（残りの燃焼が多いほど強い）",
    tags: ["fire", "area"],
    keywords: kw(["explode"], ["burn"]),
    damageKind: "ranged",
    axes: ["areaVsDamage", "cooldownVsDamage"],
    ...manaSkill(T.kindle),
  },
  prismShard: {
    key: "prismShard",
    name: "五彩の礫",
    icon: "彩",
    verb: "礫を 3 つ撃つ。装備の共鳴の色で効果が変わる（紅 出血 / 蒼 感電 / 翠 回復 / 金 貫通 / 冥 脆弱）",
    tags: ["projectile"],
    keywords: kw(["bullet", "bleed", "shock", "heal", "vulnerable"], ["crimson", "azure", "jade", "gold", "umbra"]),
    damageKind: "ranged",
    axes: ["countVsDamage", "cooldownVsDamage", "speedVsDamage"],
    ...manaSkill(T.prismShard),
  },
  fullMoon: {
    key: "fullMoon",
    name: "満月の砲",
    icon: "月",
    verb: "気力が満タンのときだけ撃てる。気力を全部払い、壁まで貫く太い光線を放つ",
    tags: ["projectile"],
    keywords: kw(["ranged"]),
    damageKind: "ranged",
    axes: ["areaVsDamage", "speedVsDamage"],
    ...manaSkill(T.fullMoon),
    applies: APPLIES.fullMoon,
    manaRule: "full",
  },
  dregsBlade: {
    key: "dregsBlade",
    name: "枯渇の刃",
    icon: "枯",
    verb: "気力が残り少ないときだけ撃てる、コスト 0 の 3 連斬",
    tags: ["melee", "area"],
    keywords: kw(["melee", "area"]),
    damageKind: "melee",
    axes: ["areaVsDamage", "countVsDamage"],
    ...manaSkill(T.dregsBlade),
    manaRule: "low",
  },
  shadowStep: {
    key: "shadowStep",
    name: "影渡り",
    icon: "影",
    verb: "カーソル近くの敵の背後へ瞬間移動する。直後の近接 1 回は背面から当たる（対象がいなければ消費なし）",
    tags: ["movement"],
    keywords: kw(["dash"], [], ["melee"]),
    damageKind: "none",
    axes: ["cooldownVsPotency", "durationVsPotency"],
    ...manaSkill(T.shadowStep),
  },
  powderKeg: {
    key: "powderKeg",
    name: "爆薬樽",
    icon: "樽",
    verb: "樽を置く。近接で叩くと転がって当たった所で爆発し、撃つとその場で爆発する（敵弾でも爆発）",
    tags: ["placed", "area", "fire"],
    keywords: kw(["placed", "explode"], ["melee", "bullet"]),
    damageKind: "ranged",
    axes: ["areaVsDamage", "countVsDamage", "cooldownVsDamage"],
    ...manaSkill(T.powderKeg),
    applies: APPLIES.powderKeg,
  },
  swordGrave: {
    key: "swordGrave",
    name: "剣の墓標",
    icon: "墓",
    verb: "剣を地面に刺す。自分の近接 3 段目が当たるたび、刺した剣がすべてその場で回転斬りする",
    tags: ["placed", "summon", "area"],
    keywords: kw(["placed", "area"], ["finisher"]),
    damageKind: "melee",
    axes: ["countVsDamage", "areaVsDamage", "durationVsPotency"],
    ...manaSkill(T.swordGrave),
  },
  iceBreaker: {
    key: "iceBreaker",
    name: "砕氷槌",
    icon: "砕",
    verb: "前方を叩いて冷気を与える。凍った敵を砕くと破片が周りへ飛ぶ",
    tags: ["melee", "cold", "area"],
    keywords: kw(["reaction"], ["chill"]),
    damageKind: "melee",
    axes: ["areaVsDamage", "cooldownVsDamage"],
    ...manaSkill(T.iceBreaker),
    applies: APPLIES.iceBreaker,
    combos: ["frostBreaker"],
  },
  bloodlet: {
    key: "bloodlet",
    name: "血抜き",
    icon: "抜",
    verb: "周りの敵の出血をすべて抜き取り、その量で生命を回復する（1 回の回復には上限がある）",
    tags: ["area"],
    keywords: kw(["heal"], ["bleed"]),
    damageKind: "melee",
    axes: ["areaVsDamage", "cooldownVsPotency"],
    ...manaSkill(T.bloodlet),
  },
  harvest: {
    key: "harvest",
    name: "毒の収穫",
    icon: "収",
    verb: "命中した敵の毒を消し、残りの毒のダメージを一度に与える",
    tags: ["projectile"],
    keywords: kw(["ranged"], ["poison"]),
    damageKind: "ranged",
    axes: ["cooldownVsDamage", "speedVsDamage"],
    ...manaSkill(T.harvest),
  },
  discharge: {
    key: "discharge",
    name: "放電",
    icon: "放",
    verb: "近くの感電した敵すべてから自分へ雷を引き寄せる。雷の通り道の敵にも当たる（感電は消える）",
    tags: ["lightning", "area"],
    keywords: kw(["area"], ["shock"]),
    damageKind: "ranged",
    axes: ["areaVsDamage", "cooldownVsDamage"],
    ...manaSkill(T.discharge),
  },
  rout: {
    key: "rout",
    name: "追い討ち",
    icon: "討",
    verb: "短刀を 3 本投げる。恐怖した敵に当たると恐怖を消して大きく怯ませる",
    tags: ["projectile"],
    keywords: kw(["stagger", "bullet"], ["fear"]),
    damageKind: "ranged",
    axes: ["countVsDamage", "cooldownVsDamage"],
    ...manaSkill(T.rout),
  },
  verdict: {
    key: "verdict",
    name: "処断",
    icon: "処",
    verb: "沈黙した敵を斬ると沈黙を消して大ダメージ。沈黙していなければ沈黙を付けるだけ",
    tags: ["melee"],
    keywords: kw(["melee"], ["silence"]),
    damageKind: "melee",
    axes: ["areaVsDamage", "cooldownVsDamage"],
    ...manaSkill(T.verdict),
    applies: APPLIES.verdict,
  },
  exploit: {
    key: "exploit",
    name: "刺し穿ち",
    icon: "刺",
    verb: "短く突く。脆弱な敵には脆弱を消して必ず会心、怯みも大きい",
    tags: ["melee"],
    keywords: kw(["crit", "stagger"], ["vulnerable"]),
    damageKind: "melee",
    axes: ["cooldownVsDamage", "areaVsDamage"],
    ...manaSkill(T.exploit),
    combos: ["shadowExploit"],
  },
  strip: {
    key: "strip",
    name: "剥奪",
    icon: "剥",
    verb: "命中した敵の弱体を奪い、その秒数だけ自分の与ダメージが上がる",
    tags: ["projectile"],
    keywords: kw(["ranged"], ["weaken"]),
    damageKind: "ranged",
    axes: ["cooldownVsDamage", "speedVsDamage"],
    ...manaSkill(T.strip),
  },
  lastStand: {
    key: "lastStand",
    name: "背水の一閃",
    icon: "背",
    verb: "前方へ突く。失った生命が多いほど強い（生命が多いとコストが重い）",
    tags: ["melee"],
    keywords: kw(["melee"], ["lowHp"]),
    damageKind: "melee",
    axes: ["cooldownVsDamage", "areaVsDamage"],
    ...manaSkill(T.lastStand),
  },
  comboChain: {
    key: "comboChain",
    name: "連環撃",
    icon: "環",
    verb: "コンボ 10 ごとに段数が増える連続突き。1 段でも外すとコンボが途切れる",
    tags: ["melee"],
    keywords: kw(["melee", "combo"], ["combo"]),
    damageKind: "melee",
    axes: ["cooldownVsDamage", "speedVsDamage"],
    ...manaSkill(T.comboChain),
  },
  grudge: {
    key: "grudge",
    name: "恨み返し",
    icon: "恨",
    verb: "直前に受けたダメージの 2 倍を前方へ返す（受けていなければ弱い）",
    tags: ["melee", "area"],
    keywords: kw(["area"], ["hurt"]),
    damageKind: "melee",
    axes: ["areaVsDamage", "cooldownVsDamage"],
    ...manaSkill(T.grudge),
  },
  guillotine: {
    key: "guillotine",
    name: "断頭振り",
    icon: "断",
    verb: "少し溜めて縦に振り下ろす。刃先で当てると威力が倍になる",
    tags: ["melee"],
    keywords: kw(["melee", "stagger"], ["still"]),
    damageKind: "melee",
    axes: ["speedVsDamage", "cooldownVsDamage"],
    ...manaSkill(T.guillotine),
  },
  ricochet: {
    key: "ricochet",
    name: "跳弾",
    icon: "跳",
    verb: "壁で跳ねる弾を撃つ。跳ねるたびに威力が上がる",
    tags: ["projectile"],
    keywords: kw(["bullet"], ["wall"]),
    damageKind: "ranged",
    axes: ["countVsDamage", "cooldownVsDamage", "speedVsDamage"],
    ...manaSkill(T.ricochet),
  },
  galeSlash: {
    key: "galeSlash",
    name: "風切り",
    icon: "風",
    verb: "前方へ飛ぶ斬撃を放つ。敵弾を消し、消すたびに遠くまで飛ぶ",
    tags: ["projectile", "melee"],
    keywords: kw(["bullet", "melee"], ["bullet"]),
    damageKind: "melee",
    axes: ["areaVsDamage", "cooldownVsDamage"],
    ...manaSkill(T.galeSlash),
  },
  scatterSigil: {
    key: "scatterSigil",
    name: "散弾符",
    icon: "散",
    verb: "前方へ 7 発を扇に撃つ。1 体にまとめて当てると大きく怯ませる",
    tags: ["projectile"],
    keywords: kw(["bullet", "stagger"]),
    damageKind: "ranged",
    axes: ["countVsDamage", "cooldownVsDamage", "areaVsDamage"],
    ...manaSkill(T.scatterSigil),
  },
  stomp: {
    key: "stomp",
    name: "震脚",
    icon: "震",
    verb: "足元を踏み鳴らし、周りの敵を大きく怯ませて敵弾を消す（少しの間動けない）",
    tags: ["melee", "area"],
    keywords: kw(["stagger", "area"], ["bullet"]),
    damageKind: "melee",
    axes: ["areaVsDamage", "cooldownVsDamage"],
    ...manaSkill(T.stomp),
    combos: ["reelStomp"],
  },
  threadReel: {
    key: "threadReel",
    name: "手繰り糸",
    icon: "糸",
    verb: "カーソルから自分へ糸を張り、少し後に糸に触れた敵をまとめて手前へ引く",
    tags: ["projectile"],
    keywords: kw(["area"]),
    damageKind: "ranged",
    axes: ["areaVsDamage", "cooldownVsDamage", "speedVsDamage"],
    ...manaSkill(T.threadReel),
    applies: APPLIES.threadReel,
  },
  meteorDive: {
    key: "meteorDive",
    name: "墜星",
    icon: "星",
    verb: "跳び上がり、少し後にカーソル地点へ落ちて周りを打つ（落下点は敵にも見える）",
    tags: ["movement", "area"],
    keywords: kw(["dash", "area"]),
    damageKind: "melee",
    axes: ["areaVsDamage", "speedVsDamage", "cooldownVsDamage"],
    ...manaSkill(T.meteorDive),
    combos: ["levelMeteor"],
  },
  swallowFlip: {
    key: "swallowFlip",
    name: "燕返し",
    icon: "燕",
    verb: "カーソル方向へ跳び、着地の瞬間に元の位置へ向けて斬撃が戻る（往復 2 回当たる）",
    tags: ["movement", "melee"],
    keywords: kw(["dash", "melee"]),
    damageKind: "melee",
    axes: ["areaVsDamage", "cooldownVsDamage", "speedVsDamage"],
    ...cooldownSkill(T.swallowFlip, T.swallowFlip.poise),
  },
  boneRing: {
    key: "boneRing",
    name: "骨片の輪",
    icon: "骨",
    verb: "自分の周りに骨片を回す。骨片は敵弾を 1 発ずつ止める（攻撃はしない）",
    tags: ["defense", "summon"],
    keywords: kw(["ward"], ["bullet"]),
    damageKind: "none",
    axes: ["durationVsPotency", "cooldownVsPotency"],
    ...cooldownSkill(T.boneRing, 0),
  },
  backflow: {
    key: "backflow",
    name: "巻き戻し",
    icon: "戻",
    verb: "少し前にいた位置へ戻り、その間に受けたダメージの一部を取り戻す。戻る道の敵にも当たる",
    tags: ["movement", "defense"],
    keywords: kw(["heal", "dash"], ["hurt"]),
    damageKind: "melee",
    axes: ["cooldownVsDamage", "areaVsDamage"],
    ...cooldownSkill(T.backflow, T.backflow.poise),
  },
  scarRoar: {
    key: "scarRoar",
    name: "傷返し",
    icon: "傷",
    verb: "自分の状態異常をすべて剥がし、周りの敵へ付けて衝撃を放つ（種類が多いほど強い）",
    tags: ["area", "defense"],
    keywords: kw(["area"], ["hurt"]),
    damageKind: "melee",
    axes: ["areaVsDamage", "cooldownVsDamage"],
    ...cooldownSkill(T.scarRoar, T.scarRoar.poise),
  },
  manaSpring: {
    key: "manaSpring",
    name: "湧き石",
    icon: "湧",
    verb: "足元に石を置く。石の周りで近接を当てると気力が多く戻る",
    tags: ["placed", "buff"],
    keywords: kw(["placed", "mana"], ["melee"]),
    damageKind: "none",
    axes: ["durationVsPotency", "cooldownVsPotency"],
    ...cooldownSkill(T.manaSpring, 0),
  },
  turret: {
    key: "turret",
    name: "砲台",
    icon: "砲",
    verb: "砲台を置く。自分が射撃・近接で攻撃するたび、砲台もカーソル方向へ 1 発撃つ（砲台だけでは撃たない）",
    tags: ["placed", "summon", "projectile"],
    keywords: kw(["placed", "bullet"], ["ranged"]),
    damageKind: "ranged",
    axes: ["countVsDamage", "durationVsPotency", "cooldownVsDamage"],
    ...manaSkill(T.turret),
  },
};
