import { attack } from "../../core/element";
import type { ArtSpec } from "./types";

/**
 * 刃の武器技（剣・大剣・双剣・刀・鉈・爪）。数値は data/balance/skills/ART/<武器種>.json。
 * 武器種の手触り（docs/ideas/weapon-skills.md の各節）を伸ばす方向で作る
 */

const MELEE = attack("melee", "physical");
const RANGED = attack("ranged", "physical");
const AREA = attack("area", "physical");
const POISON_MELEE = attack("melee", "hybrid", "poison");

// ---- 剣: 素直な斬撃・受け流し・十字断ち。何でも一通りこなす ----
const SWORD: readonly ArtSpec[] = [
  {
    key: "swordCrossCut",
    moveset: "sword",
    name: "十字斬り",
    icon: "十",
    verb: "前方を横、続けて縦に斬る",
    tags: ["melee"],
    attack: MELEE,
    acts: [
      { kind: "arc", n: "side" },
      { kind: "line", n: "down" },
    ],
  },
  {
    key: "swordRisingSlash",
    moveset: "sword",
    name: "昇り斬り",
    icon: "昇",
    verb: "下から斬り上げて大きく怯ませ、壁に叩きつける",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "rise" }],
  },
  {
    key: "swordFlashStep",
    moveset: "sword",
    name: "一閃",
    icon: "閃",
    verb: "照準の方向へ駆け抜け、通り道の敵を斬る。駆ける間は攻撃を受けない",
    tags: ["melee", "movement"],
    attack: MELEE,
    acts: [{ kind: "dash", n: "flash" }],
  },
  {
    key: "swordWhirlwind",
    moveset: "sword",
    name: "円舞斬",
    icon: "円",
    verb: "その場で回って周りの敵を 3 度斬る",
    tags: ["melee", "area"],
    attack: MELEE,
    acts: [{ kind: "ring", n: "spin" }],
  },
  {
    key: "swordSonicEdge",
    moveset: "sword",
    name: "飛燕剣",
    icon: "燕",
    verb: "剣を振って斬撃を飛ばし、並んだ敵を貫く",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "wave" }],
  },
  {
    key: "swordRiposte",
    moveset: "sword",
    name: "返し構え",
    icon: "返",
    verb: "一瞬だけ攻撃を受けない構えを取り、すぐに前方を斬り返す",
    tags: ["melee", "defense"],
    attack: MELEE,
    acts: [
      { kind: "buff", n: "guard" },
      { kind: "arc", n: "counter" },
    ],
  },
  {
    key: "swordTripleThrust",
    moveset: "sword",
    name: "三段突き",
    icon: "突",
    verb: "照準の方向へ素早く 3 度突く（突く間も向きを変えられる）",
    tags: ["melee"],
    attack: MELEE,
    acts: [
      { kind: "line", n: "t1" },
      { kind: "line", n: "t2" },
      { kind: "line", n: "t3" },
    ],
  },
  {
    key: "swordHeavenSplit",
    moveset: "sword",
    name: "天割り",
    icon: "天",
    verb: "長く重い振り下ろし。怯んでいる敵には大きく効く",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "split", vs: "stagger" }],
    minDepth: 2,
  },
  {
    key: "swordBladeStorm",
    moveset: "sword",
    name: "剣嵐",
    icon: "嵐",
    verb: "カーソル地点に剣の嵐を起こし、しばらく斬り続ける",
    tags: ["area"],
    attack: AREA,
    acts: [
      { kind: "ring", n: "s1", anchor: "target" },
      { kind: "ring", n: "s2", anchor: "target" },
      { kind: "ring", n: "s3", anchor: "target" },
      { kind: "ring", n: "s4", anchor: "target" },
    ],
    minDepth: 2,
  },
  {
    key: "swordValor",
    moveset: "sword",
    name: "勇心",
    icon: "勇",
    verb: "心を奮わせ、しばらく与ダメが上がり、受けるダメージが減る",
    tags: ["buff"],
    attack: null,
    acts: [{ kind: "buff", n: "valor" }],
  },
  {
    key: "swordFinisher",
    moveset: "sword",
    name: "止め斬り",
    icon: "止",
    verb: "前方を斬り、弱った敵（ボスを除く）を仕留める",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "end" }],
  },
];

// ---- 大剣: 広く重い一撃と大振り。溜めず崩す ----
const GREATSWORD: readonly ArtSpec[] = [
  {
    key: "greatswordEarthCleave",
    moveset: "greatsword",
    name: "地裂斬",
    icon: "地",
    verb: "前方の帯を斬り裂き、崩れる瓦礫を残す",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "cleave", terrain: "rubble" }],
  },
  {
    key: "greatswordGiantSwing",
    moveset: "greatsword",
    name: "大旋回",
    icon: "旋",
    verb: "大きく旋回し、周りの敵をまとめて薙ぐ",
    tags: ["melee", "area"],
    attack: AREA,
    acts: [{ kind: "ring", n: "spin" }],
  },
  {
    key: "greatswordLeapSlam",
    moveset: "greatsword",
    name: "跳躍叩き",
    icon: "躍",
    verb: "前へ跳び、着地の衝撃で地を叩きつける",
    tags: ["melee", "movement"],
    attack: MELEE,
    acts: [
      { kind: "dash", n: "leap" },
      { kind: "ring", n: "slam" },
    ],
  },
  {
    key: "greatswordCrescent",
    moveset: "greatsword",
    name: "三日月",
    icon: "月",
    verb: "220° の大振りで周りを薙ぎ払う",
    tags: ["melee", "area"],
    attack: AREA,
    acts: [{ kind: "arc", n: "cres" }],
  },
  {
    key: "greatswordGuardBreak",
    moveset: "greatsword",
    name: "鎧砕き",
    icon: "鎧",
    verb: "重い一撃で鎧を砕き、崩れやすくする",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "break" }],
  },
  {
    key: "greatswordWindCutter",
    moveset: "greatsword",
    name: "飛刃",
    icon: "飛",
    verb: "大きく重い斬撃を飛ばし、並んだ敵を貫く",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "wave" }],
  },
  {
    key: "greatswordRampage",
    moveset: "greatsword",
    name: "暴れ振り",
    icon: "暴",
    verb: "3 連の大振りを叩き込む",
    tags: ["melee"],
    attack: MELEE,
    acts: [
      { kind: "arc", n: "r1" },
      { kind: "arc", n: "r2" },
      { kind: "arc", n: "r3" },
    ],
  },
  {
    key: "greatswordIronWill",
    moveset: "greatsword",
    name: "不動",
    icon: "不",
    verb: "身を固めて受けるダメージを減らす",
    tags: ["buff", "defense"],
    attack: null,
    acts: [{ kind: "buff", n: "stand" }],
  },
  {
    key: "greatswordBeheader",
    moveset: "greatsword",
    name: "断頭",
    icon: "断",
    verb: "首を狙う一振りで、弱った敵を仕留める",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "head" }],
  },
  {
    key: "greatswordSwordPressure",
    moveset: "greatsword",
    name: "剣圧",
    icon: "圧",
    verb: "剣圧を前に飛ばして少し遅れて爆ぜ、敵弾を消す",
    tags: ["area"],
    attack: AREA,
    acts: [{ kind: "ring", n: "burst", clearsBullets: true }],
  },
  {
    key: "greatswordBoarRush",
    moveset: "greatsword",
    name: "猪突",
    icon: "猪",
    verb: "肩から重く突進し、通り道の敵を撥ね飛ばす",
    tags: ["melee", "movement"],
    attack: MELEE,
    acts: [{ kind: "dash", n: "rush" }],
  },
];

// ---- 双剣: 手数と出血。踏み込みと状態異常で崩す ----
const TWIN_BLADES: readonly ArtSpec[] = [
  {
    key: "twinBladesBladeDance",
    moveset: "twinBlades",
    name: "刃舞",
    icon: "舞",
    verb: "その場で回り、周りを 5 回斬る",
    tags: ["melee", "area"],
    attack: AREA,
    acts: [{ kind: "ring", n: "dance" }],
  },
  {
    key: "twinBladesShadowRush",
    moveset: "twinBlades",
    name: "影走り",
    icon: "影",
    verb: "踏み込み、背後へ回り込んで斬る",
    tags: ["melee", "movement"],
    attack: MELEE,
    acts: [
      { kind: "dash", n: "rush" },
      { kind: "arc", n: "back" },
    ],
  },
  {
    key: "twinBladesCrossThrow",
    moveset: "twinBlades",
    name: "交差投げ",
    icon: "交",
    verb: "跳ねる刃を交差するように 2 本投げる",
    tags: ["projectile"],
    attack: RANGED,
    acts: [
      { kind: "shot", n: "t1", shot: "ricochet" },
      { kind: "shot", n: "t2", shot: "ricochet" },
    ],
  },
  {
    key: "twinBladesFlurry",
    moveset: "twinBlades",
    name: "百裂",
    icon: "百",
    verb: "前方を素早く 6 連撃する",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "flurry" }],
  },
  {
    key: "twinBladesBleedEdge",
    moveset: "twinBlades",
    name: "血刃",
    icon: "血",
    verb: "刃で切り裂き、出血させる",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "edge" }],
  },
  {
    key: "twinBladesVenomKiss",
    moveset: "twinBlades",
    name: "毒口づけ",
    icon: "毒",
    verb: "毒を纏った突きを放つ",
    tags: ["melee"],
    attack: POISON_MELEE,
    acts: [{ kind: "line", n: "kiss" }],
  },
  {
    key: "twinBladesBackstab",
    moveset: "twinBlades",
    name: "背取り",
    icon: "取",
    verb: "照準地点へ跳び込み、背後から斬る",
    tags: ["melee", "movement"],
    attack: MELEE,
    acts: [
      { kind: "blink", n: "jump", anchor: "target" },
      { kind: "arc", n: "stab" },
    ],
  },
  {
    key: "twinBladesWhirlDash",
    moveset: "twinBlades",
    name: "旋回疾走",
    icon: "旋",
    verb: "旋回しながら走り抜け、触れた敵を斬る",
    tags: ["melee", "movement"],
    attack: MELEE,
    acts: [{ kind: "dash", n: "whirl" }],
  },
  {
    key: "twinBladesAfterimage",
    moveset: "twinBlades",
    name: "残り影",
    icon: "残",
    verb: "飛び退いて残像を残し、しばらく足が速くなる",
    tags: ["movement", "buff"],
    attack: null,
    acts: [
      { kind: "dash", n: "leap" },
      { kind: "buff", n: "after" },
    ],
  },
  {
    key: "twinBladesReap",
    moveset: "twinBlades",
    name: "双刈り",
    icon: "刈",
    verb: "出血した傷を裂いて大きく斬る",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "reap", vs: "bleed", consume: true }],
  },
  {
    key: "twinBladesTempest",
    moveset: "twinBlades",
    name: "双嵐",
    icon: "嵐",
    verb: "照準地点に刃の嵐を起こし、3 度斬りつける",
    tags: ["area"],
    attack: AREA,
    acts: [
      { kind: "ring", n: "s1", anchor: "target" },
      { kind: "ring", n: "s2", anchor: "target" },
      { kind: "ring", n: "s3", anchor: "target" },
    ],
  },
];

// ---- 刀: 速い斬りと居合。溜めと見切りで一撃を伸ばす ----
const KATANA: readonly ArtSpec[] = [
  {
    key: "katanaIai",
    moveset: "katana",
    name: "居合抜き",
    icon: "居",
    verb: "速く重い抜刀を帯状に放つ",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "draw" }],
  },
  {
    key: "katanaFlash",
    moveset: "katana",
    name: "迅閃",
    icon: "閃",
    verb: "瞬時に踏み込んで一閃する",
    tags: ["melee", "movement"],
    attack: MELEE,
    acts: [{ kind: "dash", n: "flash" }],
  },
  {
    key: "katanaCrescent",
    moveset: "katana",
    name: "月影",
    icon: "影",
    verb: "大きな弧を描いて斬り払う",
    tags: ["melee", "area"],
    attack: AREA,
    acts: [{ kind: "arc", n: "moon" }],
  },
  {
    key: "katanaTripleIai",
    moveset: "katana",
    name: "三連居合",
    icon: "三",
    verb: "居合を三連続で放つ（打つ間も向きを変えられる）",
    tags: ["melee"],
    attack: MELEE,
    acts: [
      { kind: "line", n: "t1" },
      { kind: "line", n: "t2" },
      { kind: "line", n: "t3" },
    ],
  },
  {
    key: "katanaCounter",
    moveset: "katana",
    name: "見切り",
    icon: "見",
    verb: "一瞬だけ攻撃を受けない構えを取り、鋭く斬り返す",
    tags: ["melee", "defense"],
    attack: MELEE,
    acts: [
      { kind: "buff", n: "guard" },
      { kind: "arc", n: "counter" },
    ],
  },
  {
    key: "katanaWindSlash",
    moveset: "katana",
    name: "風斬",
    icon: "風",
    verb: "速い斬撃を飛ばして敵を貫く",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "wind" }],
  },
  {
    key: "katanaBlossom",
    moveset: "katana",
    name: "血桜",
    icon: "桜",
    verb: "斬った傷から血を舞わせ、出血させる",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "sakura" }],
  },
  {
    key: "katanaDrawCircle",
    moveset: "katana",
    name: "抜刀陣",
    icon: "陣",
    verb: "抜刀の構えから周囲を一閃する",
    tags: ["melee", "area"],
    attack: AREA,
    acts: [{ kind: "ring", n: "circle" }],
  },
  {
    key: "katanaThousandCuts",
    moveset: "katana",
    name: "千本斬り",
    icon: "千",
    verb: "照準地点で刀の乱舞を起こし、6 度斬りつける",
    tags: ["area"],
    attack: AREA,
    acts: [
      { kind: "ring", n: "c1", anchor: "target" },
      { kind: "ring", n: "c2", anchor: "target" },
      { kind: "ring", n: "c3", anchor: "target" },
      { kind: "ring", n: "c4", anchor: "target" },
      { kind: "ring", n: "c5", anchor: "target" },
      { kind: "ring", n: "c6", anchor: "target" },
    ],
  },
  {
    key: "katanaClearMind",
    moveset: "katana",
    name: "明鏡止水",
    icon: "鏡",
    verb: "心を静め、しばらく与ダメが上がり足も速くなる",
    tags: ["buff"],
    attack: null,
    acts: [{ kind: "buff", n: "mind" }],
  },
  {
    key: "katanaSever",
    moveset: "katana",
    name: "両断",
    icon: "両",
    verb: "渾身の一太刀で、弱った敵を両断する",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "cut" }],
  },
];

// ---- 鉈: 重く叩きつける。壁と崩勢を絡める ----
const CLEAVER: readonly ArtSpec[] = [
  {
    key: "cleaverChop",
    moveset: "cleaver",
    name: "鉈割り",
    icon: "叩",
    verb: "重く振り下ろして叩き割る",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "chop" }],
  },
  {
    key: "cleaverHack",
    moveset: "cleaver",
    name: "滅多切り",
    icon: "滅",
    verb: "4 連続で滅多切りにする",
    tags: ["melee"],
    attack: MELEE,
    acts: [
      { kind: "arc", n: "h1" },
      { kind: "arc", n: "h2" },
      { kind: "arc", n: "h3" },
      { kind: "arc", n: "h4" },
    ],
  },
  {
    key: "cleaverThrow",
    moveset: "cleaver",
    name: "鉈投げ",
    icon: "投",
    verb: "鉈を投げつけ、跳ねて敵を刻む",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "toss", shot: "ricochet" }],
  },
  {
    key: "cleaverButcher",
    moveset: "cleaver",
    name: "解体",
    icon: "解",
    verb: "崩れた敵に強く、出血させながら解体する",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "cut", vs: "broken" }],
  },
  {
    key: "cleaverShoulder",
    moveset: "cleaver",
    name: "肩突撃",
    icon: "肩",
    verb: "肩から突っ込み、壁際で大きく弾き飛ばす",
    tags: ["melee", "movement"],
    attack: MELEE,
    acts: [{ kind: "dash", n: "charge" }],
  },
  {
    key: "cleaverQuake",
    moveset: "cleaver",
    name: "地叩き",
    icon: "地",
    verb: "地面を叩き割り、瓦礫を残す",
    tags: ["area"],
    attack: AREA,
    acts: [{ kind: "ring", n: "quake", terrain: "rubble" }],
  },
  {
    key: "cleaverBerserk",
    moveset: "cleaver",
    name: "狂乱",
    icon: "狂",
    verb: "血を滾らせ、しばらく与ダメが上がり怒気を纏う",
    tags: ["buff"],
    attack: null,
    acts: [{ kind: "buff", n: "rage" }],
  },
  {
    key: "cleaverSever",
    moveset: "cleaver",
    name: "断ち切り",
    icon: "断",
    verb: "止めの帯を薙ぎ払い、弱った敵を断つ",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "end" }],
  },
  {
    key: "cleaverWhirl",
    moveset: "cleaver",
    name: "大回転",
    icon: "回",
    verb: "大きく回転し、周りを 3 回叩く",
    tags: ["melee", "area"],
    attack: AREA,
    acts: [{ kind: "ring", n: "whirl" }],
  },
  {
    key: "cleaverBoneCrush",
    moveset: "cleaver",
    name: "骨砕き",
    icon: "骨",
    verb: "重く叩きつけ、骨を砕いて崩す",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "crush" }],
  },
  {
    key: "cleaverRend",
    moveset: "cleaver",
    name: "鉈裂き",
    icon: "裂",
    verb: "深く斬りつけ、大きく出血させる",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "rend" }],
  },
];

// ---- 爪: 最速の連撃と出血。踏み込みと消費で伸ばす ----
const CLAWS: readonly ArtSpec[] = [
  {
    key: "clawsRend",
    moveset: "claws",
    name: "八つ裂き",
    icon: "裂",
    verb: "3 回連続で切り裂き、出血を重ねる",
    tags: ["melee"],
    attack: MELEE,
    acts: [
      { kind: "arc", n: "r1" },
      { kind: "arc", n: "r2" },
      { kind: "arc", n: "r3" },
    ],
  },
  {
    key: "clawsPounce",
    moveset: "claws",
    name: "飛び掛かり",
    icon: "掛",
    verb: "跳びかかって前へ強く踏み込む",
    tags: ["melee", "movement"],
    attack: MELEE,
    acts: [{ kind: "dash", n: "pounce" }],
  },
  {
    key: "clawsFrenzy",
    moveset: "claws",
    name: "狂爪",
    icon: "狂",
    verb: "前方を 6 連続で切り刻む",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "frenzy" }],
  },
  {
    key: "clawsSpin",
    moveset: "claws",
    name: "回転爪",
    icon: "転",
    verb: "その場で回転し、周りを爪で薙ぐ",
    tags: ["melee", "area"],
    attack: AREA,
    acts: [{ kind: "ring", n: "spin" }],
  },
  {
    key: "clawsHemorrhage",
    moveset: "claws",
    name: "血裂爪",
    icon: "血",
    verb: "出血した傷を裂き、大きく出血させる（出血を消費）",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "tear", vs: "bleed", consume: true }],
  },
  {
    key: "clawsLeapBack",
    moveset: "claws",
    name: "裂き退き",
    icon: "退",
    verb: "斬りつけてから大きく跳び退く",
    tags: ["melee", "movement"],
    attack: MELEE,
    acts: [
      { kind: "arc", n: "slash" },
      { kind: "dash", n: "leap" },
    ],
  },
  {
    key: "clawsShred",
    moveset: "claws",
    name: "爪裂き",
    icon: "抓",
    verb: "出血の帯で前方を切り裂く",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "shred" }],
  },
  {
    key: "clawsBeast",
    moveset: "claws",
    name: "獣性",
    icon: "獣",
    verb: "獣の性を解き放ち、しばらく足が速く与ダメも上がる",
    tags: ["buff"],
    attack: null,
    acts: [{ kind: "buff", n: "beast" }],
  },
  {
    key: "clawsSlashWave",
    moveset: "claws",
    name: "爪風",
    icon: "風",
    verb: "爪風を 3 本の扇に飛ばす",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "wave" }],
  },
  {
    key: "clawsDive",
    moveset: "claws",
    name: "急降下",
    icon: "降",
    verb: "跳び上がり、着地の周りを爪で払う",
    tags: ["melee", "movement"],
    attack: MELEE,
    acts: [
      { kind: "dash", n: "jump" },
      { kind: "ring", n: "land" },
    ],
  },
  {
    key: "clawsVenom",
    moveset: "claws",
    name: "毒爪",
    icon: "毒",
    verb: "毒を纏った爪で切りつける",
    tags: ["melee"],
    attack: POISON_MELEE,
    acts: [{ kind: "arc", n: "venom" }],
  },
];

export const BLADE_ART_SPECS: readonly ArtSpec[] = [
  ...SWORD,
  ...GREATSWORD,
  ...TWIN_BLADES,
  ...KATANA,
  ...CLEAVER,
  ...CLAWS,
];
