import { attack } from "../../core/element";
import type { ArtSpec } from "./types";

/**
 * 共通技の後半 36 種（段取り 7c。docs/ideas/skills-7c-plan.md 1-2 の表）。武器技 298 を行為の列と命中の性質で束ね、
 * 束の代表の形と数値を写した。数値は data/balance/skills/ART/common.json（共通技 60 を 1 ファイルに持つ）。
 * どの武器種でも撃て、今の武器の型で形が変わる（skills/arts/transform.ts）
 */

const AREA = attack("area", "physical");
const DARK_HYBRID_MELEE = attack("melee", "hybrid", "dark");
const FIRE_AREA = attack("area", "physical", "fire");
const ICE_ARCANE_AREA = attack("area", "arcane", "ice");
const LIGHTNING_MELEE = attack("melee", "physical", "lightning");
const LIGHT_ARCANE_RANGED = attack("ranged", "arcane", "light");
const MELEE = attack("melee", "physical");
const POISON_ARCANE_RANGED = attack("ranged", "arcane", "poison");
const RANGED = attack("ranged", "physical");

export const COMMON_ART_SPECS_2: readonly ArtSpec[] = [
  {
    key: "commonWindCutter",
    moveset: null,
    name: "風切り",
    icon: "飛",
    verb: "大きく重い斬撃を飛ばし、並んだ敵を貫く",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "wave" }],
  },
  {
    key: "commonRicochet",
    moveset: null,
    name: "跳弾",
    icon: "跳",
    verb: "刃を投げ、壁や敵に跳ね返りながら当たり続ける",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "blade", shot: "ricochet" }],
  },
  {
    key: "commonScatter",
    moveset: null,
    name: "散弾",
    icon: "散",
    verb: "至近距離に散弾を浴びせる",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "scatter" }],
  },
  {
    key: "commonKiBlast",
    moveset: null,
    name: "気弾",
    icon: "気",
    verb: "気を練った弾を撃つ",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "blast" }],
  },
  {
    key: "commonVenomDart",
    moveset: null,
    name: "毒刃",
    icon: "毒",
    verb: "毒を塗った刃を投げ、当てた敵をむしばむ",
    tags: ["projectile"],
    attack: POISON_ARCANE_RANGED,
    acts: [{ kind: "shot", n: "blade" }],
  },
  {
    key: "commonWhirl",
    moveset: null,
    name: "旋風斬り",
    icon: "円",
    verb: "その場で回って周りの敵を 3 度斬る",
    tags: ["melee", "area"],
    attack: MELEE,
    acts: [{ kind: "ring", n: "spin" }],
  },
  {
    key: "commonTremor",
    moveset: null,
    name: "地叩き",
    icon: "震",
    verb: "地面を叩いて周りを揺らし、瓦礫を残す",
    tags: ["melee", "area"],
    attack: MELEE,
    acts: [{ kind: "ring", n: "shake", terrain: "rubble" }],
    minDepth: 2,
  },
  {
    key: "commonDeflect",
    moveset: null,
    name: "跳ね返し",
    icon: "弾",
    verb: "周りを払って敵の弾を消し、当たった敵も打つ",
    tags: ["melee", "defense"],
    attack: MELEE,
    acts: [{ kind: "ring", n: "parry", clearsBullets: true }],
  },
  {
    key: "commonSmokeScreen",
    moveset: null,
    name: "煙幕玉",
    icon: "幕",
    verb: "足元に煙幕を張り、敵の弾を遮る",
    tags: ["defense"],
    attack: null,
    acts: [{ kind: "ring", n: "smoke", terrain: "smoke", clearsBullets: true }],
  },
  {
    key: "commonPierce",
    moveset: null,
    name: "貫通突き",
    icon: "貫",
    verb: "長く踏み込んで前方を細く突き通す",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "thrust" }],
  },
  {
    key: "commonQuake",
    moveset: null,
    name: "地裂き",
    icon: "裂",
    verb: "前方の帯を斬り裂き、崩れる瓦礫を残す",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "cleave", terrain: "rubble" }],
  },
  {
    key: "commonRailshot",
    moveset: null,
    name: "撃ち抜き",
    icon: "線",
    verb: "収束した光の帯を放ち、並んだ敵を貫く",
    tags: ["projectile"],
    attack: LIGHT_ARCANE_RANGED,
    acts: [{ kind: "line", n: "rail" }],
  },
  {
    key: "commonFireWall",
    moveset: null,
    name: "炎の壁",
    icon: "壁",
    verb: "前方に炎の壁を張り、通り道に炎の床を残す",
    tags: ["area", "fire"],
    attack: FIRE_AREA,
    acts: [{ kind: "line", n: "wall", terrain: "fire" }],
  },
  {
    key: "commonShove",
    moveset: null,
    name: "押し込み",
    icon: "押",
    verb: "前方を広く押し込み、敵を押し飛ばす",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "push" }],
  },
  {
    key: "commonCrescent",
    moveset: null,
    name: "三日月",
    icon: "月",
    verb: "220° の大振りで周りを薙ぎ払う",
    tags: ["melee", "area"],
    attack: AREA,
    acts: [{ kind: "arc", n: "cres" }],
  },
  {
    key: "commonBleedEdge",
    moveset: null,
    name: "血刃",
    icon: "刃",
    verb: "刃で切り裂き、出血させる",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "edge" }],
  },
  {
    key: "commonRisingSlash",
    moveset: null,
    name: "昇り斬り",
    icon: "昇",
    verb: "下から斬り上げて大きく怯ませ、壁に叩きつける",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "rise" }],
  },
  {
    key: "commonFlurry",
    moveset: null,
    name: "百裂",
    icon: "百",
    verb: "前方を素早く 6 連撃する",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "flurry" }],
  },
  {
    key: "commonBomb",
    moveset: null,
    name: "炸裂玉",
    icon: "炸",
    verb: "カーソル地点へ玉を投げ、着弾して爆ぜる",
    tags: ["area"],
    attack: AREA,
    acts: [{ kind: "ring", n: "blast", anchor: "target" }],
  },
  {
    key: "commonFreezeBomb",
    moveset: null,
    name: "冷却弾",
    icon: "冷",
    verb: "カーソル地点を凍てつかせ、氷床を残す",
    tags: ["area", "cold"],
    attack: ICE_ARCANE_AREA,
    acts: [{ kind: "ring", n: "freeze", anchor: "target", terrain: "ice" }],
  },
  {
    key: "commonFlashBang",
    moveset: null,
    name: "閃光弾",
    icon: "閃",
    verb: "照準地点で閃光弾を弾けさせ、周りの敵を沈黙させ怯えさせる",
    tags: ["area"],
    attack: null,
    acts: [{ kind: "ring", n: "flash", anchor: "target" }],
  },
  {
    key: "commonLunge",
    moveset: null,
    name: "突進斬り",
    icon: "駆",
    verb: "照準の方向へ駆け抜け、通り道の敵を斬る。駆ける間は攻撃を受けない",
    tags: ["melee", "movement"],
    attack: MELEE,
    acts: [{ kind: "dash", n: "flash" }],
  },
  {
    key: "commonCharge",
    moveset: null,
    name: "猪突",
    icon: "猪",
    verb: "肩から重く突進し、通り道の敵を撥ね飛ばす",
    tags: ["melee", "movement"],
    attack: MELEE,
    acts: [{ kind: "dash", n: "rush" }],
  },
  {
    key: "commonThousandCuts",
    moveset: null,
    name: "千本斬り",
    icon: "千",
    verb: "カーソル地点に刃の嵐を起こし、しばらく斬り続ける",
    tags: ["area"],
    attack: AREA,
    acts: [
      { kind: "ring", n: "s1", anchor: "target" },
      { kind: "ring", n: "s2", anchor: "target" },
      { kind: "ring", n: "s3", anchor: "target" },
      { kind: "ring", n: "s4", anchor: "target" },
    ],
    minDepth: 2,
  },
  {
    key: "commonTriplePound",
    moveset: null,
    name: "三連打",
    icon: "連",
    verb: "カーソル地点を 3 度続けて打ち据える",
    tags: ["area"],
    attack: AREA,
    acts: [
      { kind: "ring", n: "s1", anchor: "target" },
      { kind: "ring", n: "s2", anchor: "target" },
      { kind: "ring", n: "s3", anchor: "target" },
    ],
  },
  {
    key: "commonInhale",
    moveset: null,
    name: "吸い風",
    icon: "寄",
    verb: "風を吸い込み、周りの敵を引き寄せる",
    tags: ["area"],
    attack: MELEE,
    acts: [{ kind: "pull", n: "inhale" }],
  },
  {
    key: "commonTripleThrust",
    moveset: null,
    name: "三段突き",
    icon: "突",
    verb: "照準の方向へ素早く 3 度突く（突く間も向きを変えられる）",
    tags: ["melee"],
    attack: MELEE,
    acts: [
      { kind: "line", n: "t1" },
      { kind: "line", n: "t2" },
      { kind: "line", n: "t3" },
    ],
  },
  {
    key: "commonLeapSlam",
    moveset: null,
    name: "跳躍叩き",
    icon: "躍",
    verb: "前へ跳び、着地の衝撃で地を叩きつける",
    tags: ["melee", "movement"],
    attack: MELEE,
    acts: [
      { kind: "dash", n: "leap" },
      { kind: "ring", n: "slam" },
    ],
  },
  {
    key: "commonDiveShot",
    moveset: null,
    name: "飛び込み撃ち",
    icon: "転",
    verb: "照準の方向へ飛び込み、着地際に前方を撃つ",
    tags: ["movement", "projectile"],
    attack: RANGED,
    acts: [
      { kind: "dash", n: "dive" },
      { kind: "shot", n: "shot" },
    ],
  },
  {
    key: "commonRiposte",
    moveset: null,
    name: "返し構え",
    icon: "返",
    verb: "一瞬だけ攻撃を受けない構えを取り、すぐに前方を斬り返す",
    tags: ["melee", "defense"],
    attack: MELEE,
    acts: [
      { kind: "buff", n: "guard" },
      { kind: "arc", n: "counter" },
    ],
  },
  {
    key: "commonHack",
    moveset: null,
    name: "滅多切り",
    icon: "滅",
    verb: "3 連の大振りを叩き込む",
    tags: ["melee"],
    attack: MELEE,
    acts: [
      { kind: "arc", n: "r1" },
      { kind: "arc", n: "r2" },
      { kind: "arc", n: "r3" },
    ],
  },
  {
    key: "commonMeteorDive",
    moveset: null,
    name: "墜星",
    icon: "墜",
    verb: "闇に紛れて跳び、着地点に闇の円を広げる",
    tags: ["melee", "movement"],
    attack: DARK_HYBRID_MELEE,
    acts: [
      { kind: "blink", n: "step", anchor: "target" },
      { kind: "ring", n: "burst" },
    ],
  },
  {
    key: "commonDetonate",
    moveset: null,
    name: "一斉起爆",
    icon: "起",
    verb: "置いた設置弾をすべて起爆し、自分の周りも巻き込む",
    tags: ["area"],
    attack: AREA,
    acts: [
      { kind: "detonate", n: "boom" },
      { kind: "ring", n: "blast" },
    ],
  },
  {
    key: "commonCrossCut",
    moveset: null,
    name: "十字斬り",
    icon: "十",
    verb: "前方を横、続けて縦に斬る",
    tags: ["melee"],
    attack: MELEE,
    acts: [
      { kind: "arc", n: "side" },
      { kind: "line", n: "down" },
    ],
  },
  {
    key: "commonBackstab",
    moveset: null,
    name: "背取り",
    icon: "取",
    verb: "照準地点へ跳び込み、背後から斬る",
    tags: ["melee", "movement"],
    attack: MELEE,
    acts: [
      { kind: "blink", n: "jump", anchor: "target" },
      { kind: "arc", n: "stab" },
    ],
  },
  {
    key: "commonStrikeAway",
    moveset: null,
    name: "飛び退き打ち",
    icon: "払",
    verb: "前へ打ってから後ろへ跳び退く。跳ぶ間は攻撃を受けない",
    tags: ["melee", "movement"],
    attack: LIGHTNING_MELEE,
    acts: [
      { kind: "line", n: "hit" },
      { kind: "dash", n: "back" },
    ],
  },
];
