import { attack } from "../../core/element";
import type { ArtSpec } from "./types";

/**
 * 共通技（どの武器種でも撃てる技）。数値は data/balance/skills/ART/common.json。
 * 武器の手触りに依らない「道具・魔法・体術」の汎用品。武器技より 1 回あたりは控えめにする
 */

const MELEE = attack("melee", "physical");
const AREA = attack("area", "physical");
const FIRE = attack("ranged", "arcane", "fire");
const FIRE_AREA = attack("area", "arcane", "fire");
const ICE = attack("ranged", "arcane", "ice");
const ICE_AREA = attack("area", "arcane", "ice");
const THUNDER = attack("area", "arcane", "lightning");
const POISON_AREA = attack("area", "arcane", "poison");
const DARK = attack("ranged", "arcane", "dark");
const LIGHT_AREA = attack("area", "arcane", "light");
const RANGED = attack("ranged", "physical");

export const COMMON_ART_SPECS: readonly ArtSpec[] = [
  {
    key: "commonShockwave",
    moveset: null,
    name: "衝撃波",
    icon: "衝",
    verb: "足元から衝撃波を放ち、周りの敵を押し返す",
    tags: ["area"],
    attack: AREA,
    acts: [{ kind: "ring", n: "wave" }],
  },
  {
    key: "commonBackstep",
    moveset: null,
    name: "飛び退き",
    icon: "退",
    verb: "照準と逆へ大きく跳び退く。跳ぶ間は攻撃を受けない",
    tags: ["movement", "defense"],
    attack: null,
    acts: [{ kind: "dash", n: "leap" }],
  },
  {
    key: "commonBlink",
    moveset: null,
    name: "瞬身",
    icon: "瞬",
    verb: "カーソル地点へ一瞬で移る（壁は越えない）",
    tags: ["movement"],
    attack: null,
    acts: [{ kind: "blink", n: "blink", anchor: "target" }],
  },
  {
    key: "commonWarCry",
    moveset: null,
    name: "鬨の声",
    icon: "鬨",
    verb: "叫んで周りの敵を怯えさせ、しばらく与ダメが上がる",
    tags: ["buff", "area"],
    attack: null,
    acts: [
      { kind: "ring", n: "shout" },
      { kind: "buff", n: "rouse" },
    ],
  },
  {
    key: "commonFirstAid",
    moveset: null,
    name: "応急手当",
    icon: "癒",
    verb: "傷を手当てして生命を回復する",
    tags: ["buff", "defense"],
    attack: null,
    acts: [{ kind: "buff", n: "mend" }],
  },
  {
    key: "commonMeditate",
    moveset: null,
    name: "瞑想",
    icon: "瞑",
    verb: "息を整えて気力を取り戻し、少しの間身を固める",
    tags: ["buff", "defense"],
    attack: null,
    acts: [{ kind: "buff", n: "calm" }],
  },
  {
    key: "commonFireball",
    moveset: null,
    name: "火球",
    icon: "火",
    verb: "燃える火の玉を撃ち、当てた敵を燃やす",
    tags: ["projectile", "fire"],
    attack: FIRE,
    acts: [{ kind: "shot", n: "ball" }],
  },
  {
    key: "commonIceLance",
    moveset: null,
    name: "氷の投げ槍",
    icon: "槍",
    verb: "敵を貫く氷の槍を撃ち、冷気を付ける",
    tags: ["projectile", "cold"],
    attack: ICE,
    acts: [{ kind: "shot", n: "lance" }],
  },
  {
    key: "commonThunderclap",
    moveset: null,
    name: "雷鳴",
    icon: "鳴",
    verb: "カーソル地点に雷を落とし、周りの敵を感電させる",
    tags: ["area", "lightning"],
    attack: THUNDER,
    acts: [{ kind: "ring", n: "bolt", anchor: "target" }],
  },
  {
    key: "commonPoisonMist",
    moveset: null,
    name: "毒霧",
    icon: "霧",
    verb: "カーソル地点に毒の霧を撒き、毒と毒沼を残す",
    tags: ["area"],
    attack: POISON_AREA,
    acts: [{ kind: "ring", n: "mist", anchor: "target", terrain: "bog" }],
  },
  {
    key: "commonShadowBolt",
    moveset: null,
    name: "闇弾",
    icon: "闇",
    verb: "闇の弾を撃ち、当てた敵を弱らせる",
    tags: ["projectile"],
    attack: DARK,
    acts: [{ kind: "shot", n: "bolt" }],
  },
  {
    key: "commonHolyNova",
    moveset: null,
    name: "聖光",
    icon: "聖",
    verb: "光を放って周りの敵を焼き、自分の生命を少し戻す",
    tags: ["area", "buff"],
    attack: LIGHT_AREA,
    acts: [
      { kind: "ring", n: "light" },
      { kind: "buff", n: "bless" },
    ],
  },
  {
    key: "commonChainSpark",
    moveset: null,
    name: "連鎖電",
    icon: "鎖",
    verb: "カーソルの近くの敵に電撃を放ち、近くの敵へ次々と跳ねる",
    tags: ["lightning"],
    attack: THUNDER,
    acts: [{ kind: "chain", n: "arc", anchor: "target" }],
  },
  {
    key: "commonMagnet",
    moveset: null,
    name: "引き寄せ",
    icon: "引",
    verb: "カーソル地点へ周りの敵を引き集め、崩す",
    tags: ["area"],
    attack: attack("area", "arcane", "dark"),
    acts: [{ kind: "pull", n: "gather", anchor: "target" }],
  },
  {
    key: "commonSmokeBomb",
    moveset: null,
    name: "煙玉",
    icon: "煙",
    verb: "足元に煙を張って跳び退く。煙は敵の弾を遮る",
    tags: ["movement", "defense"],
    attack: null,
    acts: [
      { kind: "ring", n: "smoke", terrain: "smoke" },
      { kind: "dash", n: "hop" },
    ],
  },
  {
    key: "commonKnifeFan",
    moveset: null,
    name: "投げ短刀",
    icon: "刀",
    verb: "短刀を扇に投げ、当てた敵を出血させる",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "knives" }],
  },
  {
    key: "commonMeteor",
    moveset: null,
    name: "流星",
    icon: "星",
    verb: "少し遅れてカーソル地点に燃える星が落ち、炎の床を残す",
    tags: ["area", "fire"],
    attack: FIRE_AREA,
    acts: [{ kind: "ring", n: "fall", anchor: "target", terrain: "fire" }],
    minDepth: 2,
  },
  {
    key: "commonQuickstep",
    moveset: null,
    name: "疾走",
    icon: "疾",
    verb: "しばらく足が速くなる",
    tags: ["buff", "movement"],
    attack: null,
    acts: [{ kind: "buff", n: "run" }],
  },
  {
    key: "commonIronSkin",
    moveset: null,
    name: "鉄身",
    icon: "鉄",
    verb: "体を硬くして受けるダメージを減らす",
    tags: ["buff", "defense"],
    attack: null,
    acts: [{ kind: "buff", n: "harden" }],
  },
  {
    key: "commonExecution",
    moveset: null,
    name: "介錯",
    icon: "介",
    verb: "前方を鋭く突き、弱った敵（ボスを除く）は仕留める",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "thrust" }],
    minDepth: 2,
  },
  {
    key: "commonBarrage",
    moveset: null,
    name: "乱れ弾",
    icon: "乱",
    verb: "照準の方向へ小さな弾を立て続けに撃つ（撃つ間も向きを変えられる）",
    tags: ["projectile"],
    attack: RANGED,
    acts: [
      { kind: "shot", n: "s1" },
      { kind: "shot", n: "s2" },
      { kind: "shot", n: "s3" },
      { kind: "shot", n: "s4" },
    ],
  },
  {
    key: "commonGroundSpike",
    moveset: null,
    name: "地槍",
    icon: "地",
    verb: "前方へ順に地面から槍が突き出て、通り道の敵を打ち上げる",
    tags: ["area"],
    attack: AREA,
    acts: [
      { kind: "ring", n: "near" },
      { kind: "ring", n: "mid" },
      { kind: "ring", n: "far" },
    ],
  },
  {
    key: "commonFrostNova",
    moveset: null,
    name: "氷輪",
    icon: "氷",
    verb: "周りを凍てつかせて敵に冷気を重ね、足元に氷床を張る",
    tags: ["area", "cold"],
    attack: ICE_AREA,
    acts: [{ kind: "ring", n: "frost", terrain: "ice" }],
  },
  {
    key: "commonBloodSurge",
    moveset: null,
    name: "血気",
    icon: "血",
    verb: "血をたぎらせ、しばらく与ダメと足が上がって怒気が付く",
    tags: ["buff"],
    attack: null,
    acts: [{ kind: "buff", n: "surge" }],
    minDepth: 2,
  },
];
