import { attack } from "../../core/element";
import type { ArtSpec } from "./types";

/**
 * 銃・魔法の武器技（二丁拳銃・短銃・長銃・砲・杖）。数値は data/balance/skills/ART/<武器種>.json。
 * 参照ステータスは docs/STATS_AND_SCALING.md 3 章の銃の対応（拳銃系 = 技巧+精神、小銃 = 筋力+技巧、
 * 手砲・杖 = 精神+霊力）に合わせ、殴り系の行為（銃把打ち・銃剣突撃・銃床打ち）だけ筋力+技巧にする
 */

const RANGED = attack("ranged", "physical");
const MELEE = attack("melee", "physical");
const AREA = attack("area", "physical");
const RANGED_FIRE = attack("ranged", "physical", "fire");
const RANGED_ICE = attack("ranged", "physical", "ice");
const RANGED_LIGHTNING = attack("ranged", "physical", "lightning");
const RANGED_LIGHT = attack("ranged", "arcane", "light");
const AREA_FIRE = attack("area", "physical", "fire");
const AREA_ICE = attack("area", "physical", "ice");

// ---- 二丁拳銃: 手数と持ち替えの速さ。単発は控えめ、連射・広がりで稼ぐ ----
const GUNNER: readonly ArtSpec[] = [
  {
    key: "gunnerFanFire",
    moveset: "gunner",
    name: "扇撃ち",
    icon: "扇",
    verb: "左右の銃口から扇状に撃つ",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "fan" }],
  },
  {
    key: "gunnerBulletDance",
    moveset: "gunner",
    name: "弾舞",
    icon: "舞",
    verb: "その場で回りながら全方位へ 8 発を撃ち出す",
    tags: ["projectile", "area"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "dance" }],
  },
  {
    key: "gunnerDiveShot",
    moveset: "gunner",
    name: "飛び込み撃ち",
    icon: "飛",
    verb: "照準の方向へ飛び込み、着地際に前方を撃つ",
    tags: ["movement", "projectile"],
    attack: RANGED,
    acts: [
      { kind: "dash", n: "dive" },
      { kind: "shot", n: "shot" },
    ],
  },
  {
    key: "gunnerDoubleTap",
    moveset: "gunner",
    name: "二連射",
    icon: "二",
    verb: "照準へ 2 発を叩き込む",
    tags: ["projectile"],
    attack: RANGED,
    acts: [
      { kind: "shot", n: "t1" },
      { kind: "shot", n: "t2" },
    ],
  },
  {
    key: "gunnerRicochet",
    moveset: "gunner",
    name: "跳弾",
    icon: "跳",
    verb: "壁で跳ね返りながら進む弾を放つ",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "bounce", shot: "ricochet" }],
  },
  {
    key: "gunnerBarrage",
    moveset: "gunner",
    name: "連射",
    icon: "連",
    verb: "照準の方向へ 6 連射する（撃つ間も向きを変えられる）",
    tags: ["projectile"],
    attack: RANGED,
    acts: [
      { kind: "shot", n: "s1" },
      { kind: "shot", n: "s2" },
      { kind: "shot", n: "s3" },
      { kind: "shot", n: "s4" },
      { kind: "shot", n: "s5" },
      { kind: "shot", n: "s6" },
    ],
  },
  {
    key: "gunnerPistolWhip",
    moveset: "gunner",
    name: "銃把打ち",
    icon: "把",
    verb: "銃把で前方を強く打ちつけ、大きく怯ませる",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "whip" }],
  },
  {
    key: "gunnerBlast",
    moveset: "gunner",
    name: "炸裂弾",
    icon: "炸",
    verb: "照準地点へ撃ち込み、着弾で爆ぜる",
    tags: ["area"],
    attack: AREA,
    acts: [{ kind: "ring", n: "blast", anchor: "target" }],
  },
  {
    key: "gunnerBackflip",
    moveset: "gunner",
    name: "後転撃ち",
    icon: "転",
    verb: "うしろへ跳びながら前方を撃つ。跳ぶ間は攻撃を受けない",
    tags: ["movement", "projectile"],
    attack: RANGED,
    acts: [
      { kind: "dash", n: "flip" },
      { kind: "shot", n: "shot" },
    ],
  },
  {
    key: "gunnerTrickShot",
    moveset: "gunner",
    name: "曲撃ち",
    icon: "曲",
    verb: "弾を曲げてカーソルの近くの敵から次々と当てる",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "chain", n: "curve", anchor: "target" }],
  },
  {
    key: "gunnerQuickDraw",
    moveset: "gunner",
    name: "早撃ち",
    icon: "早",
    verb: "素早く構え直し、しばらく与ダメが上がって足も速くなる",
    tags: ["buff"],
    attack: null,
    acts: [{ kind: "buff", n: "draw" }],
  },
];

// ---- 短銃: 片手の速さ。状態異常の弾を撃ち分ける ----
const SIDEARM: readonly ArtSpec[] = [
  {
    key: "sidearmSnipe",
    moveset: "sidearm",
    name: "精密射撃",
    icon: "精",
    verb: "引き金を絞り、単発の重い弾を撃ち込む",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "snipe" }],
  },
  {
    key: "sidearmQuickdraw",
    moveset: "sidearm",
    name: "早抜き",
    icon: "抜",
    verb: "抜き撃ちで 3 発を連続で放つ",
    tags: ["projectile"],
    attack: RANGED,
    acts: [
      { kind: "shot", n: "s1" },
      { kind: "shot", n: "s2" },
      { kind: "shot", n: "s3" },
    ],
  },
  {
    key: "sidearmFlash",
    moveset: "sidearm",
    name: "閃光弾",
    icon: "閃",
    verb: "照準地点で閃光弾を弾けさせ、周りの敵を沈黙させ怯えさせる",
    tags: ["area"],
    attack: null,
    acts: [{ kind: "ring", n: "flash", anchor: "target" }],
  },
  {
    key: "sidearmRoll",
    moveset: "sidearm",
    name: "転がり撃ち",
    icon: "転",
    verb: "横へ転がりながら前方を撃つ。転がる間は攻撃を受けない",
    tags: ["movement", "projectile"],
    attack: RANGED,
    acts: [
      { kind: "dash", n: "roll" },
      { kind: "shot", n: "shot" },
    ],
  },
  {
    key: "sidearmPiercer",
    moveset: "sidearm",
    name: "徹甲弾",
    icon: "徹",
    verb: "敵を貫通する徹甲弾を撃つ",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "pierce" }],
  },
  {
    key: "sidearmIncendiary",
    moveset: "sidearm",
    name: "焼夷弾",
    icon: "焼",
    verb: "燃える弾を撃ち、当てた敵を燃やす",
    tags: ["projectile", "fire"],
    attack: RANGED_FIRE,
    acts: [{ kind: "shot", n: "incend" }],
  },
  {
    key: "sidearmFreeze",
    moveset: "sidearm",
    name: "冷凍弾",
    icon: "冷",
    verb: "凍える弾を撃ち、当てた敵を冷やす",
    tags: ["projectile", "cold"],
    attack: RANGED_ICE,
    acts: [{ kind: "shot", n: "freeze" }],
  },
  {
    key: "sidearmShock",
    moveset: "sidearm",
    name: "電撃弾",
    icon: "電",
    verb: "帯電した弾を撃ち、当てた敵を感電させる",
    tags: ["projectile", "lightning"],
    attack: RANGED_LIGHTNING,
    acts: [{ kind: "shot", n: "shock" }],
  },
  {
    key: "sidearmMark",
    moveset: "sidearm",
    name: "標的指定",
    icon: "標",
    verb: "印を撃ち込み、当てた敵を脆弱にする",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "mark" }],
  },
  {
    key: "sidearmSteady",
    moveset: "sidearm",
    name: "呼吸止め",
    icon: "呼",
    verb: "息を止めて構え、しばらく与ダメが上がる",
    tags: ["buff"],
    attack: null,
    acts: [{ kind: "buff", n: "hold" }],
  },
  {
    key: "sidearmScatter",
    moveset: "sidearm",
    name: "散弾",
    icon: "散",
    verb: "至近距離に散弾を浴びせる",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "scatter" }],
  },
];

// ---- 長銃: 重い一撃と銃剣。射程と貫通で押す ----
const LONGARM: readonly ArtSpec[] = [
  {
    key: "longarmSnipe",
    moveset: "longarm",
    name: "狙撃",
    icon: "狙",
    verb: "速く重い弾を撃ち、並んだ敵を貫く",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "snipe" }],
  },
  {
    key: "longarmBayonet",
    moveset: "longarm",
    name: "銃剣突撃",
    icon: "剣",
    verb: "銃剣を構えて突撃し、通り道の敵を貫く",
    tags: ["melee", "movement"],
    attack: MELEE,
    acts: [{ kind: "dash", n: "charge" }],
  },
  {
    key: "longarmVolley",
    moveset: "longarm",
    name: "一斉射",
    icon: "一",
    verb: "束ねた弾を同時に撃ち込む",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "volley" }],
  },
  {
    key: "longarmHeadshot",
    moveset: "longarm",
    name: "頭撃ち",
    icon: "頭",
    verb: "狙いを定めた一線を撃ち抜き、弱った敵は仕留める",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "line", n: "head" }],
    minDepth: 2,
  },
  {
    key: "longarmRecoilJump",
    moveset: "longarm",
    name: "反動跳び",
    icon: "跳",
    verb: "反動を使ってうしろへ大きく跳ぶ",
    tags: ["movement"],
    attack: null,
    acts: [{ kind: "dash", n: "jump" }],
  },
  {
    key: "longarmRail",
    moveset: "longarm",
    name: "貫く一線",
    icon: "貫",
    verb: "収束した光の帯を放ち、並んだ敵を貫く",
    tags: ["projectile"],
    attack: RANGED_LIGHT,
    acts: [{ kind: "line", n: "rail" }],
  },
  {
    key: "longarmFlare",
    moveset: "longarm",
    name: "照明弾",
    icon: "照",
    verb: "照準地点に照明弾を撃ち込み、当てた敵を脆弱にする",
    tags: ["area"],
    attack: AREA,
    acts: [{ kind: "ring", n: "flare", anchor: "target" }],
  },
  {
    key: "longarmButtStroke",
    moveset: "longarm",
    name: "銃床打ち",
    icon: "床",
    verb: "銃床で殴りつけ、大きく怯ませる",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "stroke" }],
  },
  {
    key: "longarmSuppress",
    moveset: "longarm",
    name: "制圧射撃",
    icon: "制",
    verb: "照準の方向へ 5 連射して押さえ込む（撃つ間も向きを変えられる）",
    tags: ["projectile"],
    attack: RANGED,
    acts: [
      { kind: "shot", n: "s1" },
      { kind: "shot", n: "s2" },
      { kind: "shot", n: "s3" },
      { kind: "shot", n: "s4" },
      { kind: "shot", n: "s5" },
    ],
  },
  {
    key: "longarmExplosive",
    moveset: "longarm",
    name: "爆裂弾",
    icon: "爆",
    verb: "照準地点へ撃ち込み、大きく爆ぜる",
    tags: ["area"],
    attack: AREA,
    acts: [{ kind: "ring", n: "boom", anchor: "target" }],
    minDepth: 2,
  },
  {
    key: "longarmAim",
    moveset: "longarm",
    name: "集中",
    icon: "集",
    verb: "呼吸を整えて集中し、しばらく与ダメが上がる",
    tags: ["buff"],
    attack: null,
    acts: [{ kind: "buff", n: "focus" }],
  },
];

// ---- 砲: 最も重い一撃。爆発・地形・自分の設置弾との連動 ----
const CANNON: readonly ArtSpec[] = [
  {
    key: "cannonBlast",
    moveset: "cannon",
    name: "砲撃",
    icon: "砲",
    verb: "重い砲弾を放つ",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "blast" }],
  },
  {
    key: "cannonGrapeshot",
    moveset: "cannon",
    name: "散弾砲",
    icon: "散",
    verb: "至近距離へ 9 発の散弾をまとめて放つ",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "grape" }],
  },
  {
    key: "cannonRecoil",
    moveset: "cannon",
    name: "反動砲",
    icon: "反",
    verb: "発砲の反動でうしろへ跳びながら前方を撃つ",
    tags: ["movement", "projectile"],
    attack: RANGED,
    acts: [
      { kind: "dash", n: "recoil" },
      { kind: "shot", n: "shot" },
    ],
  },
  {
    key: "cannonBarrage",
    moveset: "cannon",
    name: "一斉砲火",
    icon: "斉",
    verb: "照準地点へ砲撃を 3 回撃ち込む",
    tags: ["area"],
    attack: AREA,
    acts: [
      { kind: "ring", n: "s1", anchor: "target" },
      { kind: "ring", n: "s2", anchor: "target" },
      { kind: "ring", n: "s3", anchor: "target" },
    ],
    minDepth: 2,
  },
  {
    key: "cannonShockwave",
    moveset: "cannon",
    name: "衝撃砲",
    icon: "衝",
    verb: "前方へ衝撃の帯を放ち、大きく押し飛ばす",
    tags: ["area"],
    attack: AREA,
    acts: [{ kind: "line", n: "push" }],
  },
  {
    key: "cannonNapalm",
    moveset: "cannon",
    name: "焼夷砲",
    icon: "焼",
    verb: "照準地点に焼夷弾を撃ち込み、炎の床を残す",
    tags: ["area", "fire"],
    attack: AREA_FIRE,
    acts: [{ kind: "ring", n: "napalm", anchor: "target", terrain: "fire" }],
  },
  {
    key: "cannonChainShot",
    moveset: "cannon",
    name: "連鎖弾",
    icon: "鎖",
    verb: "跳ね返りながら進む重い弾を撃つ",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "chain", shot: "ricochet" }],
  },
  {
    key: "cannonPointBlank",
    moveset: "cannon",
    name: "零距離",
    icon: "零",
    verb: "至近距離へ砲撃し、自分は後ろへ跳ぶ",
    tags: ["area", "movement"],
    attack: AREA,
    acts: [
      { kind: "ring", n: "blast" },
      { kind: "dash", n: "jump" },
    ],
  },
  {
    key: "cannonMortar",
    moveset: "cannon",
    name: "迫撃",
    icon: "迫",
    verb: "少し遅れて照準地点に大きな砲弾が降ってくる",
    tags: ["area"],
    attack: AREA,
    acts: [{ kind: "ring", n: "fall", anchor: "target" }],
    minDepth: 2,
  },
  {
    key: "cannonFrost",
    moveset: "cannon",
    name: "凍結砲",
    icon: "凍",
    verb: "冷気の砲弾を撃ち込み、氷の床を残す",
    tags: ["area", "cold"],
    attack: AREA_ICE,
    acts: [{ kind: "ring", n: "frost", anchor: "target", terrain: "ice" }],
  },
  {
    key: "cannonDetonate",
    moveset: "cannon",
    name: "起爆",
    icon: "起",
    verb: "床に置いた設置弾をまとめて起爆し、自分の周りも吹き飛ばす",
    tags: ["area"],
    attack: AREA,
    acts: [
      { kind: "detonate", n: "det" },
      { kind: "ring", n: "blast" },
    ],
  },
];

// ---- 杖: 6 属性の魔法を撃ち分ける ----
const WAND: readonly ArtSpec[] = [
  {
    key: "wandFlare",
    moveset: "wand",
    name: "火炎弾",
    icon: "炎",
    verb: "燃える弾を撃ち、当てた敵を燃やす",
    tags: ["projectile", "fire"],
    attack: attack("ranged", "arcane", "fire"),
    acts: [{ kind: "shot", n: "ball" }],
  },
  {
    key: "wandFrostBolt",
    moveset: "wand",
    name: "氷結弾",
    icon: "氷",
    verb: "凍える弾を撃ち、当てた敵を冷やす",
    tags: ["projectile", "cold"],
    attack: attack("ranged", "arcane", "ice"),
    acts: [{ kind: "shot", n: "bolt" }],
  },
  {
    key: "wandLightning",
    moveset: "wand",
    name: "落雷",
    icon: "雷",
    verb: "照準地点に雷を落とし、周りの敵を感電させる",
    tags: ["area", "lightning"],
    attack: attack("area", "arcane", "lightning"),
    acts: [{ kind: "ring", n: "bolt", anchor: "target" }],
  },
  {
    key: "wandVenom",
    moveset: "wand",
    name: "毒球",
    icon: "毒",
    verb: "照準地点に毒球を撃ち込み、毒沼を残す",
    tags: ["area"],
    attack: attack("area", "arcane", "poison"),
    acts: [{ kind: "ring", n: "ball", anchor: "target", terrain: "bog" }],
  },
  {
    key: "wandVortex",
    moveset: "wand",
    name: "渦",
    icon: "渦",
    verb: "照準地点に渦を起こして敵を引き寄せ、まとめて爆ぜさせる",
    tags: ["area"],
    attack: attack("area", "arcane", "dark"),
    acts: [{ kind: "pull", n: "gather", anchor: "target" }],
  },
  {
    key: "wandHolyRay",
    moveset: "wand",
    name: "光線",
    icon: "光",
    verb: "収束した光線を放ち、並んだ敵を貫く",
    tags: ["projectile"],
    attack: RANGED_LIGHT,
    acts: [{ kind: "line", n: "ray" }],
  },
  {
    key: "wandDarkOrb",
    moveset: "wand",
    name: "闇球",
    icon: "闇",
    verb: "ゆっくり進む闇の球を放ち、当てた敵を弱らせる",
    tags: ["projectile"],
    attack: attack("ranged", "arcane", "dark"),
    acts: [{ kind: "shot", n: "orb" }],
  },
  {
    key: "wandBlizzard",
    moveset: "wand",
    name: "吹雪",
    icon: "吹",
    verb: "照準地点に吹雪を起こし、しばらく冷気を浴びせ続ける",
    tags: ["area", "cold"],
    attack: attack("area", "arcane", "ice"),
    acts: [
      { kind: "ring", n: "s1", anchor: "target" },
      { kind: "ring", n: "s2", anchor: "target" },
      { kind: "ring", n: "s3", anchor: "target" },
      { kind: "ring", n: "s4", anchor: "target" },
    ],
    minDepth: 2,
  },
  {
    key: "wandFireWall",
    moveset: "wand",
    name: "炎の壁",
    icon: "壁",
    verb: "前方に炎の壁を張り、通り道に炎の床を残す",
    tags: ["area", "fire"],
    attack: AREA_FIRE,
    acts: [{ kind: "line", n: "wall", terrain: "fire" }],
  },
  {
    key: "wandArcaneMissile",
    moveset: "wand",
    name: "魔力弾",
    icon: "魔",
    verb: "魔力の弾を扇に 5 発撃つ",
    tags: ["projectile"],
    attack: attack("ranged", "arcane"),
    acts: [{ kind: "shot", n: "missiles" }],
  },
  {
    key: "wandMeteor",
    moveset: "wand",
    name: "隕石",
    icon: "隕",
    verb: "少し遅れてカーソル地点に燃える隕石が落ち、炎の床を残す",
    tags: ["area", "fire"],
    attack: AREA_FIRE,
    acts: [{ kind: "ring", n: "fall", anchor: "target", terrain: "fire" }],
    minDepth: 2,
  },
  {
    key: "wandChain",
    moveset: "wand",
    name: "雷鎖",
    icon: "鎖",
    verb: "カーソルの近くの敵に雷を放ち、近くの敵へ次々と跳ねる",
    tags: ["lightning"],
    attack: attack("area", "arcane", "lightning"),
    acts: [{ kind: "chain", n: "arc", anchor: "target" }],
  },
];

export const GUN_ART_SPECS: readonly ArtSpec[] = [...GUNNER, ...SIDEARM, ...LONGARM, ...CANNON, ...WAND];
