import { attack } from "../../core/element";
import type { ArtSpec } from "./types";

/**
 * 重打・舞の武器技（斧・戦鎚・大盾・拳・チャクラム・扇子）。数値は data/balance/skills/ART/<武器種>.json。
 * 武器種の手触り（docs/ideas/weapon-skills.md の各節）を伸ばす方向で作る
 */

const MELEE = attack("melee", "physical");
const RANGED = attack("ranged", "physical");
const FIRE = attack("melee", "physical", "fire");
const ICE = attack("melee", "physical", "ice");
const LIGHTNING_AREA = attack("area", "physical", "lightning");

// ---- 斧: 出血・投擲。当てるほど出血を重ね、崩す ----
const AXE: readonly ArtSpec[] = [
  {
    key: "axeCleave",
    moveset: "axe",
    name: "大割り",
    icon: "大",
    verb: "前方を大きく振り下ろし、出血させる",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "swing" }],
  },
  {
    key: "axeHatchet",
    moveset: "axe",
    name: "手斧",
    icon: "投",
    verb: "手斧を投げる。壁で跳ね返って戻ってくる",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "toss", shot: "ricochet" }],
  },
  {
    key: "axeWhirl",
    moveset: "axe",
    name: "大車輪",
    icon: "車",
    verb: "斧を車輪のように回し、周りの敵を 3 度斬る",
    tags: ["melee", "area"],
    attack: MELEE,
    acts: [{ kind: "ring", n: "spin" }],
  },
  {
    key: "axeLeap",
    moveset: "axe",
    name: "跳び割り",
    icon: "跳",
    verb: "踏み込んで大きく叩き割る",
    tags: ["melee", "movement"],
    attack: MELEE,
    acts: [{ kind: "dash", n: "leap" }],
  },
  {
    key: "axeRend",
    moveset: "axe",
    name: "裂傷",
    icon: "裂",
    verb: "前方を鋭く裂き、出血を大きく重ねる",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "cut" }],
  },
  {
    key: "axeBerserk",
    moveset: "axe",
    name: "戦狂",
    icon: "狂",
    verb: "戦い狂い、しばらく与ダメが上がって怒気が付く",
    tags: ["buff"],
    attack: null,
    acts: [{ kind: "buff", n: "rage" }],
  },
  {
    key: "axeSunder",
    moveset: "axe",
    name: "叩き崩し",
    icon: "崩",
    verb: "前方を叩き割る。出血している敵には大きく効き、出血を消し去る",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "break", vs: "bleed", consume: true }],
  },
  {
    key: "axeDoubleChop",
    moveset: "axe",
    name: "二連割り",
    icon: "二",
    verb: "続けて 2 度振り下ろす",
    tags: ["melee"],
    attack: MELEE,
    acts: [
      { kind: "arc", n: "c1" },
      { kind: "arc", n: "c2" },
    ],
  },
  {
    key: "axeStorm",
    moveset: "axe",
    name: "斧嵐",
    icon: "嵐",
    verb: "手斧を扇に 3 本投げる",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "fan" }],
  },
  {
    key: "axeFissure",
    moveset: "axe",
    name: "地割れ",
    icon: "地",
    verb: "斧を叩き込んで地面を割り、瓦礫を残す",
    tags: ["melee", "area"],
    attack: MELEE,
    acts: [{ kind: "ring", n: "crack", terrain: "rubble" }],
    minDepth: 2,
  },
  {
    key: "axeHowl",
    moveset: "axe",
    name: "雄叫び",
    icon: "咆",
    verb: "雄叫びを上げ、周りの敵を怯えさせる",
    tags: ["area"],
    attack: null,
    acts: [{ kind: "ring", n: "shout" }],
  },
];

// ---- 戦鎚: 遅く重い・衝撃波。低い手数の代わりに崩す力が強い ----
const HAMMER: readonly ArtSpec[] = [
  {
    key: "hammerSmash",
    moveset: "hammer",
    name: "大打撃",
    icon: "大",
    verb: "渾身の一撃を叩き込む",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "hit" }],
  },
  {
    key: "hammerQuake",
    moveset: "hammer",
    name: "地震",
    icon: "震",
    verb: "地面を叩いて周りを揺らし、瓦礫を残す",
    tags: ["melee", "area"],
    attack: MELEE,
    acts: [{ kind: "ring", n: "shake", terrain: "rubble" }],
    minDepth: 2,
  },
  {
    key: "hammerMeteor",
    moveset: "hammer",
    name: "天墜",
    icon: "天",
    verb: "跳び上がり、落下の勢いで叩きつける",
    tags: ["melee", "movement"],
    attack: MELEE,
    acts: [{ kind: "dash", n: "fall" }],
  },
  {
    key: "hammerSpin",
    moveset: "hammer",
    name: "旋回打",
    icon: "旋",
    verb: "鎚を振り回し、周りを 3 度打つ",
    tags: ["melee", "area"],
    attack: MELEE,
    acts: [{ kind: "ring", n: "spin" }],
  },
  {
    key: "hammerThrow",
    moveset: "hammer",
    name: "鎚投げ",
    icon: "投",
    verb: "鎚を投げる。壁で跳ね返って戻ってくる",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "toss", shot: "ricochet" }],
  },
  {
    key: "hammerShatter",
    moveset: "hammer",
    name: "砕破",
    icon: "砕",
    verb: "叩き砕く。冷気を帯びた敵には大きく効く",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "break", vs: "chill" }],
  },
  {
    key: "hammerBell",
    moveset: "hammer",
    name: "鐘打ち",
    icon: "鐘",
    verb: "鐘のように打ち鳴らし、敵を麻痺させる",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "toll" }],
  },
  {
    key: "hammerFissure",
    moveset: "hammer",
    name: "地割り",
    icon: "裂",
    verb: "前方の地面を割って進み、瓦礫を残す",
    tags: ["melee", "area"],
    attack: MELEE,
    acts: [{ kind: "line", n: "split", terrain: "rubble" }],
    minDepth: 2,
  },
  {
    key: "hammerCharge",
    moveset: "hammer",
    name: "鉄槌突進",
    icon: "突",
    verb: "鎚を構えて重く突進する",
    tags: ["melee", "movement"],
    attack: MELEE,
    acts: [{ kind: "dash", n: "charge" }],
  },
  {
    key: "hammerBreak",
    moveset: "hammer",
    name: "打ち崩し",
    icon: "崩",
    verb: "前方を打ち据え、崩勢を負わせる",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "crush" }],
  },
  {
    key: "hammerThunder",
    moveset: "hammer",
    name: "雷鎚",
    icon: "雷",
    verb: "鎚に雷をまとわせ、カーソル地点へ叩き込む",
    tags: ["area", "lightning"],
    attack: LIGHTNING_AREA,
    acts: [{ kind: "ring", n: "bolt", anchor: "target" }],
    minDepth: 2,
  },
];

// ---- 大盾: 押す・守る。低威力の代わりに押し返しと守りが強い ----
const SHIELD: readonly ArtSpec[] = [
  {
    key: "shieldBash",
    moveset: "shield",
    name: "盾打ち",
    icon: "打",
    verb: "盾で前方を打ち、大きく怯ませる",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "bash" }],
  },
  {
    key: "shieldCharge",
    moveset: "shield",
    name: "盾突進",
    icon: "突",
    verb: "盾を構えて前方へ突進する",
    tags: ["melee", "movement"],
    attack: MELEE,
    acts: [{ kind: "dash", n: "rush" }],
  },
  {
    key: "shieldFortress",
    moveset: "shield",
    name: "鉄壁",
    icon: "鉄",
    verb: "盾を構え、しばらく攻撃を受けず身を固める",
    tags: ["buff", "defense"],
    attack: null,
    acts: [{ kind: "buff", n: "wall" }],
  },
  {
    key: "shieldSlam",
    moveset: "shield",
    name: "盾落とし",
    icon: "落",
    verb: "盾を高く掲げ、大きく打ち下ろす",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "drop" }],
  },
  {
    key: "shieldThrow",
    moveset: "shield",
    name: "盾投げ",
    icon: "投",
    verb: "盾を投げる。壁で跳ね返って戻ってくる",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "toss", shot: "ricochet" }],
  },
  {
    key: "shieldReflect",
    moveset: "shield",
    name: "反射",
    icon: "反",
    verb: "盾を構えて周りの敵弾を消す",
    tags: ["defense", "area"],
    attack: MELEE,
    acts: [{ kind: "ring", n: "guard", clearsBullets: true }],
  },
  {
    key: "shieldTaunt",
    moveset: "shield",
    name: "挑発",
    icon: "挑",
    verb: "盾を叩いて周りの敵を引き寄せ、弱らせる",
    tags: ["area"],
    attack: null,
    acts: [{ kind: "pull", n: "gather" }],
  },
  {
    key: "shieldQuake",
    moveset: "shield",
    name: "盾震",
    icon: "震",
    verb: "盾でカーソル地点を打ち、地を震わせる",
    tags: ["melee", "area"],
    attack: MELEE,
    acts: [{ kind: "ring", n: "shake", anchor: "target" }],
    minDepth: 2,
  },
  {
    key: "shieldShove",
    moveset: "shield",
    name: "押し込み",
    icon: "押",
    verb: "盾で前方を広く押し込む",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "push" }],
  },
  {
    key: "shieldBulwark",
    moveset: "shield",
    name: "城壁",
    icon: "城",
    verb: "身を固めて生命を少し取り戻す",
    tags: ["buff", "defense"],
    attack: null,
    acts: [{ kind: "buff", n: "wall2" }],
  },
  {
    key: "shieldCounter",
    moveset: "shield",
    name: "盾返し",
    icon: "返",
    verb: "一瞬だけ攻撃を受けない構えを取り、盾で押し返す",
    tags: ["melee", "defense"],
    attack: MELEE,
    acts: [
      { kind: "buff", n: "guard" },
      { kind: "arc", n: "counter" },
    ],
  },
];

// ---- 拳: 至近の連打・投げ。手数が多く隙が少ない ----
const FISTS: readonly ArtSpec[] = [
  {
    key: "fistsRapidPunch",
    moveset: "fists",
    name: "乱撃拳",
    icon: "連",
    verb: "至近を素早く 4 回連打する",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "punch" }],
  },
  {
    key: "fistsUppercut",
    moveset: "fists",
    name: "昇拳",
    icon: "昇",
    verb: "下から打ち上げて大きく怯ませ、壁に叩きつける",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "up" }],
  },
  {
    key: "fistsDashStraight",
    moveset: "fists",
    name: "踏込み突き",
    icon: "踏",
    verb: "踏み込んで真っすぐ突く",
    tags: ["melee", "movement"],
    attack: MELEE,
    acts: [{ kind: "dash", n: "straight" }],
  },
  {
    key: "fistsGroundPound",
    moveset: "fists",
    name: "地砕き",
    icon: "砕",
    verb: "拳で地面を砕き、瓦礫を残す",
    tags: ["melee", "area"],
    attack: MELEE,
    acts: [{ kind: "ring", n: "pound", terrain: "rubble" }],
    minDepth: 2,
  },
  {
    key: "fistsKiBlast",
    moveset: "fists",
    name: "気弾",
    icon: "気",
    verb: "気を練った弾を撃つ",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "blast" }],
  },
  {
    key: "fistsCounterStance",
    moveset: "fists",
    name: "見切りの構え",
    icon: "見",
    verb: "一瞬だけ攻撃を受けない構えを取り、周りへ反撃する",
    tags: ["melee", "defense"],
    attack: MELEE,
    acts: [
      { kind: "buff", n: "stance" },
      { kind: "ring", n: "counter" },
    ],
  },
  {
    key: "fistsSpinKick",
    moveset: "fists",
    name: "旋風脚",
    icon: "旋",
    verb: "回転して周りを 3 度蹴る",
    tags: ["melee", "area"],
    attack: MELEE,
    acts: [{ kind: "ring", n: "spin" }],
  },
  {
    key: "fistsPalm",
    moveset: "fists",
    name: "発勁",
    icon: "発",
    verb: "気をため、前方へ大きく打ち出して吹き飛ばす",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "palm" }],
  },
  {
    key: "fistsFocus",
    moveset: "fists",
    name: "練気",
    icon: "練",
    verb: "気を練り、しばらく与ダメが上がって気力を取り戻す",
    tags: ["buff"],
    attack: null,
    acts: [{ kind: "buff", n: "focus" }],
  },
  {
    key: "fistsFlyingKnee",
    moveset: "fists",
    name: "飛び膝",
    icon: "飛",
    verb: "跳び込んで膝を打ち込む",
    tags: ["melee", "movement"],
    attack: MELEE,
    acts: [{ kind: "dash", n: "knee" }],
  },
  {
    key: "fistsHundredFist",
    moveset: "fists",
    name: "百烈拳",
    icon: "百",
    verb: "前方の帯へ 8 連打を叩き込む",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "barrage" }],
    minDepth: 2,
  },
];

// ---- チャクラム: 速く広い斬り・周回。輪の刃で周りを薙ぐ ----
const RING_BLADES: readonly ArtSpec[] = [
  {
    key: "ringBladesThrow",
    moveset: "ringBlades",
    name: "双輪投げ",
    icon: "大",
    verb: "輪を大きく投げ、貫いて壁で跳ね返る",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "throw", shot: "ricochet" }],
  },
  {
    key: "ringBladesOrbit",
    moveset: "ringBlades",
    name: "周回刃",
    icon: "周",
    verb: "輪を自分の周りに回し、3 度斬る",
    tags: ["melee", "area"],
    attack: MELEE,
    acts: [{ kind: "ring", n: "orbit" }],
  },
  {
    key: "ringBladesDance",
    moveset: "ringBlades",
    name: "双輪舞",
    icon: "舞",
    verb: "大きく舞って周りを薙ぐ",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "dance" }],
  },
  {
    key: "ringBladesCross",
    moveset: "ringBlades",
    name: "交差",
    icon: "差",
    verb: "2 枚の輪を交差させて斬る",
    tags: ["melee"],
    attack: MELEE,
    acts: [
      { kind: "arc", n: "x1" },
      { kind: "arc", n: "x2" },
    ],
  },
  {
    key: "ringBladesSaw",
    moveset: "ringBlades",
    name: "回転鋸",
    icon: "鋸",
    verb: "輪を鋸のように回して帯を刻み、出血させる",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "saw" }],
  },
  {
    key: "ringBladesStorm",
    moveset: "ringBlades",
    name: "刃の嵐",
    icon: "嵐",
    verb: "全方位へ刃の嵐を起こす",
    tags: ["melee", "area"],
    attack: MELEE,
    acts: [{ kind: "ring", n: "storm" }],
    minDepth: 2,
  },
  {
    key: "ringBladesDoubleSlash",
    moveset: "ringBlades",
    name: "二連輪",
    icon: "二",
    verb: "輪を続けて 2 度振るう",
    tags: ["melee", "area"],
    attack: MELEE,
    acts: [
      { kind: "ring", n: "r1" },
      { kind: "ring", n: "r2" },
    ],
  },
  {
    key: "ringBladesRebound",
    moveset: "ringBlades",
    name: "返し刃",
    icon: "跳",
    verb: "輪を投げる。壁で跳ね返って戻ってくる",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "rebound", shot: "ricochet" }],
  },
  {
    key: "ringBladesShield",
    moveset: "ringBlades",
    name: "輪の盾",
    icon: "盾",
    verb: "輪を周りに回して敵弾を消す",
    tags: ["defense", "area"],
    attack: MELEE,
    acts: [{ kind: "ring", n: "guard", clearsBullets: true }],
  },
  {
    key: "ringBladesReap",
    moveset: "ringBlades",
    name: "刈り輪",
    icon: "刈",
    verb: "輪で前方を刈り、出血を重ねる",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "reap" }],
  },
  {
    key: "ringBladesVortex",
    moveset: "ringBlades",
    name: "渦輪",
    icon: "渦",
    verb: "カーソル地点に輪の渦を起こし、敵を引き寄せて斬る",
    tags: ["area"],
    attack: MELEE,
    acts: [{ kind: "pull", n: "vortex", anchor: "target" }],
    minDepth: 2,
  },
];

// ---- 扇子: 押し返す・風・地形。低威力の代わりに間合いと属性の舞に長ける ----
const FAN: readonly ArtSpec[] = [
  {
    key: "fanGust",
    moveset: "fan",
    name: "突風",
    icon: "突",
    verb: "扇で突風を起こし、押し返して敵弾を消す",
    tags: ["melee", "defense"],
    attack: MELEE,
    acts: [{ kind: "line", n: "gust", clearsBullets: true }],
  },
  {
    key: "fanTornado",
    moveset: "fan",
    name: "竜巻",
    icon: "竜",
    verb: "カーソル地点に竜巻を起こし、引き寄せて 4 度斬る",
    tags: ["area"],
    attack: MELEE,
    acts: [
      { kind: "pull", n: "gather", anchor: "target" },
      { kind: "ring", n: "t1", anchor: "target" },
      { kind: "ring", n: "t2", anchor: "target" },
      { kind: "ring", n: "t3", anchor: "target" },
    ],
    minDepth: 2,
  },
  {
    key: "fanPetals",
    moveset: "fan",
    name: "花吹雪",
    icon: "花",
    verb: "花びらを 7 枚まとめて散らす",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "petals" }],
  },
  {
    key: "fanDance",
    moveset: "fan",
    name: "舞い",
    icon: "舞",
    verb: "扇を広げて舞い、周りを打って足を速める",
    tags: ["melee", "buff"],
    attack: MELEE,
    acts: [
      { kind: "ring", n: "spin" },
      { kind: "buff", n: "swift" },
    ],
  },
  {
    key: "fanFlameDance",
    moveset: "fan",
    name: "炎の舞",
    icon: "炎",
    verb: "扇に炎をまとわせて舞い、燃やす",
    tags: ["melee", "fire"],
    attack: FIRE,
    acts: [{ kind: "arc", n: "flame" }],
  },
  {
    key: "fanSnowDance",
    moveset: "fan",
    name: "雪舞",
    icon: "雪",
    verb: "扇に冷気をまとわせて舞い、凍えさせる",
    tags: ["melee", "cold"],
    attack: ICE,
    acts: [{ kind: "arc", n: "snow" }],
  },
  {
    key: "fanWindShield",
    moveset: "fan",
    name: "風の盾",
    icon: "盾",
    verb: "風の盾を広げ、周りの敵弾を消す",
    tags: ["defense", "area"],
    attack: MELEE,
    acts: [{ kind: "ring", n: "shield", clearsBullets: true }],
  },
  {
    key: "fanWindStep",
    moveset: "fan",
    name: "風歩",
    icon: "歩",
    verb: "風に乗って踏み込む。踏み込む間は攻撃を受けない",
    tags: ["movement", "defense"],
    attack: null,
    acts: [{ kind: "dash", n: "step" }],
  },
  {
    key: "fanInhale",
    moveset: "fan",
    name: "吸い風",
    icon: "吸",
    verb: "扇で風を吸い込み、周りの敵を引き寄せる",
    tags: ["area"],
    attack: MELEE,
    acts: [{ kind: "pull", n: "inhale" }],
  },
  {
    key: "fanRazorWind",
    moveset: "fan",
    name: "鎌鼬",
    icon: "鎌",
    verb: "鎌鼬の刃風を放ち、貫いて出血させる",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "razor" }],
  },
  {
    key: "fanCalm",
    moveset: "fan",
    name: "凪",
    icon: "凪",
    verb: "呼吸を静め、生命と気力を少し取り戻す",
    tags: ["buff"],
    attack: null,
    acts: [{ kind: "buff", n: "calm" }],
  },
];

export const HEAVY_ART_SPECS: readonly ArtSpec[] = [...AXE, ...HAMMER, ...SHIELD, ...FISTS, ...RING_BLADES, ...FAN];
