/**
 * 技（skills/arts/）の key。依存を持たない（skills/types.ts の SKILL_KEYS がここを取り込むため）。
 * 武器技の key は `<武器種の key><名前>`（skills/arts/arts.test.ts が武器種ごとに 10 種以上・接頭辞を検査する）。
 * 足すときは配列の末尾へ（既存の順は抽選の並びに効く）。一覧と狙いは docs/ideas/weapon-skills.md
 */

/** 共通技（どの武器種でも撃てる） */
export const COMMON_ART_KEYS = [
  "commonShockwave",
  "commonBackstep",
  "commonBlink",
  "commonWarCry",
  "commonFirstAid",
  "commonMeditate",
  "commonFireball",
  "commonIceLance",
  "commonThunderclap",
  "commonPoisonMist",
  "commonShadowBolt",
  "commonHolyNova",
  "commonChainSpark",
  "commonMagnet",
  "commonSmokeBomb",
  "commonKnifeFan",
  "commonMeteor",
  "commonQuickstep",
  "commonIronSkin",
  "commonExecution",
  "commonBarrage",
  "commonGroundSpike",
  "commonFrostNova",
  "commonBloodSurge",
] as const;

/** 武器技（武器種ごと。その武器種を装備しているときだけ撃てる） */
export const WEAPON_ART_KEYS = {
  sword: [
    "swordCrossCut",
    "swordRisingSlash",
    "swordFlashStep",
    "swordWhirlwind",
    "swordSonicEdge",
    "swordRiposte",
    "swordTripleThrust",
    "swordHeavenSplit",
    "swordBladeStorm",
    "swordValor",
    "swordFinisher",
  ],
  greatsword: [
    "greatswordEarthCleave",
    "greatswordGiantSwing",
    "greatswordLeapSlam",
    "greatswordCrescent",
    "greatswordGuardBreak",
    "greatswordWindCutter",
    "greatswordRampage",
    "greatswordIronWill",
    "greatswordBeheader",
    "greatswordSwordPressure",
    "greatswordBoarRush",
  ],
  twinBlades: [
    "twinBladesBladeDance",
    "twinBladesShadowRush",
    "twinBladesCrossThrow",
    "twinBladesFlurry",
    "twinBladesBleedEdge",
    "twinBladesVenomKiss",
    "twinBladesBackstab",
    "twinBladesWhirlDash",
    "twinBladesAfterimage",
    "twinBladesReap",
    "twinBladesTempest",
  ],
  spear: [
    "spearPierce",
    "spearVault",
    "spearSweep",
    "spearRain",
    "spearHurl",
    "spearCharge",
    "spearWall",
    "spearTwinStrike",
    "spearImpale",
    "spearCyclone",
    "spearPin",
  ],
  scythe: [
    "scytheReap",
    "scytheSoulHarvest",
    "scytheDeathSpin",
    "scytheGrimPull",
    "scytheCurse",
    "scytheHarvestMoon",
    "scytheBeheader",
    "scytheShadowStep",
    "scytheWither",
    "scytheTerror",
    "scytheBloodMoon",
  ],
  fists: [
    "fistsRapidPunch",
    "fistsUppercut",
    "fistsDashStraight",
    "fistsGroundPound",
    "fistsKiBlast",
    "fistsCounterStance",
    "fistsSpinKick",
    "fistsPalm",
    "fistsFocus",
    "fistsFlyingKnee",
    "fistsHundredFist",
  ],
  whip: [
    "whipLash",
    "whipCrack",
    "whipSnare",
    "whipCircle",
    "whipChainLightning",
    "whipDoubleLash",
    "whipTame",
    "whipStorm",
    "whipSwingAway",
    "whipDisarm",
    "whipSpark",
  ],
  cleaver: [
    "cleaverChop",
    "cleaverHack",
    "cleaverThrow",
    "cleaverButcher",
    "cleaverShoulder",
    "cleaverQuake",
    "cleaverBerserk",
    "cleaverSever",
    "cleaverWhirl",
    "cleaverBoneCrush",
    "cleaverRend",
  ],
  staff: [
    "staffSweep",
    "staffPoleVault",
    "staffThrust",
    "staffWindmill",
    "staffDeflect",
    "staffBreath",
    "staffTrip",
    "staffCombo",
    "staffSlam",
    "staffGuard",
    "staffGale",
  ],
  wand: [
    "wandFlare",
    "wandFrostBolt",
    "wandLightning",
    "wandVenom",
    "wandVortex",
    "wandHolyRay",
    "wandDarkOrb",
    "wandBlizzard",
    "wandFireWall",
    "wandArcaneMissile",
    "wandMeteor",
    "wandChain",
  ],
  katana: [
    "katanaIai",
    "katanaFlash",
    "katanaCrescent",
    "katanaTripleIai",
    "katanaCounter",
    "katanaWindSlash",
    "katanaBlossom",
    "katanaDrawCircle",
    "katanaThousandCuts",
    "katanaClearMind",
    "katanaSever",
  ],
  axe: [
    "axeCleave",
    "axeHatchet",
    "axeWhirl",
    "axeLeap",
    "axeRend",
    "axeBerserk",
    "axeSunder",
    "axeDoubleChop",
    "axeStorm",
    "axeFissure",
    "axeHowl",
  ],
  shield: [
    "shieldBash",
    "shieldCharge",
    "shieldFortress",
    "shieldSlam",
    "shieldThrow",
    "shieldReflect",
    "shieldTaunt",
    "shieldQuake",
    "shieldShove",
    "shieldBulwark",
    "shieldCounter",
  ],
  chainSickle: [
    "chainSickleHook",
    "chainSickleWhirl",
    "chainSickleBind",
    "chainSickleReap",
    "chainSickleSwing",
    "chainSickleFlurry",
    "chainSickleChainThrow",
    "chainSickleWeight",
    "chainSickleTopple",
    "chainSickleShadowStitch",
    "chainSickleSpiral",
  ],
  hammer: [
    "hammerSmash",
    "hammerQuake",
    "hammerMeteor",
    "hammerSpin",
    "hammerThrow",
    "hammerShatter",
    "hammerBell",
    "hammerFissure",
    "hammerCharge",
    "hammerBreak",
    "hammerThunder",
  ],
  gunner: [
    "gunnerFanFire",
    "gunnerBulletDance",
    "gunnerDiveShot",
    "gunnerDoubleTap",
    "gunnerRicochet",
    "gunnerBarrage",
    "gunnerPistolWhip",
    "gunnerBlast",
    "gunnerBackflip",
    "gunnerTrickShot",
    "gunnerQuickDraw",
  ],
  sidearm: [
    "sidearmSnipe",
    "sidearmQuickdraw",
    "sidearmFlash",
    "sidearmRoll",
    "sidearmPiercer",
    "sidearmIncendiary",
    "sidearmFreeze",
    "sidearmShock",
    "sidearmMark",
    "sidearmSteady",
    "sidearmScatter",
  ],
  longarm: [
    "longarmSnipe",
    "longarmBayonet",
    "longarmVolley",
    "longarmHeadshot",
    "longarmRecoilJump",
    "longarmRail",
    "longarmFlare",
    "longarmButtStroke",
    "longarmSuppress",
    "longarmExplosive",
    "longarmAim",
  ],
  cannon: [
    "cannonBlast",
    "cannonGrapeshot",
    "cannonRecoil",
    "cannonBarrage",
    "cannonShockwave",
    "cannonNapalm",
    "cannonChainShot",
    "cannonPointBlank",
    "cannonMortar",
    "cannonFrost",
    "cannonDetonate",
  ],
  thrown: [
    "thrownFan",
    "thrownPoison",
    "thrownRain",
    "thrownRicochet",
    "thrownVolley",
    "thrownPin",
    "thrownSmoke",
    "thrownBomb",
    "thrownBola",
    "thrownCaltrops",
    "thrownDagger",
  ],
  grenade: [
    "grenadeCluster",
    "grenadeFrag",
    "grenadeIncendiary",
    "grenadeSmoke",
    "grenadeConcussion",
    "grenadeGas",
    "grenadeFlash",
    "grenadeFreeze",
    "grenadeBarrage",
    "grenadeSticky",
    "grenadeBounce",
  ],
  trapper: [
    "trapperDetonate",
    "trapperSpike",
    "trapperNet",
    "trapperTripwire",
    "trapperBearTrap",
    "trapperLure",
    "trapperOil",
    "trapperFire",
    "trapperSmoke",
    "trapperShrapnel",
    "trapperCaltrops",
  ],
  warRing: [
    "warRingSpin",
    "warRingThrow",
    "warRingRicochet",
    "warRingFan",
    "warRingGuard",
    "warRingStorm",
    "warRingDash",
    "warRingSever",
    "warRingEcho",
    "warRingSlash",
    "warRingCyclone",
  ],
  claws: [
    "clawsRend",
    "clawsPounce",
    "clawsFrenzy",
    "clawsSpin",
    "clawsHemorrhage",
    "clawsLeapBack",
    "clawsShred",
    "clawsBeast",
    "clawsSlashWave",
    "clawsDive",
    "clawsVenom",
  ],
  flail: [
    "flailSpin",
    "flailSmash",
    "flailSweep",
    "flailHurl",
    "flailWreck",
    "flailChainPull",
    "flailDrop",
    "flailCrush",
    "flailOrbit",
    "flailPound",
    "flailStun",
  ],
  ringBlades: [
    "ringBladesThrow",
    "ringBladesOrbit",
    "ringBladesDance",
    "ringBladesCross",
    "ringBladesSaw",
    "ringBladesStorm",
    "ringBladesDoubleSlash",
    "ringBladesRebound",
    "ringBladesShield",
    "ringBladesReap",
    "ringBladesVortex",
  ],
  fan: [
    "fanGust",
    "fanTornado",
    "fanPetals",
    "fanDance",
    "fanFlameDance",
    "fanSnowDance",
    "fanWindShield",
    "fanWindStep",
    "fanInhale",
    "fanRazorWind",
    "fanCalm",
  ],
} as const;

type WeaponArtTable = typeof WEAPON_ART_KEYS;
export type WeaponArtMoveset = keyof WeaponArtTable;
export type WeaponArtKey = WeaponArtTable[WeaponArtMoveset][number];
export type CommonArtKey = (typeof COMMON_ART_KEYS)[number];

/** 武器技の武器種の並び（MOVESET_KEYS と同じ順。arts.test.ts が一致を検査する） */
export const WEAPON_ART_MOVESETS = Object.keys(WEAPON_ART_KEYS) as WeaponArtMoveset[];

export const ART_SKILL_KEYS = [...COMMON_ART_KEYS, ...WEAPON_ART_MOVESETS.flatMap((m) => WEAPON_ART_KEYS[m])] as readonly (CommonArtKey | WeaponArtKey)[];
export type ArtSkillKey = CommonArtKey | WeaponArtKey;
