/**
 * 技（skills/arts/）の key。依存を持たない（skills/types.ts の SKILL_KEYS がここを取り込むため）。
 * 段取り 7c で武器技 298 を共通技へ束ね、技は武器種の縛りの無い共通技 60 だけになった（旧 key の写しは skills/legacyKeys.ts）。
 * 形は今の武器の型で変わる（skills/arts/transform.ts）。足すときは配列の末尾へ（既存の順は抽選の並びに効く）
 */

/** 共通技（どの武器種でも撃てる）。前半 24 は skills/arts/common.ts、後半 36 は common2.ts */
export const COMMON_ART_KEYS = [
  "commonShockwave",
  "commonBackstep",
  "commonBlink",
  "commonWarCry",
  "commonFirstAid",
  "commonMeditate",
  "commonFireball",
  "commonIceLance",
  "commonThunderclap",
  "commonPoisonMist",
  "commonShadowBolt",
  "commonHolyNova",
  "commonChainSpark",
  "commonMagnet",
  "commonSmokeBomb",
  "commonKnifeFan",
  "commonMeteor",
  "commonQuickstep",
  "commonIronSkin",
  "commonExecution",
  "commonBarrage",
  "commonGroundSpike",
  "commonFrostNova",
  "commonBloodSurge",
  "commonWindCutter",
  "commonRicochet",
  "commonScatter",
  "commonKiBlast",
  "commonVenomDart",
  "commonWhirl",
  "commonTremor",
  "commonDeflect",
  "commonSmokeScreen",
  "commonPierce",
  "commonQuake",
  "commonRailshot",
  "commonFireWall",
  "commonShove",
  "commonCrescent",
  "commonBleedEdge",
  "commonRisingSlash",
  "commonFlurry",
  "commonBomb",
  "commonFreezeBomb",
  "commonFlashBang",
  "commonLunge",
  "commonCharge",
  "commonThousandCuts",
  "commonTriplePound",
  "commonInhale",
  "commonTripleThrust",
  "commonLeapSlam",
  "commonDiveShot",
  "commonRiposte",
  "commonHack",
  "commonMeteorDive",
  "commonDetonate",
  "commonCrossCut",
  "commonBackstab",
  "commonStrikeAway",
] as const;

export type ArtSkillKey = (typeof COMMON_ART_KEYS)[number];

export const ART_SKILL_KEYS: readonly ArtSkillKey[] = COMMON_ART_KEYS;
