import { attack } from "../../core/element";
import type { ArtSpec } from "./types";

/**
 * 長柄・鎖の武器技（槍・大鎌・棍・鎖鎌・鞭・チェーンアレイ）。数値は data/balance/skills/ART/<武器種>.json。
 * 武器種の手触り（docs/ideas/weapon-skills.md の各節）を伸ばす方向で作る
 */

const MELEE = attack("melee", "physical");
const RANGED = attack("ranged", "physical");
const AREA = attack("area", "physical");

// ---- 槍: 長い突き・穂先。単体の貫通と間合い管理 ----
const SPEAR: readonly ArtSpec[] = [
  {
    key: "spearPierce",
    moveset: "spear",
    name: "貫通突き",
    icon: "貫",
    verb: "長く踏み込んで穂先を突き通す",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "thrust" }],
  },
  {
    key: "spearVault",
    moveset: "spear",
    name: "棒高跳び",
    icon: "跳",
    verb: "石突きで跳び、着地の衝撃で周りを打つ。跳ぶ間は攻撃を受けない",
    tags: ["melee", "movement"],
    attack: MELEE,
    acts: [
      { kind: "dash", n: "leap" },
      { kind: "ring", n: "land" },
    ],
  },
  {
    key: "spearSweep",
    moveset: "spear",
    name: "石突き払い",
    icon: "払",
    verb: "石突きで足元を大きく払い、周りを押し返す",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "butt" }],
  },
  {
    key: "spearRain",
    moveset: "spear",
    name: "槍の雨",
    icon: "雨",
    verb: "カーソル地点に穂先が 3 本続けて降り注ぐ",
    tags: ["area"],
    attack: AREA,
    acts: [
      { kind: "ring", n: "s1", anchor: "target" },
      { kind: "ring", n: "s2", anchor: "target" },
      { kind: "ring", n: "s3", anchor: "target" },
    ],
    minDepth: 2,
  },
  {
    key: "spearHurl",
    moveset: "spear",
    name: "投槍",
    icon: "投",
    verb: "槍を投げ、並んだ敵を貫く",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "javelin" }],
  },
  {
    key: "spearCharge",
    moveset: "spear",
    name: "突撃",
    icon: "突",
    verb: "低く構えて照準の方向へ突進し、通り道の敵を貫く",
    tags: ["melee", "movement"],
    attack: MELEE,
    acts: [{ kind: "dash", n: "rush" }],
  },
  {
    key: "spearWall",
    moveset: "spear",
    name: "槍衾",
    icon: "衾",
    verb: "正面と左右へ同時に穂先を突き出す",
    tags: ["melee"],
    attack: MELEE,
    acts: [
      { kind: "line", n: "c" },
      { kind: "line", n: "l" },
      { kind: "line", n: "r" },
    ],
  },
  {
    key: "spearTwinStrike",
    moveset: "spear",
    name: "二段突き",
    icon: "双",
    verb: "続けて 2 度、深く突く",
    tags: ["melee"],
    attack: MELEE,
    acts: [
      { kind: "line", n: "t1" },
      { kind: "line", n: "t2" },
    ],
  },
  {
    key: "spearImpale",
    moveset: "spear",
    name: "串刺し",
    icon: "串",
    verb: "深く突き通し、敵を脆くする",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "run" }],
    minDepth: 2,
  },
  {
    key: "spearCyclone",
    moveset: "spear",
    name: "旋槍",
    icon: "旋",
    verb: "その場で槍を旋回させ、周りを 3 度打つ",
    tags: ["melee", "area"],
    attack: MELEE,
    acts: [{ kind: "ring", n: "spin" }],
  },
  {
    key: "spearPin",
    moveset: "spear",
    name: "縫い止め",
    icon: "縫",
    verb: "深く突き、敵の動きを縫い止める",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "nail" }],
  },
];

// ---- 大鎌: 引き寄せ・闇。広い弧と状態異常で削る ----
const MELEE_DARK = attack("melee", "hybrid", "dark");
const AREA_DARK = attack("area", "hybrid", "dark");
const RANGED_DARK = attack("ranged", "hybrid", "dark");

const SCYTHE: readonly ArtSpec[] = [
  {
    key: "scytheReap",
    moveset: "scythe",
    name: "死神刈り",
    icon: "刈",
    verb: "270° の大きな弧で周りを刈り取る",
    tags: ["melee", "area"],
    attack: MELEE_DARK,
    acts: [{ kind: "arc", n: "sweep" }],
  },
  {
    key: "scytheSoulHarvest",
    moveset: "scythe",
    name: "魂刈り",
    icon: "魂",
    verb: "刈った魂で生命を少し取り戻す",
    tags: ["melee", "buff"],
    attack: MELEE_DARK,
    acts: [
      { kind: "arc", n: "cut" },
      { kind: "buff", n: "drain" },
    ],
  },
  {
    key: "scytheDeathSpin",
    moveset: "scythe",
    name: "死の旋回",
    icon: "旋",
    verb: "鎌を旋回させ、周りを 4 度刈る",
    tags: ["melee", "area"],
    attack: MELEE_DARK,
    acts: [{ kind: "ring", n: "spin" }],
  },
  {
    key: "scytheGrimPull",
    moveset: "scythe",
    name: "引き鎌",
    icon: "引",
    verb: "カーソル地点へ周りの敵を引き寄せて刈る",
    tags: ["area"],
    attack: AREA_DARK,
    acts: [{ kind: "pull", n: "pull", anchor: "target" }],
    minDepth: 2,
  },
  {
    key: "scytheCurse",
    moveset: "scythe",
    name: "呪詛",
    icon: "呪",
    verb: "闇の弾を放ち、当てた敵を弱らせ死を宣告する",
    tags: ["projectile"],
    attack: RANGED_DARK,
    acts: [{ kind: "shot", n: "bolt" }],
  },
  {
    key: "scytheHarvestMoon",
    moveset: "scythe",
    name: "刈月",
    icon: "月",
    verb: "三日月形の刃を飛ばし、並んだ敵を貫く",
    tags: ["projectile"],
    attack: RANGED_DARK,
    acts: [{ kind: "shot", n: "moon" }],
  },
  {
    key: "scytheBeheader",
    moveset: "scythe",
    name: "首刈り",
    icon: "首",
    verb: "首筋を狙って刈り、弱った敵（ボスを除く）は仕留める",
    tags: ["melee"],
    attack: MELEE_DARK,
    acts: [{ kind: "arc", n: "cut" }],
  },
  {
    key: "scytheShadowStep",
    moveset: "scythe",
    name: "影歩み",
    icon: "影",
    verb: "闇に紛れて跳び、着地点に闇の円を広げる",
    tags: ["melee", "movement"],
    attack: MELEE_DARK,
    acts: [
      { kind: "blink", n: "step", anchor: "target" },
      { kind: "ring", n: "burst" },
    ],
  },
  {
    key: "scytheWither",
    moveset: "scythe",
    name: "枯死",
    icon: "枯",
    verb: "周りを腐らせ、腐食と毒を重ねる",
    tags: ["area"],
    attack: AREA_DARK,
    acts: [{ kind: "ring", n: "rot" }],
  },
  {
    key: "scytheTerror",
    moveset: "scythe",
    name: "死神の影",
    icon: "怖",
    verb: "死神の影を見せ、周りの敵を怯えさせる",
    tags: ["area"],
    attack: null,
    acts: [{ kind: "ring", n: "dread" }],
  },
  {
    key: "scytheBloodMoon",
    moveset: "scythe",
    name: "血の月",
    icon: "血",
    verb: "大きく刈り、出血している敵には特に強く効く",
    tags: ["melee"],
    attack: MELEE_DARK,
    acts: [{ kind: "arc", n: "cut", vs: "bleed", consume: true }],
    minDepth: 2,
  },
];

// ---- 棍: 広く薙ぐ・気力。低威力を範囲と資源で補う ----
const STAFF: readonly ArtSpec[] = [
  {
    key: "staffSweep",
    moveset: "staff",
    name: "薙ぎ払い",
    icon: "薙",
    verb: "広く薙いで周りを打つ",
    tags: ["melee", "area"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "wide" }],
  },
  {
    key: "staffPoleVault",
    moveset: "staff",
    name: "棒跳び",
    icon: "跳",
    verb: "棍を突いて跳び、着地の衝撃で周りを打つ。跳ぶ間は攻撃を受けない",
    tags: ["melee", "movement"],
    attack: MELEE,
    acts: [
      { kind: "dash", n: "leap" },
      { kind: "ring", n: "land" },
    ],
  },
  {
    key: "staffThrust",
    moveset: "staff",
    name: "突き込み",
    icon: "込",
    verb: "石突きで鋭く突き込む",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "poke" }],
  },
  {
    key: "staffWindmill",
    moveset: "staff",
    name: "風車",
    icon: "車",
    verb: "棍を風車のように回し、周りを 4 度打つ",
    tags: ["melee", "area"],
    attack: MELEE,
    acts: [{ kind: "ring", n: "spin" }],
  },
  {
    key: "staffDeflect",
    moveset: "staff",
    name: "跳ね返し",
    icon: "弾",
    verb: "棍を振って敵の弾を払い、当たった敵も打つ",
    tags: ["melee", "defense"],
    attack: MELEE,
    acts: [{ kind: "ring", n: "parry", clearsBullets: true }],
  },
  {
    key: "staffBreath",
    moveset: "staff",
    name: "呼吸",
    icon: "息",
    verb: "呼吸を整え、気力を取り戻す",
    tags: ["buff"],
    attack: null,
    acts: [{ kind: "buff", n: "calm" }],
  },
  {
    key: "staffTrip",
    moveset: "staff",
    name: "足払い",
    icon: "払",
    verb: "足元を払い、敵を弱らせる",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "sweep" }],
  },
  {
    key: "staffCombo",
    moveset: "staff",
    name: "連棍",
    icon: "連",
    verb: "棍を 3 連で突き出す",
    tags: ["melee"],
    attack: MELEE,
    acts: [
      { kind: "line", n: "a" },
      { kind: "line", n: "b" },
      { kind: "line", n: "c" },
    ],
  },
  {
    key: "staffSlam",
    moveset: "staff",
    name: "振り下ろし",
    icon: "打",
    verb: "棍を大きく振り下ろし、手前を強く打つ",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "down" }],
    minDepth: 2,
  },
  {
    key: "staffGuard",
    moveset: "staff",
    name: "守りの型",
    icon: "守",
    verb: "身を固めながら棍で押し返す",
    tags: ["area", "defense", "buff"],
    attack: AREA,
    acts: [
      { kind: "ring", n: "push" },
      { kind: "buff", n: "ward" },
    ],
  },
  {
    key: "staffGale",
    moveset: "staff",
    name: "棍風",
    icon: "風",
    verb: "棍を振って幅広い風の塊を飛ばす",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "wind" }],
  },
];

// ---- 鎖鎌: 引き寄せ・崩し。短い間合いを鎖で伸ばす ----
const CHAIN_SICKLE: readonly ArtSpec[] = [
  {
    key: "chainSickleHook",
    moveset: "chainSickle",
    name: "鉤引き",
    icon: "鉤",
    verb: "鎌を投げて敵を引っ掛け、手元まで引き寄せる",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "pull", n: "hook" }],
  },
  {
    key: "chainSickleWhirl",
    moveset: "chainSickle",
    name: "分銅回し",
    icon: "錘",
    verb: "分銅を回し続け、周りを 4 度打つ",
    tags: ["melee", "area"],
    attack: MELEE,
    acts: [{ kind: "ring", n: "spin" }],
  },
  {
    key: "chainSickleBind",
    moveset: "chainSickle",
    name: "鎖縛り",
    icon: "縛",
    verb: "鎖を打ち込み、敵の動きを縛る",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "line" }],
  },
  {
    key: "chainSickleReap",
    moveset: "chainSickle",
    name: "鎌払い",
    icon: "鎌",
    verb: "鎌で払い、傷口から出血させる",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "cut" }],
  },
  {
    key: "chainSickleSwing",
    moveset: "chainSickle",
    name: "振り子",
    icon: "振",
    verb: "鎖を伸ばして照準地点へ振り子のように跳び、着地で鎌を薙ぐ。跳ぶ間は攻撃を受けない",
    tags: ["melee", "movement"],
    attack: MELEE,
    acts: [
      { kind: "blink", n: "leap", anchor: "target" },
      { kind: "ring", n: "cut" },
    ],
  },
  {
    key: "chainSickleFlurry",
    moveset: "chainSickle",
    name: "乱れ鎌",
    icon: "乱",
    verb: "鎌を短く 4 連で振る",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "swing" }],
  },
  {
    key: "chainSickleChainThrow",
    moveset: "chainSickle",
    name: "鎖投げ",
    icon: "鎖",
    verb: "鎖を長く伸ばし、間合いの外まで斬る",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "chain" }],
  },
  {
    key: "chainSickleWeight",
    moveset: "chainSickle",
    name: "分銅打ち",
    icon: "打",
    verb: "分銅を投げつけ、重く打ち据える",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "ball" }],
  },
  {
    key: "chainSickleTopple",
    moveset: "chainSickle",
    name: "引き崩し",
    icon: "崩",
    verb: "鎖で引き寄せて体勢を崩す",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "pull", n: "drag" }],
  },
  {
    key: "chainSickleShadowStitch",
    moveset: "chainSickle",
    name: "影縫い",
    icon: "縫",
    verb: "鎖で影を縫い止め、声を封じる",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "stitch" }],
  },
  {
    key: "chainSickleSpiral",
    moveset: "chainSickle",
    name: "螺旋鎖",
    icon: "螺",
    verb: "カーソル地点で鎖を螺旋に振り、3 度打つ",
    tags: ["area"],
    attack: AREA,
    acts: [
      { kind: "ring", n: "s1", anchor: "target" },
      { kind: "ring", n: "s2", anchor: "target" },
      { kind: "ring", n: "s3", anchor: "target" },
    ],
    minDepth: 2,
  },
];

// ---- 鞭: 先端・雷。細く長い間合いで感電を重ねる ----
const MELEE_LIGHTNING = attack("melee", "physical", "lightning");
const AREA_LIGHTNING = attack("area", "physical", "lightning");

const WHIP: readonly ArtSpec[] = [
  {
    key: "whipLash",
    moveset: "whip",
    name: "雷鞭",
    icon: "鞭",
    verb: "長く伸ばした鞭で先端を叩き込み、感電させる",
    tags: ["melee", "lightning"],
    attack: MELEE_LIGHTNING,
    acts: [{ kind: "line", n: "lash" }],
  },
  {
    key: "whipCrack",
    moveset: "whip",
    name: "炸裂打ち",
    icon: "炸",
    verb: "カーソル地点で鞭の先端を弾けさせる",
    tags: ["area", "lightning"],
    attack: AREA_LIGHTNING,
    acts: [{ kind: "ring", n: "burst", anchor: "target" }],
  },
  {
    key: "whipSnare",
    moveset: "whip",
    name: "絡め取り",
    icon: "絡",
    verb: "鞭を絡めて引き寄せ、動きを止める",
    tags: ["melee"],
    attack: MELEE_LIGHTNING,
    acts: [{ kind: "pull", n: "coil" }],
  },
  {
    key: "whipCircle",
    moveset: "whip",
    name: "円舞鞭",
    icon: "円",
    verb: "鞭を円を描くように振り、周りを 3 度打つ",
    tags: ["melee", "area"],
    attack: MELEE_LIGHTNING,
    acts: [{ kind: "ring", n: "spin" }],
  },
  {
    key: "whipChainLightning",
    moveset: "whip",
    name: "雷連鎖",
    icon: "雷",
    verb: "鞭を伝って雷が近くの敵へ次々と跳ねる",
    tags: ["area", "lightning"],
    attack: AREA_LIGHTNING,
    acts: [{ kind: "chain", n: "arc" }],
  },
  {
    key: "whipDoubleLash",
    moveset: "whip",
    name: "二連打ち",
    icon: "二",
    verb: "続けて 2 度、鞭を打ち込む",
    tags: ["melee"],
    attack: MELEE_LIGHTNING,
    acts: [
      { kind: "line", n: "t1" },
      { kind: "line", n: "t2" },
    ],
  },
  {
    key: "whipTame",
    moveset: "whip",
    name: "調教",
    icon: "調",
    verb: "鞭で打ち据え、恐怖と弱体を刻む",
    tags: ["melee"],
    attack: MELEE_LIGHTNING,
    acts: [{ kind: "line", n: "crack" }],
  },
  {
    key: "whipStorm",
    moveset: "whip",
    name: "雷嵐",
    icon: "嵐",
    verb: "カーソル地点に鞭の雷嵐を 4 度落とす",
    tags: ["area", "lightning"],
    attack: AREA_LIGHTNING,
    acts: [
      { kind: "ring", n: "s1", anchor: "target" },
      { kind: "ring", n: "s2", anchor: "target" },
      { kind: "ring", n: "s3", anchor: "target" },
      { kind: "ring", n: "s4", anchor: "target" },
    ],
    minDepth: 2,
  },
  {
    key: "whipSwingAway",
    moveset: "whip",
    name: "飛び退き打ち",
    icon: "退",
    verb: "後ろへ跳びながら鞭を打つ。跳ぶ間は攻撃を受けない",
    tags: ["melee", "movement"],
    attack: MELEE_LIGHTNING,
    acts: [{ kind: "dash", n: "back" }],
  },
  {
    key: "whipDisarm",
    moveset: "whip",
    name: "武器落とし",
    icon: "落",
    verb: "鞭で武器を弾き、弱らせて声を封じる",
    tags: ["melee"],
    attack: MELEE_LIGHTNING,
    acts: [{ kind: "line", n: "snap" }],
  },
  {
    key: "whipSpark",
    moveset: "whip",
    name: "火花散らし",
    icon: "花",
    verb: "短く鞭を振って火花を散らす",
    tags: ["melee"],
    attack: MELEE_LIGHTNING,
    acts: [{ kind: "arc", n: "fan" }],
  },
];

// ---- チェーンアレイ: 広い範囲・怯み。鎖の鉄球で重く広く打つ ----
const FLAIL: readonly ArtSpec[] = [
  {
    key: "flailSpin",
    moveset: "flail",
    name: "大回転",
    icon: "回",
    verb: "鉄球を大きく回し、周りを 3 度打つ",
    tags: ["melee", "area"],
    attack: MELEE,
    acts: [{ kind: "ring", n: "spin" }],
  },
  {
    key: "flailSmash",
    moveset: "flail",
    name: "叩きつけ",
    icon: "叩",
    verb: "鉄球を大きく振り上げて叩きつける",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "smash" }],
  },
  {
    key: "flailSweep",
    moveset: "flail",
    name: "薙ぎ",
    icon: "薙",
    verb: "鎖を伸ばして広く薙ぐ",
    tags: ["melee", "area"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "wide" }],
  },
  {
    key: "flailHurl",
    moveset: "flail",
    name: "鉄球投げ",
    icon: "鉄",
    verb: "鉄球を投げつけ、並んだ敵を貫く",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "ball" }],
  },
  {
    key: "flailWreck",
    moveset: "flail",
    name: "破城",
    icon: "城",
    verb: "鉄球を抱えて重く突進する",
    tags: ["melee", "movement"],
    attack: MELEE,
    acts: [{ kind: "dash", n: "rush" }],
  },
  {
    key: "flailChainPull",
    moveset: "flail",
    name: "鎖引き",
    icon: "引",
    verb: "鎖で周りの敵を引き寄せる",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "pull", n: "drag" }],
  },
  {
    key: "flailDrop",
    moveset: "flail",
    name: "鉄球落とし",
    icon: "落",
    verb: "カーソル地点へ少し遅れて鉄球が落ちる",
    tags: ["area"],
    attack: AREA,
    acts: [{ kind: "ring", n: "fall", anchor: "target" }],
    minDepth: 2,
  },
  {
    key: "flailCrush",
    moveset: "flail",
    name: "粉砕",
    icon: "砕",
    verb: "鉄球を叩きつけ、崩れている敵には特に強く効く",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "hit", vs: "stagger" }],
  },
  {
    key: "flailOrbit",
    moveset: "flail",
    name: "周回",
    icon: "周",
    verb: "鉄球を周回させ、敵の弾を払いながら 5 度打つ",
    tags: ["melee", "defense"],
    attack: MELEE,
    acts: [{ kind: "ring", n: "guard", clearsBullets: true }],
  },
  {
    key: "flailPound",
    moveset: "flail",
    name: "連打",
    icon: "連",
    verb: "カーソル地点を鉄球で 3 度連打する",
    tags: ["area"],
    attack: AREA,
    acts: [
      { kind: "ring", n: "s1", anchor: "target" },
      { kind: "ring", n: "s2", anchor: "target" },
      { kind: "ring", n: "s3", anchor: "target" },
    ],
  },
  {
    key: "flailStun",
    moveset: "flail",
    name: "脳天打ち",
    icon: "脳",
    verb: "鉄球を頭上から叩き込み、痺れさせる",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "down" }],
  },
];

export const POLEARM_ART_SPECS: readonly ArtSpec[] = [...SPEAR, ...SCYTHE, ...STAFF, ...CHAIN_SICKLE, ...WHIP, ...FLAIL];
