import { attack } from "../../core/element";
import type { ArtSpec } from "./types";

/**
 * 投げ・仕掛けの武器技（投擲・擲弾・仕掛け・戦輪）。数値は data/balance/skills/ART/<武器種>.json。
 * 武器種の手触り（docs/ideas/weapon-skills.md の各節）を伸ばす方向で作る
 */

const RANGED = attack("ranged", "physical");
const AREA = attack("area", "physical");
const FIRE_AREA = attack("area", "arcane", "fire");
const ICE_AREA = attack("area", "arcane", "ice");
const POISON_AREA = attack("area", "arcane", "poison");
const POISON_R = attack("ranged", "arcane", "poison");
const ICE_R = attack("ranged", "arcane", "ice");
const MELEE = attack("melee", "physical");

// ---- 投擲: 手数・状態異常・搦め手。単発の重い一投から扇・連投まで幅広い ----
const THROWN: readonly ArtSpec[] = [
  {
    key: "thrownFan",
    moveset: "thrown",
    name: "扇投げ",
    icon: "扇",
    verb: "短刀を扇に投げ、並んだ敵に当てる",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "fan" }],
  },
  {
    key: "thrownPoison",
    moveset: "thrown",
    name: "毒刃",
    icon: "毒",
    verb: "毒を塗った刃を投げ、当てた敵をむしばむ",
    tags: ["projectile"],
    attack: POISON_R,
    acts: [{ kind: "shot", n: "blade" }],
  },
  {
    key: "thrownRain",
    moveset: "thrown",
    name: "刃の雨",
    icon: "雨",
    verb: "カーソル地点に刃を降らせ、4 度斬りつける",
    tags: ["area"],
    attack: AREA,
    acts: [
      { kind: "ring", n: "r1", anchor: "target" },
      { kind: "ring", n: "r2", anchor: "target" },
      { kind: "ring", n: "r3", anchor: "target" },
      { kind: "ring", n: "r4", anchor: "target" },
    ],
    minDepth: 2,
  },
  {
    key: "thrownRicochet",
    moveset: "thrown",
    name: "跳ね刃",
    icon: "跳",
    verb: "刃を投げ、壁や敵に跳ね返りながら当たり続ける",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "blade", shot: "ricochet" }],
  },
  {
    key: "thrownVolley",
    moveset: "thrown",
    name: "連投",
    icon: "連",
    verb: "刃を 4 回続けて投げる（投げる間も向きを変えられる）",
    tags: ["projectile"],
    attack: RANGED,
    acts: [
      { kind: "shot", n: "s1" },
      { kind: "shot", n: "s2" },
      { kind: "shot", n: "s3" },
      { kind: "shot", n: "s4" },
    ],
  },
  {
    key: "thrownPin",
    moveset: "thrown",
    name: "影縫い投げ",
    icon: "縫",
    verb: "刃を投げて地に縫い止め、当てた敵を麻痺させる",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "pin" }],
  },
  {
    key: "thrownSmoke",
    moveset: "thrown",
    name: "煙幕玉",
    icon: "幕",
    verb: "足元に煙幕を張り、敵の弾を遮る",
    tags: ["defense"],
    attack: null,
    acts: [{ kind: "ring", n: "smoke", terrain: "smoke", clearsBullets: true }],
  },
  {
    key: "thrownBomb",
    moveset: "thrown",
    name: "炸裂玉",
    icon: "炸",
    verb: "カーソル地点へ玉を投げ、着弾して爆ぜる",
    tags: ["area"],
    attack: AREA,
    acts: [{ kind: "ring", n: "blast", anchor: "target" }],
  },
  {
    key: "thrownBola",
    moveset: "thrown",
    name: "絡み紐",
    icon: "紐",
    verb: "紐のついた重りを投げ、当てた敵の足を強く冷やして鈍らせる",
    tags: ["projectile"],
    attack: ICE_R,
    acts: [{ kind: "shot", n: "bola" }],
  },
  {
    key: "thrownCaltrops",
    moveset: "thrown",
    name: "鉄菱",
    icon: "鉄",
    verb: "足元に鉄菱を撒き、踏んだ範囲の敵を傷つけて崩れる床を残す",
    tags: ["area"],
    attack: AREA,
    acts: [{ kind: "ring", n: "spikes", terrain: "rubble" }],
  },
  {
    key: "thrownDagger",
    moveset: "thrown",
    name: "投げ短剣",
    icon: "剣",
    verb: "短剣を鋭く一投し、素早く重く当てる",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "dagger" }],
  },
];

// ---- 擲弾: 照準地点へ撃ち込む榴弾。地形・状態異常の種類が豊富 ----
const GRENADE: readonly ArtSpec[] = [
  {
    key: "grenadeCluster",
    moveset: "grenade",
    name: "子爆弾",
    icon: "子",
    verb: "カーソルの周りに小さな爆弾を 3 つ投げ込む",
    tags: ["area"],
    attack: AREA,
    acts: [
      { kind: "ring", n: "c1", anchor: "target" },
      { kind: "ring", n: "c2", anchor: "target" },
      { kind: "ring", n: "c3", anchor: "target" },
    ],
    minDepth: 2,
  },
  {
    key: "grenadeFrag",
    moveset: "grenade",
    name: "破片榴弾",
    icon: "破",
    verb: "カーソル地点で榴弾が弾け、破片が周りへ突き刺さる",
    tags: ["area"],
    attack: AREA,
    acts: [{ kind: "ring", n: "frag", anchor: "target" }],
  },
  {
    key: "grenadeIncendiary",
    moveset: "grenade",
    name: "焼夷榴弾",
    icon: "焼",
    verb: "カーソル地点に着弾し、炎の床を残して燃やす",
    tags: ["area", "fire"],
    attack: FIRE_AREA,
    acts: [{ kind: "ring", n: "burn", anchor: "target", terrain: "fire" }],
  },
  {
    key: "grenadeSmoke",
    moveset: "grenade",
    name: "煙幕弾",
    icon: "煙",
    verb: "カーソル地点に煙幕弾を撃ち込み、視界と敵弾を遮る",
    tags: ["defense"],
    attack: null,
    acts: [{ kind: "ring", n: "smoke", anchor: "target", terrain: "smoke", clearsBullets: true }],
  },
  {
    key: "grenadeConcussion",
    moveset: "grenade",
    name: "衝撃榴弾",
    icon: "衝",
    verb: "カーソル地点で炸裂し、周りの敵を大きく吹き飛ばす",
    tags: ["area"],
    attack: AREA,
    acts: [{ kind: "ring", n: "blast", anchor: "target" }],
  },
  {
    key: "grenadeGas",
    moveset: "grenade",
    name: "毒ガス弾",
    icon: "毒",
    verb: "カーソル地点に毒ガスをまき、毒沼を残す",
    tags: ["area"],
    attack: POISON_AREA,
    acts: [{ kind: "ring", n: "gas", anchor: "target", terrain: "bog" }],
  },
  {
    key: "grenadeFlash",
    moveset: "grenade",
    name: "閃光榴弾",
    icon: "閃",
    verb: "カーソル地点で閃光を放ち、周りの敵の目をくらませて怯えさせる",
    tags: ["area"],
    attack: null,
    acts: [{ kind: "ring", n: "flash", anchor: "target" }],
  },
  {
    key: "grenadeFreeze",
    moveset: "grenade",
    name: "冷却榴弾",
    icon: "凍",
    verb: "カーソル地点を凍てつかせ、氷床を残す",
    tags: ["area", "cold"],
    attack: ICE_AREA,
    acts: [{ kind: "ring", n: "freeze", anchor: "target", terrain: "ice" }],
  },
  {
    key: "grenadeBarrage",
    moveset: "grenade",
    name: "連続投擲",
    icon: "投",
    verb: "前方へ榴弾を立て続けに 3 つ投げ込む",
    tags: ["area"],
    attack: AREA,
    acts: [
      { kind: "ring", n: "near" },
      { kind: "ring", n: "mid" },
      { kind: "ring", n: "far" },
    ],
  },
  {
    key: "grenadeSticky",
    moveset: "grenade",
    name: "粘着弾",
    icon: "粘",
    verb: "カーソル地点に粘着榴弾を張り付け、少し遅れて大きく爆ぜる",
    tags: ["area"],
    attack: AREA,
    acts: [{ kind: "ring", n: "stick", anchor: "target" }],
    minDepth: 2,
  },
  {
    key: "grenadeBounce",
    moveset: "grenade",
    name: "弾み弾",
    icon: "跳",
    verb: "榴弾を放ち、跳ね返りながら当たった敵を巻き込んで弾ける",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "bounce", shot: "ricochet" }],
  },
];

// ---- 仕掛け: 足元・前方に罠を仕込む。設置の起爆や地形の組み合わせが芯 ----
const TRAPPER: readonly ArtSpec[] = [
  {
    key: "trapperDetonate",
    moveset: "trapper",
    name: "一斉起爆",
    icon: "起",
    verb: "置いた設置弾をすべて起爆し、自分の周りも巻き込む",
    tags: ["area"],
    attack: AREA,
    acts: [
      { kind: "detonate", n: "boom" },
      { kind: "ring", n: "blast" },
    ],
  },
  {
    key: "trapperSpike",
    moveset: "trapper",
    name: "棘罠",
    icon: "棘",
    verb: "足元に棘罠を仕掛け、少し遅れて突き出て出血させる",
    tags: ["area"],
    attack: AREA,
    acts: [{ kind: "ring", n: "spike" }],
  },
  {
    key: "trapperNet",
    moveset: "trapper",
    name: "網",
    icon: "網",
    verb: "カーソル地点に網を投げ広げ、絡めた敵を凍えさせる",
    tags: ["area", "cold"],
    attack: ICE_AREA,
    acts: [{ kind: "ring", n: "net", anchor: "target" }],
  },
  {
    key: "trapperTripwire",
    moveset: "trapper",
    name: "張り線",
    icon: "張",
    verb: "前方に張り線を仕込み、触れた敵を麻痺させる",
    tags: ["area"],
    attack: AREA,
    acts: [{ kind: "line", n: "wire" }],
  },
  {
    key: "trapperBearTrap",
    moveset: "trapper",
    name: "虎挟み",
    icon: "虎",
    verb: "カーソル地点に虎挟みを仕掛け、少し遅れて重く挟み込む",
    tags: ["area"],
    attack: AREA,
    acts: [{ kind: "ring", n: "trap", anchor: "target" }],
    minDepth: 2,
  },
  {
    key: "trapperLure",
    moveset: "trapper",
    name: "誘い餌",
    icon: "餌",
    verb: "カーソル地点に餌を投げ、周りの敵を引き寄せる",
    tags: ["area"],
    attack: null,
    acts: [{ kind: "pull", n: "lure", anchor: "target" }],
  },
  {
    key: "trapperOil",
    moveset: "trapper",
    name: "油の罠",
    icon: "油",
    verb: "足元に油を撒き、踏んだ敵を滑らせる",
    tags: ["area"],
    attack: null,
    acts: [{ kind: "ring", n: "oil", terrain: "oil" }],
  },
  {
    key: "trapperFire",
    moveset: "trapper",
    name: "火付け",
    icon: "火",
    verb: "前方に火を放ち、燃える帯を残す",
    tags: ["area", "fire"],
    attack: FIRE_AREA,
    acts: [{ kind: "line", n: "fire", terrain: "fire" }],
  },
  {
    key: "trapperSmoke",
    moveset: "trapper",
    name: "煙の罠",
    icon: "煙",
    verb: "足元に煙の罠を仕掛け、敵の弾を遮って姿を隠す",
    tags: ["defense"],
    attack: null,
    acts: [{ kind: "ring", n: "smoke", terrain: "smoke", clearsBullets: true }],
  },
  {
    key: "trapperShrapnel",
    moveset: "trapper",
    name: "破片撒き",
    icon: "破",
    verb: "周りへ破片を撒き散らし、近くの敵を切り裂く",
    tags: ["area"],
    attack: AREA,
    acts: [{ kind: "ring", n: "shrapnel" }],
  },
  {
    key: "trapperCaltrops",
    moveset: "trapper",
    name: "撒き菱",
    icon: "撒",
    verb: "足元に菱を撒き、踏んだ敵を傷つけて崩れる床を残す",
    tags: ["area"],
    attack: AREA,
    acts: [{ kind: "ring", n: "caltrops", terrain: "rubble" }],
  },
];

// ---- 戦輪: 手に持ち投げる刃の輪。近接と遠距離を行き来する ----
const WAR_RING: readonly ArtSpec[] = [
  {
    key: "warRingSpin",
    moveset: "warRing",
    name: "輪の円舞",
    icon: "舞",
    verb: "輪を回しながらその場で回転し、周りを 3 度斬る",
    tags: ["melee", "area"],
    attack: AREA,
    acts: [{ kind: "ring", n: "spin" }],
  },
  {
    key: "warRingThrow",
    moveset: "warRing",
    name: "大投げ",
    icon: "投",
    verb: "輪を強く投げつけ、重く当てる",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "throw" }],
  },
  {
    key: "warRingRicochet",
    moveset: "warRing",
    name: "跳ね輪",
    icon: "跳",
    verb: "輪を投げ、壁や敵に跳ね返りながら当て続ける",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "ring", shot: "ricochet" }],
  },
  {
    key: "warRingFan",
    moveset: "warRing",
    name: "三連輪",
    icon: "三",
    verb: "輪を 3 つ、扇に広げて投げる",
    tags: ["projectile"],
    attack: RANGED,
    acts: [{ kind: "shot", n: "fan" }],
  },
  {
    key: "warRingGuard",
    moveset: "warRing",
    name: "守り輪",
    icon: "守",
    verb: "輪を掲げて周りの敵弾を消す",
    tags: ["defense"],
    attack: null,
    acts: [{ kind: "ring", n: "guard", clearsBullets: true }],
  },
  {
    key: "warRingStorm",
    moveset: "warRing",
    name: "輪嵐",
    icon: "嵐",
    verb: "カーソル地点に輪の嵐を起こし、しばらく斬り続ける",
    tags: ["area"],
    attack: AREA,
    acts: [
      { kind: "ring", n: "s1", anchor: "target" },
      { kind: "ring", n: "s2", anchor: "target" },
      { kind: "ring", n: "s3", anchor: "target" },
      { kind: "ring", n: "s4", anchor: "target" },
    ],
    minDepth: 2,
  },
  {
    key: "warRingDash",
    moveset: "warRing",
    name: "輪走り",
    icon: "駆",
    verb: "輪を構えて照準の方向へ駆け抜け、通り道の敵を斬る",
    tags: ["melee", "movement"],
    attack: MELEE,
    acts: [{ kind: "dash", n: "dash" }],
  },
  {
    key: "warRingSever",
    moveset: "warRing",
    name: "断ち輪",
    icon: "断",
    verb: "輪の刃を長く薙ぎ、当てた敵を出血させる",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "line", n: "sever" }],
  },
  {
    key: "warRingEcho",
    moveset: "warRing",
    name: "追い輪",
    icon: "追",
    verb: "輪を 3 度続けて投げ、追いすがるように当てる",
    tags: ["projectile"],
    attack: RANGED,
    acts: [
      { kind: "shot", n: "s1" },
      { kind: "shot", n: "s2" },
      { kind: "shot", n: "s3" },
    ],
  },
  {
    key: "warRingSlash",
    moveset: "warRing",
    name: "輪裂き",
    icon: "払",
    verb: "輪を大きく振り払い、前方を薙ぐ",
    tags: ["melee"],
    attack: MELEE,
    acts: [{ kind: "arc", n: "sweep" }],
  },
  {
    key: "warRingCyclone",
    moveset: "warRing",
    name: "旋風輪",
    icon: "旋",
    verb: "輪を全方位へ振り回し、周りをまとめて叩く",
    tags: ["melee", "area"],
    attack: AREA,
    acts: [{ kind: "ring", n: "cyclone" }],
    minDepth: 2,
  },
];

export const THROWING_ART_SPECS: readonly ArtSpec[] = [...THROWN, ...GRENADE, ...TRAPPER, ...WAR_RING];
